// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/AnswerInlineQueryRequest.hpp"

namespace TgBot {
    void to_json(json& j, const AnswerInlineQueryRequest& value) {
        j = json{};
        j["inline_query_id"] = value.inline_query_id;
        j["results"] = value.results;
    if (value.cache_time != 0) { 
                    j["cache_time"] = value.cache_time; 
            }
    if (value.is_personal) { 
                    j["is_personal"] = value.is_personal; 
            }
    if (!value.next_offset.empty()) { 
                    j["next_offset"] = value.next_offset; 
            }
    if (value.button) { 
                    j["button"] = value.button; 
            }
    }

    void from_json(const json& j, AnswerInlineQueryRequest& value) {
        if (j.contains("inline_query_id")) {
            j.at("inline_query_id").get_to(value.inline_query_id);
        }
        if (j.contains("results")) {
            j.at("results").get_to(value.results);
        }
        if (j.contains("cache_time")) {
            j.at("cache_time").get_to(value.cache_time);
        }
        if (j.contains("is_personal")) {
            j.at("is_personal").get_to(value.is_personal);
        }
        if (j.contains("next_offset")) {
            j.at("next_offset").get_to(value.next_offset);
        }
        if (j.contains("button")) {
            j.at("button").get_to(value.button);
        }
    }
}
