// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/BanChatMemberRequest.hpp"

namespace TgBot {
    void to_json(json& j, const BanChatMemberRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["user_id"] = value.user_id;
    if (value.until_date != 0) { 
                    j["until_date"] = value.until_date; 
            }
    if (value.revoke_messages) { 
                    j["revoke_messages"] = value.revoke_messages; 
            }
    }

    void from_json(const json& j, BanChatMemberRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("until_date")) {
            j.at("until_date").get_to(value.until_date);
        }
        if (j.contains("revoke_messages")) {
            j.at("revoke_messages").get_to(value.revoke_messages);
        }
    }
}
