// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/CloseRequest.hpp"

namespace TgBot {
    void to_json(json& j, const CloseRequest& value) {
        j = json{};
    }

    void from_json(const json& j, CloseRequest& value) {
    }
}
