// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/DeleteChatStickerSetRequest.hpp"

namespace TgBot {
    void to_json(json& j, const DeleteChatStickerSetRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
    }

    void from_json(const json& j, DeleteChatStickerSetRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
    }
}
