// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/EditGeneralForumTopicRequest.hpp"

namespace TgBot {
    void to_json(json& j, const EditGeneralForumTopicRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["name"] = value.name;
    }

    void from_json(const json& j, EditGeneralForumTopicRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
    }
}
