// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetForumTopicIconStickersRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetForumTopicIconStickersRequest& value) {
        j = json{};
    }

    void from_json(const json& j, GetForumTopicIconStickersRequest& value) {
    }
}
