// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetGameHighScoresRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetGameHighScoresRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
    if (value.chat_id != 0) { 
                    j["chat_id"] = value.chat_id; 
            }
    if (value.message_id != 0) { 
                    j["message_id"] = value.message_id; 
            }
    if (!value.inline_message_id.empty()) { 
                    j["inline_message_id"] = value.inline_message_id; 
            }
    }

    void from_json(const json& j, GetGameHighScoresRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("inline_message_id")) {
            j.at("inline_message_id").get_to(value.inline_message_id);
        }
    }
}
