// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetMyDescriptionRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetMyDescriptionRequest& value) {
        j = json{};
    if (!value.language_code.empty()) { 
                    j["language_code"] = value.language_code; 
            }
    }

    void from_json(const json& j, GetMyDescriptionRequest& value) {
        if (j.contains("language_code")) {
            j.at("language_code").get_to(value.language_code);
        }
    }
}
