// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetUserGiftsRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetUserGiftsRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
    if (value.exclude_unlimited) { 
                    j["exclude_unlimited"] = value.exclude_unlimited; 
            }
    if (value.exclude_limited_upgradable) { 
                    j["exclude_limited_upgradable"] = value.exclude_limited_upgradable; 
            }
    if (value.exclude_limited_non_upgradable) { 
                    j["exclude_limited_non_upgradable"] = value.exclude_limited_non_upgradable; 
            }
    if (value.exclude_from_blockchain) { 
                    j["exclude_from_blockchain"] = value.exclude_from_blockchain; 
            }
    if (value.exclude_unique) { 
                    j["exclude_unique"] = value.exclude_unique; 
            }
    if (value.sort_by_price) { 
                    j["sort_by_price"] = value.sort_by_price; 
            }
    if (!value.offset.empty()) { 
                    j["offset"] = value.offset; 
            }
    if (value.limit != 0) { 
                    j["limit"] = value.limit; 
            }
    }

    void from_json(const json& j, GetUserGiftsRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("exclude_unlimited")) {
            j.at("exclude_unlimited").get_to(value.exclude_unlimited);
        }
        if (j.contains("exclude_limited_upgradable")) {
            j.at("exclude_limited_upgradable").get_to(value.exclude_limited_upgradable);
        }
        if (j.contains("exclude_limited_non_upgradable")) {
            j.at("exclude_limited_non_upgradable").get_to(value.exclude_limited_non_upgradable);
        }
        if (j.contains("exclude_from_blockchain")) {
            j.at("exclude_from_blockchain").get_to(value.exclude_from_blockchain);
        }
        if (j.contains("exclude_unique")) {
            j.at("exclude_unique").get_to(value.exclude_unique);
        }
        if (j.contains("sort_by_price")) {
            j.at("sort_by_price").get_to(value.sort_by_price);
        }
        if (j.contains("offset")) {
            j.at("offset").get_to(value.offset);
        }
        if (j.contains("limit")) {
            j.at("limit").get_to(value.limit);
        }
    }
}
