// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetUserChatBoostsRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetUserChatBoostsRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["user_id"] = value.user_id;
    }

    void from_json(const json& j, GetUserChatBoostsRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
    }
}
