// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/RemoveBusinessAccountProfilePhotoRequest.hpp"

namespace TgBot {
    void to_json(json& j, const RemoveBusinessAccountProfilePhotoRequest& value) {
        j = json{};
        j["business_connection_id"] = value.business_connection_id;
    if (value.is_public) { 
                    j["is_public"] = value.is_public; 
            }
    }

    void from_json(const json& j, RemoveBusinessAccountProfilePhotoRequest& value) {
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("is_public")) {
            j.at("is_public").get_to(value.is_public);
        }
    }
}
