// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/RepostStoryRequest.hpp"

namespace TgBot {
    void to_json(json& j, const RepostStoryRequest& value) {
        j = json{};
        j["business_connection_id"] = value.business_connection_id;
        j["from_chat_id"] = value.from_chat_id;
        j["from_story_id"] = value.from_story_id;
        j["active_period"] = value.active_period;
    if (value.post_to_chat_page) { 
                    j["post_to_chat_page"] = value.post_to_chat_page; 
            }
    if (value.protect_content) { 
                    j["protect_content"] = value.protect_content; 
            }
    }

    void from_json(const json& j, RepostStoryRequest& value) {
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("from_chat_id")) {
            j.at("from_chat_id").get_to(value.from_chat_id);
        }
        if (j.contains("from_story_id")) {
            j.at("from_story_id").get_to(value.from_story_id);
        }
        if (j.contains("active_period")) {
            j.at("active_period").get_to(value.active_period);
        }
        if (j.contains("post_to_chat_page")) {
            j.at("post_to_chat_page").get_to(value.post_to_chat_page);
        }
        if (j.contains("protect_content")) {
            j.at("protect_content").get_to(value.protect_content);
        }
    }
}
