// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SendMessageRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SendMessageRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["text"] = value.text;
    if (!value.business_connection_id.empty()) { 
                    j["business_connection_id"] = value.business_connection_id; 
            }
    if (value.message_thread_id != 0) { 
                    j["message_thread_id"] = value.message_thread_id; 
            }
    if (value.direct_messages_topic_id != 0) { 
                    j["direct_messages_topic_id"] = value.direct_messages_topic_id; 
            }
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.entities.empty()) { 
                    j["entities"] = value.entities; 
            }
    if (value.link_preview_options) { 
                    j["link_preview_options"] = value.link_preview_options; 
            }
    if (value.disable_notification) { 
                    j["disable_notification"] = value.disable_notification; 
            }
    if (value.protect_content) { 
                    j["protect_content"] = value.protect_content; 
            }
    if (value.allow_paid_broadcast) { 
                    j["allow_paid_broadcast"] = value.allow_paid_broadcast; 
            }
    if (!value.message_effect_id.empty()) { 
                    j["message_effect_id"] = value.message_effect_id; 
            }
    if (value.suggested_post_parameters) { 
                    j["suggested_post_parameters"] = value.suggested_post_parameters; 
            }
    if (value.reply_parameters) { 
                    j["reply_parameters"] = value.reply_parameters; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    }

    void from_json(const json& j, SendMessageRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("message_thread_id")) {
            j.at("message_thread_id").get_to(value.message_thread_id);
        }
        if (j.contains("direct_messages_topic_id")) {
            j.at("direct_messages_topic_id").get_to(value.direct_messages_topic_id);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("entities")) {
            j.at("entities").get_to(value.entities);
        }
        if (j.contains("link_preview_options")) {
            j.at("link_preview_options").get_to(value.link_preview_options);
        }
        if (j.contains("disable_notification")) {
            j.at("disable_notification").get_to(value.disable_notification);
        }
        if (j.contains("protect_content")) {
            j.at("protect_content").get_to(value.protect_content);
        }
        if (j.contains("allow_paid_broadcast")) {
            j.at("allow_paid_broadcast").get_to(value.allow_paid_broadcast);
        }
        if (j.contains("message_effect_id")) {
            j.at("message_effect_id").get_to(value.message_effect_id);
        }
        if (j.contains("suggested_post_parameters")) {
            j.at("suggested_post_parameters").get_to(value.suggested_post_parameters);
        }
        if (j.contains("reply_parameters")) {
            j.at("reply_parameters").get_to(value.reply_parameters);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
