// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetCustomEmojiStickerSetThumbnailRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetCustomEmojiStickerSetThumbnailRequest& value) {
        j = json{};
        j["name"] = value.name;
    if (!value.custom_emoji_id.empty()) { 
                    j["custom_emoji_id"] = value.custom_emoji_id; 
            }
    }

    void from_json(const json& j, SetCustomEmojiStickerSetThumbnailRequest& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("custom_emoji_id")) {
            j.at("custom_emoji_id").get_to(value.custom_emoji_id);
        }
    }
}
