// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetMyDefaultAdministratorRightsRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetMyDefaultAdministratorRightsRequest& value) {
        j = json{};
    if (value.rights) { 
                    j["rights"] = value.rights; 
            }
    if (value.for_channels) { 
                    j["for_channels"] = value.for_channels; 
            }
    }

    void from_json(const json& j, SetMyDefaultAdministratorRightsRequest& value) {
        if (j.contains("rights")) {
            j.at("rights").get_to(value.rights);
        }
        if (j.contains("for_channels")) {
            j.at("for_channels").get_to(value.for_channels);
        }
    }
}
