// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetMessageReactionRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetMessageReactionRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["message_id"] = value.message_id;
    if (!value.reaction.empty()) { 
                    j["reaction"] = value.reaction; 
            }
    if (value.is_big) { 
                    j["is_big"] = value.is_big; 
            }
    }

    void from_json(const json& j, SetMessageReactionRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("reaction")) {
            j.at("reaction").get_to(value.reaction);
        }
        if (j.contains("is_big")) {
            j.at("is_big").get_to(value.is_big);
        }
    }
}
