// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetPassportDataErrorsRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetPassportDataErrorsRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
        j["errors"] = value.errors;
    }

    void from_json(const json& j, SetPassportDataErrorsRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("errors")) {
            j.at("errors").get_to(value.errors);
        }
    }
}
