// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetStickerSetTitleRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetStickerSetTitleRequest& value) {
        j = json{};
        j["name"] = value.name;
        j["title"] = value.title;
    }

    void from_json(const json& j, SetStickerSetTitleRequest& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
    }
}
