// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetWebhookRequest.hpp"
#include <string>

namespace TgBot {
    void to_json(json& j, const SetWebhookRequest& value) {
        j = json{};
        j["url"] = value.url;
    if (!value.ip_address.empty()) { 
                    j["ip_address"] = value.ip_address; 
            }
    if (value.max_connections != 0) { 
                    j["max_connections"] = value.max_connections; 
            }
    if (!value.allowed_updates.empty()) { 
                    j["allowed_updates"] = value.allowed_updates; 
            }
    if (value.drop_pending_updates) { 
                    j["drop_pending_updates"] = value.drop_pending_updates; 
            }
    if (!value.secret_token.empty()) { 
                    j["secret_token"] = value.secret_token; 
            }
    }

    void from_json(const json& j, SetWebhookRequest& value) {
        if (j.contains("url")) {
            j.at("url").get_to(value.url);
        }
        if (j.contains("ip_address")) {
            j.at("ip_address").get_to(value.ip_address);
        }
        if (j.contains("max_connections")) {
            j.at("max_connections").get_to(value.max_connections);
        }
        if (j.contains("allowed_updates")) {
            j.at("allowed_updates").get_to(value.allowed_updates);
        }
        if (j.contains("drop_pending_updates")) {
            j.at("drop_pending_updates").get_to(value.drop_pending_updates);
        }
        if (j.contains("secret_token")) {
            j.at("secret_token").get_to(value.secret_token);
        }
    }


    std::string toMultipart(const SetWebhookRequest& value, const std::string& boundary) {
        std::string body;

        // Non-file field: url
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"url\"\r\n\r\n";
        body += value.url + "\r\n";

        // Non-file field: ip_address
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"ip_address\"\r\n\r\n";
        body += value.ip_address + "\r\n";

        // Non-file field: max_connections
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"max_connections\"\r\n\r\n";
        body += std::to_string(value.max_connections) + "\r\n";

        // Non-file field: allowed_updates
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"allowed_updates\"\r\n\r\n";
        for (const auto& item : value.allowed_updates) {
            body += item + "\r\n";
        }

        // Non-file field: drop_pending_updates
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"drop_pending_updates\"\r\n\r\n";
        body += (value.drop_pending_updates ? "true" : "false") + std::string("\r\n");

        // Non-file field: secret_token
        body += "--" + boundary + "\r\n";
        body += "Content-Disposition: form-data; name=\"secret_token\"\r\n\r\n";
        body += value.secret_token + "\r\n";

        // File field: certificate
        if (value.certificate) {
            body += "--" + boundary + "\r\n";
            body += "Content-Disposition: form-data; name=\"certificate\"; filename=\"" + value.certificate->fileName + "\".\r\n";
            body += "Content-Type: " + value.certificate->mimeType + "\r\n\r\n";
            body += value.certificate->data + "\r\n";
        }

        body += "--" + boundary + "--\r\n";
        return body;
    }
}
