// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/StopPollRequest.hpp"

namespace TgBot {
    void to_json(json& j, const StopPollRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["message_id"] = value.message_id;
    if (!value.business_connection_id.empty()) { 
                    j["business_connection_id"] = value.business_connection_id; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    }

    void from_json(const json& j, StopPollRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
