// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BackgroundTypePattern.hpp"
#include "types/Document.hpp"
#include "types/BackgroundFill.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BackgroundTypePattern& value) {
        j = json{};
        j["type"] = value.type_;
        j["document"] = value.document;
        j["fill"] = value.fill;
        j["intensity"] = value.intensity;
    if (value.is_inverted) { 
                    j["is_inverted"] = value.is_inverted; 
            }
    if (value.is_moving) { 
                    j["is_moving"] = value.is_moving; 
            }
    }

    void from_json(const json& j, BackgroundTypePattern& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("document")) {
            j.at("document").get_to(value.document);
        }
        if (j.contains("fill")) {
            j.at("fill").get_to(value.fill);
        }
        if (j.contains("intensity")) {
            j.at("intensity").get_to(value.intensity);
        }
        if (j.contains("is_inverted")) {
            j.at("is_inverted").get_to(value.is_inverted);
        }
        if (j.contains("is_moving")) {
            j.at("is_moving").get_to(value.is_moving);
        }
    }
}
