// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BusinessOpeningHoursInterval.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BusinessOpeningHoursInterval& value) {
        j = json{};
        j["opening_minute"] = value.opening_minute;
        j["closing_minute"] = value.closing_minute;
    }

    void from_json(const json& j, BusinessOpeningHoursInterval& value) {
        if (j.contains("opening_minute")) {
            j.at("opening_minute").get_to(value.opening_minute);
        }
        if (j.contains("closing_minute")) {
            j.at("closing_minute").get_to(value.closing_minute);
        }
    }
}
