// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/CallbackQuery.hpp"
#include "types/User.hpp"
#include "types/MaybeInaccessibleMessage.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const CallbackQuery& value) {
        j = json{};
        j["id"] = value.id;
        j["from"] = value.from;
        j["chat_instance"] = value.chat_instance;
    if (value.message) { 
                    j["message"] = value.message; 
            }
    if (!value.inline_message_id.empty()) { 
                    j["inline_message_id"] = value.inline_message_id; 
            }
    if (!value.data.empty()) { 
                    j["data"] = value.data; 
            }
    if (!value.game_short_name.empty()) { 
                    j["game_short_name"] = value.game_short_name; 
            }
    }

    void from_json(const json& j, CallbackQuery& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("chat_instance")) {
            j.at("chat_instance").get_to(value.chat_instance);
        }
        if (j.contains("message")) {
            j.at("message").get_to(value.message);
        }
        if (j.contains("inline_message_id")) {
            j.at("inline_message_id").get_to(value.inline_message_id);
        }
        if (j.contains("data")) {
            j.at("data").get_to(value.data);
        }
        if (j.contains("game_short_name")) {
            j.at("game_short_name").get_to(value.game_short_name);
        }
    }
}
