// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChatInviteLink.hpp"
#include "types/User.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChatInviteLink& value) {
        j = json{};
        j["invite_link"] = value.invite_link;
        j["creator"] = value.creator;
        j["creates_join_request"] = value.creates_join_request;
        j["is_primary"] = value.is_primary;
        j["is_revoked"] = value.is_revoked;
    if (!value.name.empty()) { 
                    j["name"] = value.name; 
            }
    if (value.expire_date != 0) { 
                    j["expire_date"] = value.expire_date; 
            }
    if (value.member_limit != 0) { 
                    j["member_limit"] = value.member_limit; 
            }
    if (value.pending_join_request_count != 0) { 
                    j["pending_join_request_count"] = value.pending_join_request_count; 
            }
    if (value.subscription_period != 0) { 
                    j["subscription_period"] = value.subscription_period; 
            }
    if (value.subscription_price != 0) { 
                    j["subscription_price"] = value.subscription_price; 
            }
    }

    void from_json(const json& j, ChatInviteLink& value) {
        if (j.contains("invite_link")) {
            j.at("invite_link").get_to(value.invite_link);
        }
        if (j.contains("creator")) {
            j.at("creator").get_to(value.creator);
        }
        if (j.contains("creates_join_request")) {
            j.at("creates_join_request").get_to(value.creates_join_request);
        }
        if (j.contains("is_primary")) {
            j.at("is_primary").get_to(value.is_primary);
        }
        if (j.contains("is_revoked")) {
            j.at("is_revoked").get_to(value.is_revoked);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("expire_date")) {
            j.at("expire_date").get_to(value.expire_date);
        }
        if (j.contains("member_limit")) {
            j.at("member_limit").get_to(value.member_limit);
        }
        if (j.contains("pending_join_request_count")) {
            j.at("pending_join_request_count").get_to(value.pending_join_request_count);
        }
        if (j.contains("subscription_period")) {
            j.at("subscription_period").get_to(value.subscription_period);
        }
        if (j.contains("subscription_price")) {
            j.at("subscription_price").get_to(value.subscription_price);
        }
    }
}
