// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChatPermissions.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChatPermissions& value) {
        j = json{};
    if (value.can_send_messages) { 
                    j["can_send_messages"] = value.can_send_messages; 
            }
    if (value.can_send_audios) { 
                    j["can_send_audios"] = value.can_send_audios; 
            }
    if (value.can_send_documents) { 
                    j["can_send_documents"] = value.can_send_documents; 
            }
    if (value.can_send_photos) { 
                    j["can_send_photos"] = value.can_send_photos; 
            }
    if (value.can_send_videos) { 
                    j["can_send_videos"] = value.can_send_videos; 
            }
    if (value.can_send_video_notes) { 
                    j["can_send_video_notes"] = value.can_send_video_notes; 
            }
    if (value.can_send_voice_notes) { 
                    j["can_send_voice_notes"] = value.can_send_voice_notes; 
            }
    if (value.can_send_polls) { 
                    j["can_send_polls"] = value.can_send_polls; 
            }
    if (value.can_send_other_messages) { 
                    j["can_send_other_messages"] = value.can_send_other_messages; 
            }
    if (value.can_add_web_page_previews) { 
                    j["can_add_web_page_previews"] = value.can_add_web_page_previews; 
            }
    if (value.can_edit_tag) { 
                    j["can_edit_tag"] = value.can_edit_tag; 
            }
    if (value.can_change_info) { 
                    j["can_change_info"] = value.can_change_info; 
            }
    if (value.can_invite_users) { 
                    j["can_invite_users"] = value.can_invite_users; 
            }
    if (value.can_pin_messages) { 
                    j["can_pin_messages"] = value.can_pin_messages; 
            }
    if (value.can_manage_topics) { 
                    j["can_manage_topics"] = value.can_manage_topics; 
            }
    }

    void from_json(const json& j, ChatPermissions& value) {
        if (j.contains("can_send_messages")) {
            j.at("can_send_messages").get_to(value.can_send_messages);
        }
        if (j.contains("can_send_audios")) {
            j.at("can_send_audios").get_to(value.can_send_audios);
        }
        if (j.contains("can_send_documents")) {
            j.at("can_send_documents").get_to(value.can_send_documents);
        }
        if (j.contains("can_send_photos")) {
            j.at("can_send_photos").get_to(value.can_send_photos);
        }
        if (j.contains("can_send_videos")) {
            j.at("can_send_videos").get_to(value.can_send_videos);
        }
        if (j.contains("can_send_video_notes")) {
            j.at("can_send_video_notes").get_to(value.can_send_video_notes);
        }
        if (j.contains("can_send_voice_notes")) {
            j.at("can_send_voice_notes").get_to(value.can_send_voice_notes);
        }
        if (j.contains("can_send_polls")) {
            j.at("can_send_polls").get_to(value.can_send_polls);
        }
        if (j.contains("can_send_other_messages")) {
            j.at("can_send_other_messages").get_to(value.can_send_other_messages);
        }
        if (j.contains("can_add_web_page_previews")) {
            j.at("can_add_web_page_previews").get_to(value.can_add_web_page_previews);
        }
        if (j.contains("can_edit_tag")) {
            j.at("can_edit_tag").get_to(value.can_edit_tag);
        }
        if (j.contains("can_change_info")) {
            j.at("can_change_info").get_to(value.can_change_info);
        }
        if (j.contains("can_invite_users")) {
            j.at("can_invite_users").get_to(value.can_invite_users);
        }
        if (j.contains("can_pin_messages")) {
            j.at("can_pin_messages").get_to(value.can_pin_messages);
        }
        if (j.contains("can_manage_topics")) {
            j.at("can_manage_topics").get_to(value.can_manage_topics);
        }
    }
}
