// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChatOwnerChanged.hpp"
#include "types/User.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChatOwnerChanged& value) {
        j = json{};
        j["new_owner"] = value.new_owner;
    }

    void from_json(const json& j, ChatOwnerChanged& value) {
        if (j.contains("new_owner")) {
            j.at("new_owner").get_to(value.new_owner);
        }
    }
}
