// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Contact.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Contact& value) {
        j = json{};
        j["phone_number"] = value.phone_number;
        j["first_name"] = value.first_name;
    if (!value.last_name.empty()) { 
                    j["last_name"] = value.last_name; 
            }
    if (value.user_id != 0) { 
                    j["user_id"] = value.user_id; 
            }
    if (!value.vcard.empty()) { 
                    j["vcard"] = value.vcard; 
            }
    }

    void from_json(const json& j, Contact& value) {
        if (j.contains("phone_number")) {
            j.at("phone_number").get_to(value.phone_number);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("vcard")) {
            j.at("vcard").get_to(value.vcard);
        }
    }
}
