// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/File.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const File& value) {
        j = json{};
        j["file_id"] = value.file_id;
        j["file_unique_id"] = value.file_unique_id;
    if (value.file_size != 0) { 
                    j["file_size"] = value.file_size; 
            }
    if (!value.file_path.empty()) { 
                    j["file_path"] = value.file_path; 
            }
    }

    void from_json(const json& j, File& value) {
        if (j.contains("file_id")) {
            j.at("file_id").get_to(value.file_id);
        }
        if (j.contains("file_unique_id")) {
            j.at("file_unique_id").get_to(value.file_unique_id);
        }
        if (j.contains("file_size")) {
            j.at("file_size").get_to(value.file_size);
        }
        if (j.contains("file_path")) {
            j.at("file_path").get_to(value.file_path);
        }
    }
}
