// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Game.hpp"
#include "types/Animation.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Game& value) {
        j = json{};
        j["title"] = value.title;
        j["description"] = value.description;
        j["photo"] = value.photo;
    if (!value.text.empty()) { 
                    j["text"] = value.text; 
            }
    if (!value.text_entities.empty()) { 
                    j["text_entities"] = value.text_entities; 
            }
    if (value.animation) { 
                    j["animation"] = value.animation; 
            }
    }

    void from_json(const json& j, Game& value) {
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("text_entities")) {
            j.at("text_entities").get_to(value.text_entities);
        }
        if (j.contains("animation")) {
            j.at("animation").get_to(value.animation);
        }
    }
}
