// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQuery.hpp"
#include "types/User.hpp"
#include "types/Location.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InlineQuery& value) {
        j = json{};
        j["id"] = value.id;
        j["from"] = value.from;
        j["query"] = value.query;
        j["offset"] = value.offset;
    if (!value.chat_type.empty()) { 
                    j["chat_type"] = value.chat_type; 
            }
    if (value.location) { 
                    j["location"] = value.location; 
            }
    }

    void from_json(const json& j, InlineQuery& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("query")) {
            j.at("query").get_to(value.query);
        }
        if (j.contains("offset")) {
            j.at("offset").get_to(value.offset);
        }
        if (j.contains("chat_type")) {
            j.at("chat_type").get_to(value.chat_type);
        }
        if (j.contains("location")) {
            j.at("location").get_to(value.location);
        }
    }
}
