// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultMpeg4Gif.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InlineQueryResultMpeg4Gif& value) {
        j = json{};
        j["type"] = value.type_;
        j["id"] = value.id;
        j["mpeg4_url"] = value.mpeg4_url;
        j["thumbnail_url"] = value.thumbnail_url;
    if (value.mpeg4_width != 0) { 
                    j["mpeg4_width"] = value.mpeg4_width; 
            }
    if (value.mpeg4_height != 0) { 
                    j["mpeg4_height"] = value.mpeg4_height; 
            }
    if (value.mpeg4_duration != 0) { 
                    j["mpeg4_duration"] = value.mpeg4_duration; 
            }
    if (!value.thumbnail_mime_type.empty()) { 
                    j["thumbnail_mime_type"] = value.thumbnail_mime_type; 
            }
    if (!value.title.empty()) { 
                    j["title"] = value.title; 
            }
    if (!value.caption.empty()) { 
                    j["caption"] = value.caption; 
            }
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.caption_entities.empty()) { 
                    j["caption_entities"] = value.caption_entities; 
            }
    if (value.show_caption_above_media) { 
                    j["show_caption_above_media"] = value.show_caption_above_media; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    if (value.input_message_content) { 
                    j["input_message_content"] = value.input_message_content; 
            }
    }

    void from_json(const json& j, InlineQueryResultMpeg4Gif& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("mpeg4_url")) {
            j.at("mpeg4_url").get_to(value.mpeg4_url);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("mpeg4_width")) {
            j.at("mpeg4_width").get_to(value.mpeg4_width);
        }
        if (j.contains("mpeg4_height")) {
            j.at("mpeg4_height").get_to(value.mpeg4_height);
        }
        if (j.contains("mpeg4_duration")) {
            j.at("mpeg4_duration").get_to(value.mpeg4_duration);
        }
        if (j.contains("thumbnail_mime_type")) {
            j.at("thumbnail_mime_type").get_to(value.thumbnail_mime_type);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
    }
}
