// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultVideo.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InlineQueryResultVideo& value) {
        j = json{};
        j["type"] = value.type_;
        j["id"] = value.id;
        j["video_url"] = value.video_url;
        j["mime_type"] = value.mime_type;
        j["thumbnail_url"] = value.thumbnail_url;
        j["title"] = value.title;
    if (!value.caption.empty()) { 
                    j["caption"] = value.caption; 
            }
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.caption_entities.empty()) { 
                    j["caption_entities"] = value.caption_entities; 
            }
    if (value.show_caption_above_media) { 
                    j["show_caption_above_media"] = value.show_caption_above_media; 
            }
    if (value.video_width != 0) { 
                    j["video_width"] = value.video_width; 
            }
    if (value.video_height != 0) { 
                    j["video_height"] = value.video_height; 
            }
    if (value.video_duration != 0) { 
                    j["video_duration"] = value.video_duration; 
            }
    if (!value.description.empty()) { 
                    j["description"] = value.description; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    if (value.input_message_content) { 
                    j["input_message_content"] = value.input_message_content; 
            }
    }

    void from_json(const json& j, InlineQueryResultVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("video_url")) {
            j.at("video_url").get_to(value.video_url);
        }
        if (j.contains("mime_type")) {
            j.at("mime_type").get_to(value.mime_type);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("video_width")) {
            j.at("video_width").get_to(value.video_width);
        }
        if (j.contains("video_height")) {
            j.at("video_height").get_to(value.video_height);
        }
        if (j.contains("video_duration")) {
            j.at("video_duration").get_to(value.video_duration);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
    }
}
