// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputStoryContentPhoto.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputStoryContentPhoto& value) {
        j = json{};
        j["type"] = value.type_;
        j["photo"] = value.photo;
    }

    void from_json(const json& j, InputStoryContentPhoto& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
    }
}
