// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputVenueMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputVenueMessageContent& value) {
        j = json{};
        j["latitude"] = value.latitude;
        j["longitude"] = value.longitude;
        j["title"] = value.title;
        j["address"] = value.address;
    if (!value.foursquare_id.empty()) { 
                    j["foursquare_id"] = value.foursquare_id; 
            }
    if (!value.foursquare_type.empty()) { 
                    j["foursquare_type"] = value.foursquare_type; 
            }
    if (!value.google_place_id.empty()) { 
                    j["google_place_id"] = value.google_place_id; 
            }
    if (!value.google_place_type.empty()) { 
                    j["google_place_type"] = value.google_place_type; 
            }
    }

    void from_json(const json& j, InputVenueMessageContent& value) {
        if (j.contains("latitude")) {
            j.at("latitude").get_to(value.latitude);
        }
        if (j.contains("longitude")) {
            j.at("longitude").get_to(value.longitude);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("address")) {
            j.at("address").get_to(value.address);
        }
        if (j.contains("foursquare_id")) {
            j.at("foursquare_id").get_to(value.foursquare_id);
        }
        if (j.contains("foursquare_type")) {
            j.at("foursquare_type").get_to(value.foursquare_type);
        }
        if (j.contains("google_place_id")) {
            j.at("google_place_id").get_to(value.google_place_id);
        }
        if (j.contains("google_place_type")) {
            j.at("google_place_type").get_to(value.google_place_type);
        }
    }
}
