// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputMediaVideo.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputMediaVideo& value) {
        j = json{};
        j["type"] = value.type_;
        j["media"] = value.media;
    if (!value.thumbnail.empty()) { 
                    j["thumbnail"] = value.thumbnail; 
            }
    if (!value.cover.empty()) { 
                    j["cover"] = value.cover; 
            }
    if (value.start_timestamp != 0) { 
                    j["start_timestamp"] = value.start_timestamp; 
            }
    if (!value.caption.empty()) { 
                    j["caption"] = value.caption; 
            }
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.caption_entities.empty()) { 
                    j["caption_entities"] = value.caption_entities; 
            }
    if (value.show_caption_above_media) { 
                    j["show_caption_above_media"] = value.show_caption_above_media; 
            }
    if (value.width != 0) { 
                    j["width"] = value.width; 
            }
    if (value.height != 0) { 
                    j["height"] = value.height; 
            }
    if (value.duration != 0) { 
                    j["duration"] = value.duration; 
            }
    if (value.supports_streaming) { 
                    j["supports_streaming"] = value.supports_streaming; 
            }
    if (value.has_spoiler) { 
                    j["has_spoiler"] = value.has_spoiler; 
            }
    }

    void from_json(const json& j, InputMediaVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("cover")) {
            j.at("cover").get_to(value.cover);
        }
        if (j.contains("start_timestamp")) {
            j.at("start_timestamp").get_to(value.start_timestamp);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("show_caption_above_media")) {
            j.at("show_caption_above_media").get_to(value.show_caption_above_media);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("supports_streaming")) {
            j.at("supports_streaming").get_to(value.supports_streaming);
        }
        if (j.contains("has_spoiler")) {
            j.at("has_spoiler").get_to(value.has_spoiler);
        }
    }
}
