// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputPollOption.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputPollOption& value) {
        j = json{};
        j["text"] = value.text;
    if (!value.text_parse_mode.empty()) { 
                    j["text_parse_mode"] = value.text_parse_mode; 
            }
    if (!value.text_entities.empty()) { 
                    j["text_entities"] = value.text_entities; 
            }
    }

    void from_json(const json& j, InputPollOption& value) {
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("text_parse_mode")) {
            j.at("text_parse_mode").get_to(value.text_parse_mode);
        }
        if (j.contains("text_entities")) {
            j.at("text_entities").get_to(value.text_entities);
        }
    }
}
