// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputPaidMediaVideo.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputPaidMediaVideo& value) {
        j = json{};
        j["type"] = value.type_;
        j["media"] = value.media;
    if (!value.thumbnail.empty()) { 
                    j["thumbnail"] = value.thumbnail; 
            }
    if (!value.cover.empty()) { 
                    j["cover"] = value.cover; 
            }
    if (value.start_timestamp != 0) { 
                    j["start_timestamp"] = value.start_timestamp; 
            }
    if (value.width != 0) { 
                    j["width"] = value.width; 
            }
    if (value.height != 0) { 
                    j["height"] = value.height; 
            }
    if (value.duration != 0) { 
                    j["duration"] = value.duration; 
            }
    if (value.supports_streaming) { 
                    j["supports_streaming"] = value.supports_streaming; 
            }
    }

    void from_json(const json& j, InputPaidMediaVideo& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
        if (j.contains("cover")) {
            j.at("cover").get_to(value.cover);
        }
        if (j.contains("start_timestamp")) {
            j.at("start_timestamp").get_to(value.start_timestamp);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("supports_streaming")) {
            j.at("supports_streaming").get_to(value.supports_streaming);
        }
    }
}
