// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/KeyboardButtonPollType.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const KeyboardButtonPollType& value) {
        j = json{};
    if (!value.type_.empty()) { 
                    j["type"] = value.type_; 
            }
    }

    void from_json(const json& j, KeyboardButtonPollType& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
    }
}
