// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/KeyboardButton.hpp"
#include "types/KeyboardButtonRequestUsers.hpp"
#include "types/KeyboardButtonRequestChat.hpp"
#include "types/KeyboardButtonPollType.hpp"
#include "types/WebAppInfo.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const KeyboardButton& value) {
        j = json{};
        j["text"] = value.text;
    if (!value.icon_custom_emoji_id.empty()) { 
                    j["icon_custom_emoji_id"] = value.icon_custom_emoji_id; 
            }
    if (!value.style.empty()) { 
                    j["style"] = value.style; 
            }
    if (value.request_users) { 
                    j["request_users"] = value.request_users; 
            }
    if (value.request_chat) { 
                    j["request_chat"] = value.request_chat; 
            }
    if (value.request_contact) { 
                    j["request_contact"] = value.request_contact; 
            }
    if (value.request_location) { 
                    j["request_location"] = value.request_location; 
            }
    if (value.request_poll) { 
                    j["request_poll"] = value.request_poll; 
            }
    if (value.web_app) { 
                    j["web_app"] = value.web_app; 
            }
    }

    void from_json(const json& j, KeyboardButton& value) {
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("icon_custom_emoji_id")) {
            j.at("icon_custom_emoji_id").get_to(value.icon_custom_emoji_id);
        }
        if (j.contains("style")) {
            j.at("style").get_to(value.style);
        }
        if (j.contains("request_users")) {
            j.at("request_users").get_to(value.request_users);
        }
        if (j.contains("request_chat")) {
            j.at("request_chat").get_to(value.request_chat);
        }
        if (j.contains("request_contact")) {
            j.at("request_contact").get_to(value.request_contact);
        }
        if (j.contains("request_location")) {
            j.at("request_location").get_to(value.request_location);
        }
        if (j.contains("request_poll")) {
            j.at("request_poll").get_to(value.request_poll);
        }
        if (j.contains("web_app")) {
            j.at("web_app").get_to(value.web_app);
        }
    }
}
