// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MaskPosition.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const MaskPosition& value) {
        j = json{};
        j["point"] = value.point;
        j["x_shift"] = value.x_shift;
        j["y_shift"] = value.y_shift;
        j["scale"] = value.scale;
    }

    void from_json(const json& j, MaskPosition& value) {
        if (j.contains("point")) {
            j.at("point").get_to(value.point);
        }
        if (j.contains("x_shift")) {
            j.at("x_shift").get_to(value.x_shift);
        }
        if (j.contains("y_shift")) {
            j.at("y_shift").get_to(value.y_shift);
        }
        if (j.contains("scale")) {
            j.at("scale").get_to(value.scale);
        }
    }
}
