// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MessageAutoDeleteTimerChanged.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const MessageAutoDeleteTimerChanged& value) {
        j = json{};
        j["message_auto_delete_time"] = value.message_auto_delete_time;
    }

    void from_json(const json& j, MessageAutoDeleteTimerChanged& value) {
        if (j.contains("message_auto_delete_time")) {
            j.at("message_auto_delete_time").get_to(value.message_auto_delete_time);
        }
    }
}
