// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MessageId.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const MessageId& value) {
        j = json{};
        j["message_id"] = value.message_id;
    }

    void from_json(const json& j, MessageId& value) {
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
    }
}
