// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MessageOriginChannel.hpp"
#include "types/Chat.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const MessageOriginChannel& value) {
        j = json{};
        j["type"] = value.type_;
        j["date"] = value.date;
        j["chat"] = value.chat;
        j["message_id"] = value.message_id;
    if (!value.author_signature.empty()) { 
                    j["author_signature"] = value.author_signature; 
            }
    }

    void from_json(const json& j, MessageOriginChannel& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("chat")) {
            j.at("chat").get_to(value.chat);
        }
        if (j.contains("message_id")) {
            j.at("message_id").get_to(value.message_id);
        }
        if (j.contains("author_signature")) {
            j.at("author_signature").get_to(value.author_signature);
        }
    }
}
