// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PaidMessagePriceChanged.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PaidMessagePriceChanged& value) {
        j = json{};
        j["paid_message_star_count"] = value.paid_message_star_count;
    }

    void from_json(const json& j, PaidMessagePriceChanged& value) {
        if (j.contains("paid_message_star_count")) {
            j.at("paid_message_star_count").get_to(value.paid_message_star_count);
        }
    }
}
