// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PassportElementErrorFiles.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PassportElementErrorFiles& value) {
        j = json{};
        j["source"] = value.source;
        j["type"] = value.type_;
        j["file_hashes"] = value.file_hashes;
        j["message"] = value.message;
    }

    void from_json(const json& j, PassportElementErrorFiles& value) {
        if (j.contains("source")) {
            j.at("source").get_to(value.source);
        }
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("file_hashes")) {
            j.at("file_hashes").get_to(value.file_hashes);
        }
        if (j.contains("message")) {
            j.at("message").get_to(value.message);
        }
    }
}
