// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PollOption.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PollOption& value) {
        j = json{};
        j["text"] = value.text;
        j["voter_count"] = value.voter_count;
    if (!value.text_entities.empty()) { 
                    j["text_entities"] = value.text_entities; 
            }
    }

    void from_json(const json& j, PollOption& value) {
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("voter_count")) {
            j.at("voter_count").get_to(value.voter_count);
        }
        if (j.contains("text_entities")) {
            j.at("text_entities").get_to(value.text_entities);
        }
    }
}
