// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ReplyKeyboardRemove.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ReplyKeyboardRemove& value) {
        j = json{};
        j["remove_keyboard"] = value.remove_keyboard;
    if (value.selective) { 
                    j["selective"] = value.selective; 
            }
    }

    void from_json(const json& j, ReplyKeyboardRemove& value) {
        if (j.contains("remove_keyboard")) {
            j.at("remove_keyboard").get_to(value.remove_keyboard);
        }
        if (j.contains("selective")) {
            j.at("selective").get_to(value.selective);
        }
    }
}
