// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/RevenueWithdrawalStateSucceeded.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const RevenueWithdrawalStateSucceeded& value) {
        j = json{};
        j["type"] = value.type_;
        j["date"] = value.date;
        j["url"] = value.url;
    }

    void from_json(const json& j, RevenueWithdrawalStateSucceeded& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("url")) {
            j.at("url").get_to(value.url);
        }
    }
}
