// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ShippingAddress.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ShippingAddress& value) {
        j = json{};
        j["country_code"] = value.country_code;
        j["state"] = value.state;
        j["city"] = value.city;
        j["street_line1"] = value.street_line1;
        j["street_line2"] = value.street_line2;
        j["post_code"] = value.post_code;
    }

    void from_json(const json& j, ShippingAddress& value) {
        if (j.contains("country_code")) {
            j.at("country_code").get_to(value.country_code);
        }
        if (j.contains("state")) {
            j.at("state").get_to(value.state);
        }
        if (j.contains("city")) {
            j.at("city").get_to(value.city);
        }
        if (j.contains("street_line1")) {
            j.at("street_line1").get_to(value.street_line1);
        }
        if (j.contains("street_line2")) {
            j.at("street_line2").get_to(value.street_line2);
        }
        if (j.contains("post_code")) {
            j.at("post_code").get_to(value.post_code);
        }
    }
}
