// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Story.hpp"
#include "types/Chat.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Story& value) {
        j = json{};
        j["chat"] = value.chat;
        j["id"] = value.id;
    }

    void from_json(const json& j, Story& value) {
        if (j.contains("chat")) {
            j.at("chat").get_to(value.chat);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
    }
}
