// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/StoryAreaPosition.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const StoryAreaPosition& value) {
        j = json{};
        j["x_percentage"] = value.x_percentage;
        j["y_percentage"] = value.y_percentage;
        j["width_percentage"] = value.width_percentage;
        j["height_percentage"] = value.height_percentage;
        j["rotation_angle"] = value.rotation_angle;
        j["corner_radius_percentage"] = value.corner_radius_percentage;
    }

    void from_json(const json& j, StoryAreaPosition& value) {
        if (j.contains("x_percentage")) {
            j.at("x_percentage").get_to(value.x_percentage);
        }
        if (j.contains("y_percentage")) {
            j.at("y_percentage").get_to(value.y_percentage);
        }
        if (j.contains("width_percentage")) {
            j.at("width_percentage").get_to(value.width_percentage);
        }
        if (j.contains("height_percentage")) {
            j.at("height_percentage").get_to(value.height_percentage);
        }
        if (j.contains("rotation_angle")) {
            j.at("rotation_angle").get_to(value.rotation_angle);
        }
        if (j.contains("corner_radius_percentage")) {
            j.at("corner_radius_percentage").get_to(value.corner_radius_percentage);
        }
    }
}
