// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/StoryAreaTypeSuggestedReaction.hpp"
#include "types/ReactionType.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const StoryAreaTypeSuggestedReaction& value) {
        j = json{};
        j["type"] = value.type_;
        j["reaction_type"] = value.reaction_type;
    if (value.is_dark) { 
                    j["is_dark"] = value.is_dark; 
            }
    if (value.is_flipped) { 
                    j["is_flipped"] = value.is_flipped; 
            }
    }

    void from_json(const json& j, StoryAreaTypeSuggestedReaction& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("reaction_type")) {
            j.at("reaction_type").get_to(value.reaction_type);
        }
        if (j.contains("is_dark")) {
            j.at("is_dark").get_to(value.is_dark);
        }
        if (j.contains("is_flipped")) {
            j.at("is_flipped").get_to(value.is_flipped);
        }
    }
}
