// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/SuggestedPostRefunded.hpp"
#include "types/Message.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const SuggestedPostRefunded& value) {
        j = json{};
        j["reason"] = value.reason;
    if (value.suggested_post_message) { 
                    j["suggested_post_message"] = value.suggested_post_message; 
            }
    }

    void from_json(const json& j, SuggestedPostRefunded& value) {
        if (j.contains("reason")) {
            j.at("reason").get_to(value.reason);
        }
        if (j.contains("suggested_post_message")) {
            j.at("suggested_post_message").get_to(value.suggested_post_message);
        }
    }
}
