// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/UniqueGiftInfo.hpp"
#include "types/UniqueGift.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const UniqueGiftInfo& value) {
        j = json{};
        j["gift"] = value.gift;
        j["origin"] = value.origin;
    if (!value.last_resale_currency.empty()) { 
                    j["last_resale_currency"] = value.last_resale_currency; 
            }
    if (value.last_resale_amount != 0) { 
                    j["last_resale_amount"] = value.last_resale_amount; 
            }
    if (!value.owned_gift_id.empty()) { 
                    j["owned_gift_id"] = value.owned_gift_id; 
            }
    if (value.transfer_star_count != 0) { 
                    j["transfer_star_count"] = value.transfer_star_count; 
            }
    if (value.next_transfer_date != 0) { 
                    j["next_transfer_date"] = value.next_transfer_date; 
            }
    }

    void from_json(const json& j, UniqueGiftInfo& value) {
        if (j.contains("gift")) {
            j.at("gift").get_to(value.gift);
        }
        if (j.contains("origin")) {
            j.at("origin").get_to(value.origin);
        }
        if (j.contains("last_resale_currency")) {
            j.at("last_resale_currency").get_to(value.last_resale_currency);
        }
        if (j.contains("last_resale_amount")) {
            j.at("last_resale_amount").get_to(value.last_resale_amount);
        }
        if (j.contains("owned_gift_id")) {
            j.at("owned_gift_id").get_to(value.owned_gift_id);
        }
        if (j.contains("transfer_star_count")) {
            j.at("transfer_star_count").get_to(value.transfer_star_count);
        }
        if (j.contains("next_transfer_date")) {
            j.at("next_transfer_date").get_to(value.next_transfer_date);
        }
    }
}
