// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/UserChatBoosts.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const UserChatBoosts& value) {
        j = json{};
        j["boosts"] = value.boosts;
    }

    void from_json(const json& j, UserChatBoosts& value) {
        if (j.contains("boosts")) {
            j.at("boosts").get_to(value.boosts);
        }
    }
}
