// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/User.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const User& value) {
        j = json{};
        j["id"] = value.id;
        j["is_bot"] = value.is_bot;
        j["first_name"] = value.first_name;
    if (!value.last_name.empty()) { 
                    j["last_name"] = value.last_name; 
            }
    if (!value.username.empty()) { 
                    j["username"] = value.username; 
            }
    if (!value.language_code.empty()) { 
                    j["language_code"] = value.language_code; 
            }
    if (value.is_premium) { 
                    j["is_premium"] = value.is_premium; 
            }
    if (value.added_to_attachment_menu) { 
                    j["added_to_attachment_menu"] = value.added_to_attachment_menu; 
            }
    if (value.can_join_groups) { 
                    j["can_join_groups"] = value.can_join_groups; 
            }
    if (value.can_read_all_group_messages) { 
                    j["can_read_all_group_messages"] = value.can_read_all_group_messages; 
            }
    if (value.supports_inline_queries) { 
                    j["supports_inline_queries"] = value.supports_inline_queries; 
            }
    if (value.can_connect_to_business) { 
                    j["can_connect_to_business"] = value.can_connect_to_business; 
            }
    if (value.has_main_web_app) { 
                    j["has_main_web_app"] = value.has_main_web_app; 
            }
    if (value.has_topics_enabled) { 
                    j["has_topics_enabled"] = value.has_topics_enabled; 
            }
    if (value.allows_users_to_create_topics) { 
                    j["allows_users_to_create_topics"] = value.allows_users_to_create_topics; 
            }
    }

    void from_json(const json& j, User& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("is_bot")) {
            j.at("is_bot").get_to(value.is_bot);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("username")) {
            j.at("username").get_to(value.username);
        }
        if (j.contains("language_code")) {
            j.at("language_code").get_to(value.language_code);
        }
        if (j.contains("is_premium")) {
            j.at("is_premium").get_to(value.is_premium);
        }
        if (j.contains("added_to_attachment_menu")) {
            j.at("added_to_attachment_menu").get_to(value.added_to_attachment_menu);
        }
        if (j.contains("can_join_groups")) {
            j.at("can_join_groups").get_to(value.can_join_groups);
        }
        if (j.contains("can_read_all_group_messages")) {
            j.at("can_read_all_group_messages").get_to(value.can_read_all_group_messages);
        }
        if (j.contains("supports_inline_queries")) {
            j.at("supports_inline_queries").get_to(value.supports_inline_queries);
        }
        if (j.contains("can_connect_to_business")) {
            j.at("can_connect_to_business").get_to(value.can_connect_to_business);
        }
        if (j.contains("has_main_web_app")) {
            j.at("has_main_web_app").get_to(value.has_main_web_app);
        }
        if (j.contains("has_topics_enabled")) {
            j.at("has_topics_enabled").get_to(value.has_topics_enabled);
        }
        if (j.contains("allows_users_to_create_topics")) {
            j.at("allows_users_to_create_topics").get_to(value.allows_users_to_create_topics);
        }
    }
}
