// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/PhotoSize.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents an animation file (GIF or H.264/MPEG-4 AVC video without sound).
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param width Video width as defined by the sender
     * @param height Video height as defined by the sender
     * @param duration Duration of the video in seconds as defined by the sender
     * @param thumbnail Optional. Animation thumbnail as defined by the sender
     * @param file_name Optional. Original animation filename as defined by the sender
     * @param mime_type Optional. MIME type of the file as defined by the sender
     * @param file_size Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
     */
    struct Animation : public TelegramModel {
        typedef std::shared_ptr<Animation> Ptr;
        typedef std::weak_ptr<Animation> WeakPtr;

        virtual ~Animation() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id;

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id;

        // Video width as defined by the sender
        int64_t width = 0;

        // Video height as defined by the sender
        int64_t height = 0;

        // Duration of the video in seconds as defined by the sender
        int64_t duration = 0;

        // Optional. Animation thumbnail as defined by the sender
        PhotoSize::Ptr thumbnail;

        // Optional. Original animation filename as defined by the sender
        std::string file_name;

        // Optional. MIME type of the file as defined by the sender
        std::string mime_type;

        // Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
        int64_t file_size = 0;
    };
    void to_json(json& j, const Animation& value);
    void from_json(const json& j, Animation& value);
}
