// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/BotCommandScope.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents the scope of bot commands, covering a specific member of a group or supergroup chat.
     *
     * @param type Scope type, must be chat_member
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername). Channel direct messages chats and channel chats aren't supported.
     * @param user_id Unique identifier of the target user
     */
    struct BotCommandScopeChatMember : public BotCommandScope {
        typedef std::shared_ptr<BotCommandScopeChatMember> Ptr;
        typedef std::weak_ptr<BotCommandScopeChatMember> WeakPtr;

        virtual ~BotCommandScopeChatMember() = default;
        // Scope type, must be chat_member
        std::string type_;

        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername). Channel direct messages chats and channel chats aren't supported.
        int64_t chat_id = 0;

        // Unique identifier of the target user
        int64_t user_id = 0;
    };
    void to_json(json& j, const BotCommandScopeChatMember& value);
    void from_json(const json& j, BotCommandScopeChatMember& value);
}
