// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/User.hpp"
#include "types/BusinessBotRights.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes the connection of the bot with a business account.
     *
     * @param id Unique identifier of the business connection
     * @param user Business account user that created the business connection
     * @param user_chat_id Identifier of a private chat with the user who created the business connection. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
     * @param date Date the connection was established in Unix time
     * @param is_enabled True, if the connection is active
     * @param rights Optional. Rights of the business bot
     */
    struct BusinessConnection : public TelegramModel {
        typedef std::shared_ptr<BusinessConnection> Ptr;
        typedef std::weak_ptr<BusinessConnection> WeakPtr;

        virtual ~BusinessConnection() = default;
        // Unique identifier of the business connection
        std::string id;

        // Business account user that created the business connection
        User::Ptr user;

        // Identifier of a private chat with the user who created the business connection. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
        int64_t user_chat_id = 0;

        // Date the connection was established in Unix time
        int64_t date = 0;

        // True, if the connection is active
        bool is_enabled = false;

        // Optional. Rights of the business bot
        BusinessBotRights::Ptr rights;
    };
    void to_json(json& j, const BusinessConnection& value);
    void from_json(const json& j, BusinessConnection& value);
}
