// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/User.hpp"
#include "types/MaybeInaccessibleMessage.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents an incoming callback query from a callback button in an inline keyboard. If the button that originated the query was attached to a message sent by the bot, the field message will be present. If the button was attached to a message sent via the bot (in inline mode), the field inline_message_id will be present. Exactly one of the fields data or game_short_name will be present.
     *  NOTE: After the user presses a callback button, Telegram clients will display a progress bar until you call answerCallbackQuery. It is, therefore, necessary to react by calling answerCallbackQuery even if no notification to the user is needed (e.g., without specifying any of the optional parameters).
     *
     * @param id Unique identifier for this query
     * @param from Sender
     * @param chat_instance Global identifier, uniquely corresponding to the chat to which the message with the callback button was sent. Useful for high scores in games.
     * @param message Optional. Message sent by the bot with the callback button that originated the query
     * @param inline_message_id Optional. Identifier of the message sent via the bot in inline mode, that originated the query.
     * @param data Optional. Data associated with the callback button. Be aware that the message originated the query can contain no callback buttons with this data.
     * @param game_short_name Optional. Short name of a Game to be returned, serves as the unique identifier for the game
     */
    struct CallbackQuery : public TelegramModel {
        typedef std::shared_ptr<CallbackQuery> Ptr;
        typedef std::weak_ptr<CallbackQuery> WeakPtr;

        virtual ~CallbackQuery() = default;
        // Unique identifier for this query
        std::string id;

        // Sender
        User::Ptr from;

        // Global identifier, uniquely corresponding to the chat to which the message with the callback button was sent. Useful for high scores in games.
        std::string chat_instance;

        // Optional. Message sent by the bot with the callback button that originated the query
        MaybeInaccessibleMessage::Ptr message;

        // Optional. Identifier of the message sent via the bot in inline mode, that originated the query.
        std::string inline_message_id;

        // Optional. Data associated with the callback button. Be aware that the message originated the query can contain no callback buttons with this data.
        std::string data;

        // Optional. Short name of a Game to be returned, serves as the unique identifier for the game
        std::string game_short_name;
    };
    void to_json(json& j, const CallbackQuery& value);
    void from_json(const json& j, CallbackQuery& value);
}
