// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about a user boosting a chat.
     *
     * @param boost_count Number of boosts added by the user
     */
    struct ChatBoostAdded : public TelegramModel {
        typedef std::shared_ptr<ChatBoostAdded> Ptr;
        typedef std::weak_ptr<ChatBoostAdded> WeakPtr;

        virtual ~ChatBoostAdded() = default;
        // Number of boosts added by the user
        int64_t boost_count = 0;
    };
    void to_json(json& j, const ChatBoostAdded& value);
    void from_json(const json& j, ChatBoostAdded& value);
}
