// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ChatBoostSource.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The boost was obtained by the creation of a Telegram Premium or a Telegram Star giveaway. This boosts the chat 4 times for the duration of the corresponding Telegram Premium subscription for Telegram Premium giveaways and prize_star_count / 500 times for one year for Telegram Star giveaways.
     *
     * @param source Source of the boost, always “giveaway”
     * @param giveaway_message_id Identifier of a message in the chat with the giveaway; the message could have been deleted already. May be 0 if the message isn't sent yet.
     * @param user Optional. User that won the prize in the giveaway if any; for Telegram Premium giveaways only
     * @param prize_star_count Optional. The number of Telegram Stars to be split between giveaway winners; for Telegram Star giveaways only
     * @param is_unclaimed Optional. True, if the giveaway was completed, but there was no user to win the prize
     */
    struct ChatBoostSourceGiveaway : public ChatBoostSource {
        typedef std::shared_ptr<ChatBoostSourceGiveaway> Ptr;
        typedef std::weak_ptr<ChatBoostSourceGiveaway> WeakPtr;

        virtual ~ChatBoostSourceGiveaway() = default;
        // Source of the boost, always “giveaway”
        std::string source;

        // Identifier of a message in the chat with the giveaway; the message could have been deleted already. May be 0 if the message isn't sent yet.
        int64_t giveaway_message_id = 0;

        // Optional. User that won the prize in the giveaway if any; for Telegram Premium giveaways only
        User::Ptr user;

        // Optional. The number of Telegram Stars to be split between giveaway winners; for Telegram Star giveaways only
        int64_t prize_star_count = 0;

        // Optional. True, if the giveaway was completed, but there was no user to win the prize
        bool is_unclaimed = false;
    };
    void to_json(json& j, const ChatBoostSourceGiveaway& value);
    void from_json(const json& j, ChatBoostSourceGiveaway& value);
}
