// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ChatMember.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a chat member that was banned in the chat and can't return to the chat or view chat messages.
     *
     * @param status The member's status in the chat, always “kicked”
     * @param user Information about the user
     * @param until_date Date when restrictions will be lifted for this user; Unix time. If 0, then the user is banned forever
     */
    struct ChatMemberBanned : public ChatMember {
        typedef std::shared_ptr<ChatMemberBanned> Ptr;
        typedef std::weak_ptr<ChatMemberBanned> WeakPtr;

        virtual ~ChatMemberBanned() = default;
        // The member's status in the chat, always “kicked”
        std::string status;

        // Information about the user
        User::Ptr user;

        // Date when restrictions will be lifted for this user; Unix time. If 0, then the user is banned forever
        int64_t until_date = 0;
    };
    void to_json(json& j, const ChatMemberBanned& value);
    void from_json(const json& j, ChatMemberBanned& value);
}
