// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Message.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about the completion of a giveaway without public winners.
     *
     * @param winner_count Number of winners in the giveaway
     * @param unclaimed_prize_count Optional. Number of undistributed prizes
     * @param giveaway_message Optional. Message with the giveaway that was completed, if it wasn't deleted
     * @param is_star_giveaway Optional. True, if the giveaway is a Telegram Star giveaway. Otherwise, currently, the giveaway is a Telegram Premium giveaway.
     */
    struct GiveawayCompleted : public TelegramModel {
        typedef std::shared_ptr<GiveawayCompleted> Ptr;
        typedef std::weak_ptr<GiveawayCompleted> WeakPtr;

        virtual ~GiveawayCompleted() = default;
        // Number of winners in the giveaway
        int64_t winner_count = 0;

        // Optional. Number of undistributed prizes
        int64_t unclaimed_prize_count = 0;

        // Optional. Message with the giveaway that was completed, if it wasn't deleted
        Message::Ptr giveaway_message;

        // Optional. True, if the giveaway is a Telegram Star giveaway. Otherwise, currently, the giveaway is a Telegram Premium giveaway.
        bool is_star_giveaway = false;
    };
    void to_json(json& j, const GiveawayCompleted& value);
    void from_json(const json& j, GiveawayCompleted& value);
}
