// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/MessageEntity.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a task to add to a checklist.
     *
     * @param id Unique identifier of the task; must be positive and unique among all task identifiers currently present in the checklist
     * @param text Text of the task; 1-100 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the text. See formatting options for more details.
     * @param text_entities Optional. List of special entities that appear in the text, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
     */
    struct InputChecklistTask : public TelegramModel {
        typedef std::shared_ptr<InputChecklistTask> Ptr;
        typedef std::weak_ptr<InputChecklistTask> WeakPtr;

        virtual ~InputChecklistTask() = default;
        // Unique identifier of the task; must be positive and unique among all task identifiers currently present in the checklist
        int64_t id = 0;

        // Text of the task; 1-100 characters after entities parsing
        std::string text;

        // Optional. Mode for parsing entities in the text. See formatting options for more details.
        std::string parse_mode;

        // Optional. List of special entities that appear in the text, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
        std::vector<MessageEntity::Ptr> text_entities;
    };
    void to_json(json& j, const InputChecklistTask& value);
    void from_json(const json& j, InputChecklistTask& value);
}
