// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/InputChecklistTask.hpp"
#include "types/MessageEntity.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a checklist to create.
     *
     * @param title Title of the checklist; 1-255 characters after entities parsing
     * @param tasks List of 1-30 tasks in the checklist
     * @param parse_mode Optional. Mode for parsing entities in the title. See formatting options for more details.
     * @param title_entities Optional. List of special entities that appear in the title, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
     * @param others_can_add_tasks Optional. Pass True if other users can add tasks to the checklist
     * @param others_can_mark_tasks_as_done Optional. Pass True if other users can mark tasks as done or not done in the checklist
     */
    struct InputChecklist : public TelegramModel {
        typedef std::shared_ptr<InputChecklist> Ptr;
        typedef std::weak_ptr<InputChecklist> WeakPtr;

        virtual ~InputChecklist() = default;
        // Title of the checklist; 1-255 characters after entities parsing
        std::string title;

        // List of 1-30 tasks in the checklist
        std::vector<InputChecklistTask::Ptr> tasks;

        // Optional. Mode for parsing entities in the title. See formatting options for more details.
        std::string parse_mode;

        // Optional. List of special entities that appear in the title, which can be specified instead of parse_mode. Currently, only bold, italic, underline, strikethrough, spoiler, and custom_emoji entities are allowed.
        std::vector<MessageEntity::Ptr> title_entities;

        // Optional. Pass True if other users can add tasks to the checklist
        bool others_can_add_tasks = false;

        // Optional. Pass True if other users can mark tasks as done or not done in the checklist
        bool others_can_mark_tasks_as_done = false;
    };
    void to_json(json& j, const InputChecklist& value);
    void from_json(const json& j, InputChecklist& value);
}
