// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputProfilePhoto.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * An animated profile photo in the MPEG4 format.
     *
     * @param type Type of the profile photo, must be animated
     * @param animation The animated profile photo. Profile photos can't be reused and can only be uploaded as a new file, so you can pass “attach://<file_attach_name>” if the photo was uploaded using multipart/form-data under <file_attach_name>. More information on Sending Files »
     * @param main_frame_timestamp Optional. Timestamp in seconds of the frame that will be used as the static profile photo. Defaults to 0.0.
     */
    struct InputProfilePhotoAnimated : public InputProfilePhoto {
        typedef std::shared_ptr<InputProfilePhotoAnimated> Ptr;
        typedef std::weak_ptr<InputProfilePhotoAnimated> WeakPtr;

        virtual ~InputProfilePhotoAnimated() = default;
        // Type of the profile photo, must be animated
        std::string type_;

        // The animated profile photo. Profile photos can't be reused and can only be uploaded as a new file, so you can pass “attach://<file_attach_name>” if the photo was uploaded using multipart/form-data under <file_attach_name>. More information on Sending Files »
        std::string animation;

        // Optional. Timestamp in seconds of the frame that will be used as the static profile photo. Defaults to 0.0.
        double main_frame_timestamp = 0.0;
    };
    void to_json(json& j, const InputProfilePhotoAnimated& value);
    void from_json(const json& j, InputProfilePhotoAnimated& value);
}
