// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a unique message identifier.
     *
     * @param message_id Unique message identifier. In specific instances (e.g., message containing a video sent to a big chat), the server might automatically schedule a message instead of sending it immediately. In such cases, this field will be 0 and the relevant message will be unusable until it is actually sent
     */
    struct MessageId : public TelegramModel {
        typedef std::shared_ptr<MessageId> Ptr;
        typedef std::weak_ptr<MessageId> WeakPtr;

        virtual ~MessageId() = default;
        // Unique message identifier. In specific instances (e.g., message containing a video sent to a big chat), the server might automatically schedule a message instead of sending it immediately. In such cases, this field will be 0 and the relevant message will be unusable until it is actually sent
        int64_t message_id = 0;
    };
    void to_json(json& j, const MessageId& value);
    void from_json(const json& j, MessageId& value);
}
