// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/EncryptedPassportElement.hpp"
#include "types/EncryptedCredentials.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes Telegram Passport data shared with the bot by the user.
     *
     * @param data Array with information about documents and other Telegram Passport elements that was shared with the bot
     * @param credentials Encrypted credentials required to decrypt the data
     */
    struct PassportData : public TelegramModel {
        typedef std::shared_ptr<PassportData> Ptr;
        typedef std::weak_ptr<PassportData> WeakPtr;

        virtual ~PassportData() = default;
        // Array with information about documents and other Telegram Passport elements that was shared with the bot
        std::vector<EncryptedPassportElement::Ptr> data;

        // Encrypted credentials required to decrypt the data
        EncryptedCredentials::Ptr credentials;
    };
    void to_json(json& j, const PassportData& value);
    void from_json(const json& j, PassportData& value);
}
