// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Message.hpp"
#include "types/SuggestedPostPrice.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a service message about the approval of a suggested post.
     *
     * @param send_date Date when the post will be published
     * @param suggested_post_message Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     * @param price Optional. Amount paid for the post
     */
    struct SuggestedPostApproved : public TelegramModel {
        typedef std::shared_ptr<SuggestedPostApproved> Ptr;
        typedef std::weak_ptr<SuggestedPostApproved> WeakPtr;

        virtual ~SuggestedPostApproved() = default;
        // Date when the post will be published
        int64_t send_date = 0;

        // Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        Message::Ptr suggested_post_message;

        // Optional. Amount paid for the post
        SuggestedPostPrice::Ptr price;
    };
    void to_json(json& j, const SuggestedPostApproved& value);
    void from_json(const json& j, SuggestedPostApproved& value);
}
