// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/SuggestedPostPrice.hpp"
#include "types/Message.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a service message about the failed approval of a suggested post. Currently, only caused by insufficient user funds at the time of approval.
     *
     * @param price Expected price of the post
     * @param suggested_post_message Optional. Message containing the suggested post whose approval has failed. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     */
    struct SuggestedPostApprovalFailed : public TelegramModel {
        typedef std::shared_ptr<SuggestedPostApprovalFailed> Ptr;
        typedef std::weak_ptr<SuggestedPostApprovalFailed> WeakPtr;

        virtual ~SuggestedPostApprovalFailed() = default;
        // Expected price of the post
        SuggestedPostPrice::Ptr price;

        // Optional. Message containing the suggested post whose approval has failed. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        Message::Ptr suggested_post_message;
    };
    void to_json(json& j, const SuggestedPostApprovalFailed& value);
    void from_json(const json& j, SuggestedPostApprovalFailed& value);
}
