// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Sticker.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object describes the symbol shown on the pattern of a unique gift.
     *
     * @param name Name of the symbol
     * @param sticker The sticker that represents the unique gift
     * @param rarity_per_mille The number of unique gifts that receive this model for every 1000 gifts upgraded
     */
    struct UniqueGiftSymbol : public TelegramModel {
        typedef std::shared_ptr<UniqueGiftSymbol> Ptr;
        typedef std::weak_ptr<UniqueGiftSymbol> WeakPtr;

        virtual ~UniqueGiftSymbol() = default;
        // Name of the symbol
        std::string name;

        // The sticker that represents the unique gift
        Sticker::Ptr sticker;

        // The number of unique gifts that receive this model for every 1000 gifts upgraded
        int64_t rarity_per_mille = 0;
    };
    void to_json(json& j, const UniqueGiftSymbol& value);
    void from_json(const json& j, UniqueGiftSymbol& value);
}
