// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/UniqueGiftBackdropColors.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object describes the backdrop of a unique gift.
     *
     * @param name Name of the backdrop
     * @param colors Colors of the backdrop
     * @param rarity_per_mille The number of unique gifts that receive this backdrop for every 1000 gifts upgraded
     */
    struct UniqueGiftBackdrop : public TelegramModel {
        typedef std::shared_ptr<UniqueGiftBackdrop> Ptr;
        typedef std::weak_ptr<UniqueGiftBackdrop> WeakPtr;

        virtual ~UniqueGiftBackdrop() = default;
        // Name of the backdrop
        std::string name;

        // Colors of the backdrop
        UniqueGiftBackdropColors::Ptr colors;

        // The number of unique gifts that receive this backdrop for every 1000 gifts upgraded
        int64_t rarity_per_mille = 0;
    };
    void to_json(json& j, const UniqueGiftBackdrop& value);
    void from_json(const json& j, UniqueGiftBackdrop& value);
}
