// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/InlineQueryResultsButton.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to send answers to an inline query. On success, True is returned.No more than 50 results per query are allowed.
     *
     * @param inline_query_id Unique identifier for the answered query
     * @param results A JSON-serialized array of results for the inline query
     * @param cache_time The maximum amount of time in seconds that the result of the inline query may be cached on the server. Defaults to 300.
     * @param is_personal Pass True if results may be cached on the server side only for the user that sent the query. By default, results may be returned to any user who sends the same query.
     * @param next_offset Pass the offset that a client should send in the next query with the same text to receive more results. Pass an empty string if there are no more results or if you don't support pagination. Offset length can't exceed 64 bytes.
     * @param button A JSON-serialized object describing a button to be shown above inline query results
     */
    struct AnswerInlineQueryRequest {
        typedef std::shared_ptr<AnswerInlineQueryRequest> Ptr;
        // Unique identifier for the answered query
        std::string inline_query_id = "";

        // A JSON-serialized array of results for the inline query
        std::vector<InlineQueryResult::Ptr> results = std::vector<InlineQueryResult::Ptr>();

        // The maximum amount of time in seconds that the result of the inline query may be cached on the server. Defaults to 300.
        std::int64_t cache_time = 0;

        // Pass True if results may be cached on the server side only for the user that sent the query. By default, results may be returned to any user who sends the same query.
        bool is_personal = false;

        // Pass the offset that a client should send in the next query with the same text to receive more results. Pass an empty string if there are no more results or if you don't support pagination. Offset length can't exceed 64 bytes.
        std::string next_offset = "";

        // A JSON-serialized object describing a button to be shown above inline query results
        InlineQueryResultsButton::Ptr button = nullptr;
    };
    void to_json(json& j, const AnswerInlineQueryRequest& value);
    void from_json(const json& j, AnswerInlineQueryRequest& value);
}
