// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to approve a chat join request. The bot must be an administrator in the chat for this to work and must have the can_invite_users administrator right. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param user_id Unique identifier of the target user
     */
    struct ApproveChatJoinRequestRequest {
        typedef std::shared_ptr<ApproveChatJoinRequestRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // Unique identifier of the target user
        int64_t user_id = 0;
    };
    void to_json(json& j, const ApproveChatJoinRequestRequest& value);
    void from_json(const json& j, ApproveChatJoinRequestRequest& value);
}
