// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to create a subscription invite link for a channel chat. The bot must have the can_invite_users administrator rights. The link can be edited using the method editChatSubscriptionInviteLink or revoked using the method revokeChatInviteLink. Returns the new invite link as a ChatInviteLink object.
     *
     * @param chat_id Unique identifier for the target channel chat or username of the target channel (in the format @channelusername)
     * @param subscription_period The number of seconds the subscription will be active for before the next payment. Currently, it must always be 2592000 (30 days).
     * @param subscription_price The amount of Telegram Stars a user must pay initially and after each subsequent subscription period to be a member of the chat; 1-10000
     * @param name Invite link name; 0-32 characters
     */
    struct CreateChatSubscriptionInviteLinkRequest {
        typedef std::shared_ptr<CreateChatSubscriptionInviteLinkRequest> Ptr;
        // Unique identifier for the target channel chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // The number of seconds the subscription will be active for before the next payment. Currently, it must always be 2592000 (30 days).
        int64_t subscription_period = 0;

        // The amount of Telegram Stars a user must pay initially and after each subsequent subscription period to be a member of the chat; 1-10000
        int64_t subscription_price = 0;

        // Invite link name; 0-32 characters
        std::string name;
    };
    void to_json(json& j, const CreateChatSubscriptionInviteLinkRequest& value);
    void from_json(const json& j, CreateChatSubscriptionInviteLinkRequest& value);
}
