// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to delete a sticker from a set created by the bot. Returns True on success.
     *
     * @param sticker File identifier of the sticker
     */
    struct DeleteStickerFromSetRequest {
        typedef std::shared_ptr<DeleteStickerFromSetRequest> Ptr;
        // File identifier of the sticker
        std::string sticker = "";
    };
    void to_json(json& j, const DeleteStickerFromSetRequest& value);
    void from_json(const json& j, DeleteStickerFromSetRequest& value);
}
