// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to delete a sticker set that was created by the bot. Returns True on success.
     *
     * @param name Sticker set name
     */
    struct DeleteStickerSetRequest {
        typedef std::shared_ptr<DeleteStickerSetRequest> Ptr;
        // Sticker set name
        std::string name = "";
    };
    void to_json(json& j, const DeleteStickerSetRequest& value);
    void from_json(const json& j, DeleteStickerSetRequest& value);
}
