// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Delete messages on behalf of a business account. Requires the can_delete_sent_messages business bot right to delete messages sent by the bot itself, or the can_delete_all_messages business bot right to delete any message. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which to delete the messages
     * @param message_ids A JSON-serialized list of 1-100 identifiers of messages to delete. All messages must be from the same chat. See deleteMessage for limitations on which messages can be deleted
     */
    struct DeleteBusinessMessagesRequest {
        typedef std::shared_ptr<DeleteBusinessMessagesRequest> Ptr;
        // Unique identifier of the business connection on behalf of which to delete the messages
        std::string business_connection_id = "";

        // A JSON-serialized list of 1-100 identifiers of messages to delete. All messages must be from the same chat. See deleteMessage for limitations on which messages can be deleted
        std::vector<std::int64_t> message_ids = std::vector<std::int64_t>();
    };
    void to_json(json& j, const DeleteBusinessMessagesRequest& value);
    void from_json(const json& j, DeleteBusinessMessagesRequest& value);
}
