// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputChecklist.hpp"
#include "types/InlineKeyboardMarkup.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to edit a checklist on behalf of a connected business account. On success, the edited Message is returned.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param chat_id Unique identifier for the target chat
     * @param message_id Unique identifier for the target message
     * @param checklist A JSON-serialized object for the new checklist
     * @param reply_markup A JSON-serialized object for the new inline keyboard for the message
     */
    struct EditMessageChecklistRequest {
        typedef std::shared_ptr<EditMessageChecklistRequest> Ptr;
        // Unique identifier of the business connection on behalf of which the message will be sent
        std::string business_connection_id = "";

        // Unique identifier for the target chat
        std::int64_t chat_id = 0;

        // Unique identifier for the target message
        std::int64_t message_id = 0;

        // A JSON-serialized object for the new checklist
        InputChecklist::Ptr checklist = nullptr;

        // A JSON-serialized object for the new inline keyboard for the message
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;
    };
    void to_json(json& j, const EditMessageChecklistRequest& value);
    void from_json(const json& j, EditMessageChecklistRequest& value);
}
