// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/MessageEntity.hpp"
#include "types/InlineKeyboardMarkup.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to edit captions of messages. On success, if the edited message is not an inline message, the edited Message is returned, otherwise True is returned. Note that business messages that were not sent by the bot and do not contain an inline keyboard can only be edited within 48 hours from the time they were sent.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message to be edited was sent
     * @param chat_id Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Required if inline_message_id is not specified. Identifier of the message to edit
     * @param inline_message_id Required if chat_id and message_id are not specified. Identifier of the inline message
     * @param caption New caption of the message, 0-1024 characters after entities parsing
     * @param parse_mode Mode for parsing entities in the message caption. See formatting options for more details.
     * @param caption_entities A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param show_caption_above_media Pass True, if the caption must be shown above the message media. Supported only for animation, photo and video messages.
     * @param reply_markup A JSON-serialized object for an inline keyboard.
     */
    struct EditMessageCaptionRequest {
        typedef std::shared_ptr<EditMessageCaptionRequest> Ptr;
        // Unique identifier of the business connection on behalf of which the message to be edited was sent
        std::string business_connection_id = "";

        // Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        std::int64_t chat_id = 0;

        // Required if inline_message_id is not specified. Identifier of the message to edit
        std::int64_t message_id = 0;

        // Required if chat_id and message_id are not specified. Identifier of the inline message
        std::string inline_message_id = "";

        // New caption of the message, 0-1024 characters after entities parsing
        std::string caption = "";

        // Mode for parsing entities in the message caption. See formatting options for more details.
        std::string parse_mode = "";

        // A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities = std::vector<MessageEntity::Ptr>();

        // Pass True, if the caption must be shown above the message media. Supported only for animation, photo and video messages.
        bool show_caption_above_media = false;

        // A JSON-serialized object for an inline keyboard.
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;
    };
    void to_json(json& j, const EditMessageCaptionRequest& value);
    void from_json(const json& j, EditMessageCaptionRequest& value);
}
