// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to edit a subscription invite link created by the bot. The bot must have the can_invite_users administrator rights. Returns the edited invite link as a ChatInviteLink object.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param invite_link The invite link to edit
     * @param name Invite link name; 0-32 characters
     */
    struct EditChatSubscriptionInviteLinkRequest {
        typedef std::shared_ptr<EditChatSubscriptionInviteLinkRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        std::int64_t chat_id = 0;

        // The invite link to edit
        std::string invite_link = "";

        // Invite link name; 0-32 characters
        std::string name = "";
    };
    void to_json(json& j, const EditChatSubscriptionInviteLinkRequest& value);
    void from_json(const json& j, EditChatSubscriptionInviteLinkRequest& value);
}
