// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to get information about the connection of the bot with a business account. Returns a BusinessConnection object on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     */
    struct GetBusinessConnectionRequest {
        typedef std::shared_ptr<GetBusinessConnectionRequest> Ptr;
        // Unique identifier of the business connection
        std::string business_connection_id;
    };
    void to_json(json& j, const GetBusinessConnectionRequest& value);
    void from_json(const json& j, GetBusinessConnectionRequest& value);
}
