// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Returns the gifts owned by a chat. Returns OwnedGifts on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param exclude_unsaved Pass True to exclude gifts that aren't saved to the chat's profile page. Always True, unless the bot has the can_post_messages administrator right in the channel.
     * @param exclude_saved Pass True to exclude gifts that are saved to the chat's profile page. Always False, unless the bot has the can_post_messages administrator right in the channel.
     * @param exclude_unlimited Pass True to exclude gifts that can be purchased an unlimited number of times
     * @param exclude_limited_upgradable Pass True to exclude gifts that can be purchased a limited number of times and can be upgraded to unique
     * @param exclude_limited_non_upgradable Pass True to exclude gifts that can be purchased a limited number of times and can't be upgraded to unique
     * @param exclude_from_blockchain Pass True to exclude gifts that were assigned from the TON blockchain and can't be resold or transferred in Telegram
     * @param exclude_unique Pass True to exclude unique gifts
     * @param sort_by_price Pass True to sort results by gift price instead of send date. Sorting is applied before pagination.
     * @param offset Offset of the first entry to return as received from the previous request; use an empty string to get the first chunk of results
     * @param limit The maximum number of gifts to be returned; 1-100. Defaults to 100
     */
    struct GetChatGiftsRequest {
        typedef std::shared_ptr<GetChatGiftsRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        std::int64_t chat_id = 0;

        // Pass True to exclude gifts that aren't saved to the chat's profile page. Always True, unless the bot has the can_post_messages administrator right in the channel.
        bool exclude_unsaved = false;

        // Pass True to exclude gifts that are saved to the chat's profile page. Always False, unless the bot has the can_post_messages administrator right in the channel.
        bool exclude_saved = false;

        // Pass True to exclude gifts that can be purchased an unlimited number of times
        bool exclude_unlimited = false;

        // Pass True to exclude gifts that can be purchased a limited number of times and can be upgraded to unique
        bool exclude_limited_upgradable = false;

        // Pass True to exclude gifts that can be purchased a limited number of times and can't be upgraded to unique
        bool exclude_limited_non_upgradable = false;

        // Pass True to exclude gifts that were assigned from the TON blockchain and can't be resold or transferred in Telegram
        bool exclude_from_blockchain = false;

        // Pass True to exclude unique gifts
        bool exclude_unique = false;

        // Pass True to sort results by gift price instead of send date. Sorting is applied before pagination.
        bool sort_by_price = false;

        // Offset of the first entry to return as received from the previous request; use an empty string to get the first chunk of results
        std::string offset = "";

        // The maximum number of gifts to be returned; 1-100. Defaults to 100
        std::int64_t limit = 0;
    };
    void to_json(json& j, const GetChatGiftsRequest& value);
    void from_json(const json& j, GetChatGiftsRequest& value);
}
