// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to get a list of administrators in a chat, which aren't bots. Returns an Array of ChatMember objects.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup or channel (in the format @channelusername)
     */
    struct GetChatAdministratorsRequest {
        typedef std::shared_ptr<GetChatAdministratorsRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup or channel (in the format @channelusername)
        int64_t chat_id = 0;
    };
    void to_json(json& j, const GetChatAdministratorsRequest& value);
    void from_json(const json& j, GetChatAdministratorsRequest& value);
}
