// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to get the current bot description for the given user language. Returns BotDescription on success.
     *
     * @param language_code A two-letter ISO 639-1 language code or an empty string
     */
    struct GetMyDescriptionRequest {
        typedef std::shared_ptr<GetMyDescriptionRequest> Ptr;
        // A two-letter ISO 639-1 language code or an empty string
        std::string language_code = "";
    };
    void to_json(json& j, const GetMyDescriptionRequest& value);
    void from_json(const json& j, GetMyDescriptionRequest& value);
}
