// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to get the list of boosts added to a chat by a user. Requires administrator rights in the chat. Returns a UserChatBoosts object.
     *
     * @param chat_id Unique identifier for the chat or username of the channel (in the format @channelusername)
     * @param user_id Unique identifier of the target user
     */
    struct GetUserChatBoostsRequest {
        typedef std::shared_ptr<GetUserChatBoostsRequest> Ptr;
        // Unique identifier for the chat or username of the channel (in the format @channelusername)
        int64_t chat_id = 0;

        // Unique identifier of the target user
        int64_t user_id = 0;
    };
    void to_json(json& j, const GetUserChatBoostsRequest& value);
    void from_json(const json& j, GetUserChatBoostsRequest& value);
}
