// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to hide the 'General' topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights. The topic will be automatically closed if it was open. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
     */
    struct HideGeneralForumTopicRequest {
        typedef std::shared_ptr<HideGeneralForumTopicRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
        std::int64_t chat_id = 0;
    };
    void to_json(json& j, const HideGeneralForumTopicRequest& value);
    void from_json(const json& j, HideGeneralForumTopicRequest& value);
}
