// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/MessageEntity.hpp"
#include "types/StoryArea.hpp"
#include "types/InputStoryContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Posts a story on behalf of a managed business account. Requires the can_manage_stories business bot right. Returns Story on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param content Content of the story
     * @param active_period Period after which the story is moved to the archive, in seconds; must be one of 6 * 3600, 12 * 3600, 86400, or 2 * 86400
     * @param caption Caption of the story, 0-2048 characters after entities parsing
     * @param parse_mode Mode for parsing entities in the story caption. See formatting options for more details.
     * @param caption_entities A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param areas A JSON-serialized list of clickable areas to be shown on the story
     * @param post_to_chat_page Pass True to keep the story accessible after it expires
     * @param protect_content Pass True if the content of the story must be protected from forwarding and screenshotting
     */
    struct PostStoryRequest {
        typedef std::shared_ptr<PostStoryRequest> Ptr;
        // Unique identifier of the business connection
        std::string business_connection_id = "";

        // Content of the story
        InputStoryContent::Ptr content = nullptr;

        // Period after which the story is moved to the archive, in seconds; must be one of 6 * 3600, 12 * 3600, 86400, or 2 * 86400
        std::int64_t active_period = 0;

        // Caption of the story, 0-2048 characters after entities parsing
        std::string caption = "";

        // Mode for parsing entities in the story caption. See formatting options for more details.
        std::string parse_mode = "";

        // A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities = std::vector<MessageEntity::Ptr>();

        // A JSON-serialized list of clickable areas to be shown on the story
        std::vector<StoryArea::Ptr> areas = std::vector<StoryArea::Ptr>();

        // Pass True to keep the story accessible after it expires
        bool post_to_chat_page = false;

        // Pass True if the content of the story must be protected from forwarding and screenshotting
        bool protect_content = false;
    };
    void to_json(json& j, const PostStoryRequest& value);
    void from_json(const json& j, PostStoryRequest& value);
}
