// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Refunds a successful payment in Telegram Stars. Returns True on success.
     *
     * @param user_id Identifier of the user whose payment will be refunded
     * @param telegram_payment_charge_id Telegram payment identifier
     */
    struct RefundStarPaymentRequest {
        typedef std::shared_ptr<RefundStarPaymentRequest> Ptr;
        // Identifier of the user whose payment will be refunded
        std::int64_t user_id = 0;

        // Telegram payment identifier
        std::string telegram_payment_charge_id = "";
    };
    void to_json(json& j, const RefundStarPaymentRequest& value);
    void from_json(const json& j, RefundStarPaymentRequest& value);
}
