// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to reopen a closed topic in a forum supergroup chat. The bot must be an administrator in the chat for this to work and must have the can_manage_topics administrator rights, unless it is the creator of the topic. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
     * @param message_thread_id Unique identifier for the target message thread of the forum topic
     */
    struct ReopenForumTopicRequest {
        typedef std::shared_ptr<ReopenForumTopicRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
        std::int64_t chat_id = 0;

        // Unique identifier for the target message thread of the forum topic
        std::int64_t message_thread_id = 0;
    };
    void to_json(json& j, const ReopenForumTopicRequest& value);
    void from_json(const json& j, ReopenForumTopicRequest& value);
}
