// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputMedia.hpp"
#include "types/ReplyParameters.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to send a group of photos, videos, documents or audios as an album. Documents and audio files can be only grouped in an album with messages of the same type. On success, an array of Message objects that were sent is returned.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param media A JSON-serialized array describing messages to be sent, must include 2-10 items
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param message_thread_id Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
     * @param direct_messages_topic_id Identifier of the direct messages topic to which the messages will be sent; required if the messages are sent to a direct messages chat
     * @param disable_notification Sends messages silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the sent messages from forwarding and saving
     * @param allow_paid_broadcast Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
     * @param message_effect_id Unique identifier of the message effect to be added to the message; for private chats only
     * @param reply_parameters Description of the message to reply to
     */
    struct SendMediaGroupRequest {
        typedef std::shared_ptr<SendMediaGroupRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // A JSON-serialized array describing messages to be sent, must include 2-10 items
        std::vector<InputMedia::Ptr> media;

        // Unique identifier of the business connection on behalf of which the message will be sent
        std::string business_connection_id;

        // Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
        int64_t message_thread_id = 0;

        // Identifier of the direct messages topic to which the messages will be sent; required if the messages are sent to a direct messages chat
        int64_t direct_messages_topic_id = 0;

        // Sends messages silently. Users will receive a notification with no sound.
        bool disable_notification = false;

        // Protects the contents of the sent messages from forwarding and saving
        bool protect_content = false;

        // Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
        bool allow_paid_broadcast = false;

        // Unique identifier of the message effect to be added to the message; for private chats only
        std::string message_effect_id;

        // Description of the message to reply to
        ReplyParameters::Ptr reply_parameters;
    };
    void to_json(json& j, const SendMediaGroupRequest& value);
    void from_json(const json& j, SendMediaGroupRequest& value);
}
