// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ReplyParameters.hpp"
#include "types/InlineKeyboardMarkup.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to send a game. On success, the sent Message is returned.
     *
     * @param chat_id Unique identifier for the target chat. Games can't be sent to channel direct messages chats and channel chats.
     * @param game_short_name Short name of the game, serves as the unique identifier for the game. Set up your games via @BotFather.
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param message_thread_id Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
     * @param disable_notification Sends the message silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the sent message from forwarding and saving
     * @param allow_paid_broadcast Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
     * @param message_effect_id Unique identifier of the message effect to be added to the message; for private chats only
     * @param reply_parameters Description of the message to reply to
     * @param reply_markup A JSON-serialized object for an inline keyboard. If empty, one 'Play game_title' button will be shown. If not empty, the first button must launch the game.
     */
    struct SendGameRequest {
        typedef std::shared_ptr<SendGameRequest> Ptr;
        // Unique identifier for the target chat. Games can't be sent to channel direct messages chats and channel chats.
        std::int64_t chat_id = 0;

        // Short name of the game, serves as the unique identifier for the game. Set up your games via @BotFather.
        std::string game_short_name = "";

        // Unique identifier of the business connection on behalf of which the message will be sent
        std::string business_connection_id = "";

        // Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
        std::int64_t message_thread_id = 0;

        // Sends the message silently. Users will receive a notification with no sound.
        bool disable_notification = false;

        // Protects the contents of the sent message from forwarding and saving
        bool protect_content = false;

        // Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
        bool allow_paid_broadcast = false;

        // Unique identifier of the message effect to be added to the message; for private chats only
        std::string message_effect_id = "";

        // Description of the message to reply to
        ReplyParameters::Ptr reply_parameters = nullptr;

        // A JSON-serialized object for an inline keyboard. If empty, one 'Play game_title' button will be shown. If not empty, the first button must launch the game.
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;
    };
    void to_json(json& j, const SendGameRequest& value);
    void from_json(const json& j, SendGameRequest& value);
}
