// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to set a new group sticker set for a supergroup. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Use the field can_set_sticker_set optionally returned in getChat requests to check if the bot can use this method. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
     * @param sticker_set_name Name of the sticker set to be set as the group sticker set
     */
    struct SetChatStickerSetRequest {
        typedef std::shared_ptr<SetChatStickerSetRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
        int64_t chat_id = 0;

        // Name of the sticker set to be set as the group sticker set
        std::string sticker_set_name;
    };
    void to_json(json& j, const SetChatStickerSetRequest& value);
    void from_json(const json& j, SetChatStickerSetRequest& value);
}
