// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to set a tag for a regular member in a group or a supergroup. The bot must be an administrator in the chat for this to work and must have the can_manage_tags administrator right. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
     * @param user_id Unique identifier of the target user
     * @param tag New tag for the member; 0-16 characters, emoji are not allowed
     */
    struct SetChatMemberTagRequest {
        typedef std::shared_ptr<SetChatMemberTagRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
        std::int64_t chat_id = 0;

        // Unique identifier of the target user
        std::int64_t user_id = 0;

        // New tag for the member; 0-16 characters, emoji are not allowed
        std::string tag = "";
    };
    void to_json(json& j, const SetChatMemberTagRequest& value);
    void from_json(const json& j, SetChatMemberTagRequest& value);
}
