// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to change the title of a chat. Titles can't be changed for private chats. The bot must be an administrator in the chat for this to work and must have the appropriate administrator rights. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param title New chat title, 1-128 characters
     */
    struct SetChatTitleRequest {
        typedef std::shared_ptr<SetChatTitleRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // New chat title, 1-128 characters
        std::string title;
    };
    void to_json(json& j, const SetChatTitleRequest& value);
    void from_json(const json& j, SetChatTitleRequest& value);
}
