// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ReactionType.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to change the chosen reactions on a message. Service messages of some types can't be reacted to. Automatically forwarded messages from a channel to its discussion group have the same available reactions as messages in the channel. Bots can't use paid reactions. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Identifier of the target message. If the message belongs to a media group, the reaction is set to the first non-deleted message in the group instead.
     * @param reaction A JSON-serialized list of reaction types to set on the message. Currently, as non-premium users, bots can set up to one reaction per message. A custom emoji reaction can be used if it is either already present on the message or explicitly allowed by chat administrators. Paid reactions can't be used by bots.
     * @param is_big Pass True to set the reaction with a big animation
     */
    struct SetMessageReactionRequest {
        typedef std::shared_ptr<SetMessageReactionRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        std::int64_t chat_id = 0;

        // Identifier of the target message. If the message belongs to a media group, the reaction is set to the first non-deleted message in the group instead.
        std::int64_t message_id = 0;

        // A JSON-serialized list of reaction types to set on the message. Currently, as non-premium users, bots can set up to one reaction per message. A custom emoji reaction can be used if it is either already present on the message or explicitly allowed by chat administrators. Paid reactions can't be used by bots.
        std::vector<ReactionType::Ptr> reaction = std::vector<ReactionType::Ptr>();

        // Pass True to set the reaction with a big animation
        bool is_big = false;
    };
    void to_json(json& j, const SetMessageReactionRequest& value);
    void from_json(const json& j, SetMessageReactionRequest& value);
}
