// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputProfilePhoto.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Changes the profile photo of the bot. Returns True on success.
     *
     * @param photo The new profile photo to set
     */
    struct SetMyProfilePhotoRequest {
        typedef std::shared_ptr<SetMyProfilePhotoRequest> Ptr;
        // The new profile photo to set
        InputProfilePhoto::Ptr photo = nullptr;
    };
    void to_json(json& j, const SetMyProfilePhotoRequest& value);
    void from_json(const json& j, SetMyProfilePhotoRequest& value);
}
