// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to change the bot's description, which is shown in the chat with the bot if the chat is empty. Returns True on success.
     *
     * @param description New bot description; 0-512 characters. Pass an empty string to remove the dedicated description for the given language.
     * @param language_code A two-letter ISO 639-1 language code. If empty, the description will be applied to all users for whose language there is no dedicated description.
     */
    struct SetMyDescriptionRequest {
        typedef std::shared_ptr<SetMyDescriptionRequest> Ptr;
        // New bot description; 0-512 characters. Pass an empty string to remove the dedicated description for the given language.
        std::string description = "";

        // A two-letter ISO 639-1 language code. If empty, the description will be applied to all users for whose language there is no dedicated description.
        std::string language_code = "";
    };
    void to_json(json& j, const SetMyDescriptionRequest& value);
    void from_json(const json& j, SetMyDescriptionRequest& value);
}
