// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to change the bot's name. Returns True on success.
     *
     * @param name New bot name; 0-64 characters. Pass an empty string to remove the dedicated name for the given language.
     * @param language_code A two-letter ISO 639-1 language code. If empty, the name will be shown to all users for whose language there is no dedicated name.
     */
    struct SetMyNameRequest {
        typedef std::shared_ptr<SetMyNameRequest> Ptr;
        // New bot name; 0-64 characters. Pass an empty string to remove the dedicated name for the given language.
        std::string name;

        // A two-letter ISO 639-1 language code. If empty, the name will be shown to all users for whose language there is no dedicated name.
        std::string language_code;
    };
    void to_json(json& j, const SetMyNameRequest& value);
    void from_json(const json& j, SetMyNameRequest& value);
}
