// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/MaskPosition.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to change the mask position of a mask sticker. The sticker must belong to a sticker set that was created by the bot. Returns True on success.
     *
     * @param sticker File identifier of the sticker
     * @param mask_position A JSON-serialized object with the position where the mask should be placed on faces. Omit the parameter to remove the mask position.
     */
    struct SetStickerMaskPositionRequest {
        typedef std::shared_ptr<SetStickerMaskPositionRequest> Ptr;
        // File identifier of the sticker
        std::string sticker;

        // A JSON-serialized object with the position where the mask should be placed on faces. Omit the parameter to remove the mask position.
        MaskPosition::Ptr mask_position;
    };
    void to_json(json& j, const SetStickerMaskPositionRequest& value);
    void from_json(const json& j, SetStickerMaskPositionRequest& value);
}
