// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to set the title of a created sticker set. Returns True on success.
     *
     * @param name Sticker set name
     * @param title Sticker set title, 1-64 characters
     */
    struct SetStickerSetTitleRequest {
        typedef std::shared_ptr<SetStickerSetTitleRequest> Ptr;
        // Sticker set name
        std::string name = "";

        // Sticker set title, 1-64 characters
        std::string title = "";
    };
    void to_json(json& j, const SetStickerSetTitleRequest& value);
    void from_json(const json& j, SetStickerSetTitleRequest& value);
}
