// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/PhotoSize.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents an audio file to be treated as music by the Telegram clients.
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param duration Duration of the audio in seconds as defined by the sender
     * @param performer Optional. Performer of the audio as defined by the sender or by audio tags
     * @param title Optional. Title of the audio as defined by the sender or by audio tags
     * @param file_name Optional. Original filename as defined by the sender
     * @param mime_type Optional. MIME type of the file as defined by the sender
     * @param file_size Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
     * @param thumbnail Optional. Thumbnail of the album cover to which the music file belongs
     */
    struct Audio : public TelegramModel {
        typedef std::shared_ptr<Audio> Ptr;
        typedef std::weak_ptr<Audio> WeakPtr;

        virtual ~Audio() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id = "";

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id = "";

        // Duration of the audio in seconds as defined by the sender
        std::int64_t duration = 0;

        // Optional. Performer of the audio as defined by the sender or by audio tags
        std::string performer = "";

        // Optional. Title of the audio as defined by the sender or by audio tags
        std::string title = "";

        // Optional. Original filename as defined by the sender
        std::string file_name = "";

        // Optional. MIME type of the file as defined by the sender
        std::string mime_type = "";

        // Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
        std::int64_t file_size = 0;

        // Optional. Thumbnail of the album cover to which the music file belongs
        PhotoSize::Ptr thumbnail = nullptr;
    };
    void to_json(json& j, const Audio& value);
    void from_json(const json& j, Audio& value);
}
