// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/BackgroundType.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The background is taken directly from a built-in chat theme.
     *
     * @param type Type of the background, always “chat_theme”
     * @param theme_name Name of the chat theme, which is usually an emoji
     */
    struct BackgroundTypeChatTheme : public BackgroundType {
        typedef std::shared_ptr<BackgroundTypeChatTheme> Ptr;
        typedef std::weak_ptr<BackgroundTypeChatTheme> WeakPtr;

        virtual ~BackgroundTypeChatTheme() = default;
        // Type of the background, always “chat_theme”
        std::string type_ = "";

        // Name of the chat theme, which is usually an emoji
        std::string theme_name = "";
    };
    void to_json(json& j, const BackgroundTypeChatTheme& value);
    void from_json(const json& j, BackgroundTypeChatTheme& value);
}
