// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/BackgroundType.hpp"
#include "types/BackgroundFill.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The background is automatically filled based on the selected colors.
     *
     * @param type Type of the background, always “fill”
     * @param fill The background fill
     * @param dark_theme_dimming Dimming of the background in dark themes, as a percentage; 0-100
     */
    struct BackgroundTypeFill : public BackgroundType {
        typedef std::shared_ptr<BackgroundTypeFill> Ptr;
        typedef std::weak_ptr<BackgroundTypeFill> WeakPtr;

        virtual ~BackgroundTypeFill() = default;
        // Type of the background, always “fill”
        std::string type_ = "";

        // The background fill
        BackgroundFill::Ptr fill = nullptr;

        // Dimming of the background in dark themes, as a percentage; 0-100
        std::int64_t dark_theme_dimming = 0;
    };
    void to_json(json& j, const BackgroundTypeFill& value);
    void from_json(const json& j, BackgroundTypeFill& value);
}
