// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    struct BotCommandScope : public TelegramModel {
        typedef std::shared_ptr<BotCommandScope> Ptr;
        virtual ~BotCommandScope() = default;
    };

    void to_json(json& j, const BotCommandScope& value);
    void from_json(const json& j, BotCommandScope& value);
}
