// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/BotCommandScope.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents the scope of bot commands, covering all group and supergroup chats.
     *
     * @param type Scope type, must be all_group_chats
     */
    struct BotCommandScopeAllGroupChats : public BotCommandScope {
        typedef std::shared_ptr<BotCommandScopeAllGroupChats> Ptr;
        typedef std::weak_ptr<BotCommandScopeAllGroupChats> WeakPtr;

        virtual ~BotCommandScopeAllGroupChats() = default;
        // Scope type, must be all_group_chats
        std::string type_;
    };
    void to_json(json& j, const BotCommandScopeAllGroupChats& value);
    void from_json(const json& j, BotCommandScopeAllGroupChats& value);
}
