// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents the bot's short description.
     *
     * @param short_description The bot's short description
     */
    struct BotShortDescription : public TelegramModel {
        typedef std::shared_ptr<BotShortDescription> Ptr;
        typedef std::weak_ptr<BotShortDescription> WeakPtr;

        virtual ~BotShortDescription() = default;
        // The bot's short description
        std::string short_description;
    };
    void to_json(json& j, const BotShortDescription& value);
    void from_json(const json& j, BotShortDescription& value);
}
