// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Sticker.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Contains information about the start page settings of a Telegram Business account.
     *
     * @param title Optional. Title text of the business intro
     * @param message Optional. Message text of the business intro
     * @param sticker Optional. Sticker of the business intro
     */
    struct BusinessIntro : public TelegramModel {
        typedef std::shared_ptr<BusinessIntro> Ptr;
        typedef std::weak_ptr<BusinessIntro> WeakPtr;

        virtual ~BusinessIntro() = default;
        // Optional. Title text of the business intro
        std::string title = "";

        // Optional. Message text of the business intro
        std::string message = "";

        // Optional. Sticker of the business intro
        Sticker::Ptr sticker = nullptr;
    };
    void to_json(json& j, const BusinessIntro& value);
    void from_json(const json& j, BusinessIntro& value);
}
