// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ChatMember.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a chat member that owns the chat and has all administrator privileges.
     *
     * @param status The member's status in the chat, always “creator”
     * @param user Information about the user
     * @param is_anonymous True, if the user's presence in the chat is hidden
     * @param custom_title Optional. Custom title for this user
     */
    struct ChatMemberOwner : public ChatMember {
        typedef std::shared_ptr<ChatMemberOwner> Ptr;
        typedef std::weak_ptr<ChatMemberOwner> WeakPtr;

        virtual ~ChatMemberOwner() = default;
        // The member's status in the chat, always “creator”
        std::string status = "";

        // Information about the user
        User::Ptr user = nullptr;

        // True, if the user's presence in the chat is hidden
        bool is_anonymous = false;

        // Optional. Custom title for this user
        std::string custom_title = "";
    };
    void to_json(json& j, const ChatMemberOwner& value);
    void from_json(const json& j, ChatMemberOwner& value);
}
