// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/MessageEntity.hpp"
#include "types/User.hpp"
#include "types/Chat.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a task in a checklist.
     *
     * @param id Unique identifier of the task
     * @param text Text of the task
     * @param text_entities Optional. Special entities that appear in the task text
     * @param completed_by_user Optional. User that completed the task; omitted if the task wasn't completed by a user
     * @param completed_by_chat Optional. Chat that completed the task; omitted if the task wasn't completed by a chat
     * @param completion_date Optional. Point in time (Unix timestamp) when the task was completed; 0 if the task wasn't completed
     */
    struct ChecklistTask : public TelegramModel {
        typedef std::shared_ptr<ChecklistTask> Ptr;
        typedef std::weak_ptr<ChecklistTask> WeakPtr;

        virtual ~ChecklistTask() = default;
        // Unique identifier of the task
        std::int64_t id = 0;

        // Text of the task
        std::string text = "";

        // Optional. Special entities that appear in the task text
        std::vector<MessageEntity::Ptr> text_entities = std::vector<MessageEntity::Ptr>();

        // Optional. User that completed the task; omitted if the task wasn't completed by a user
        User::Ptr completed_by_user = nullptr;

        // Optional. Chat that completed the task; omitted if the task wasn't completed by a chat
        Chat::Ptr completed_by_chat = nullptr;

        // Optional. Point in time (Unix timestamp) when the task was completed; 0 if the task wasn't completed
        std::int64_t completion_date = 0;
    };
    void to_json(json& j, const ChecklistTask& value);
    void from_json(const json& j, ChecklistTask& value);
}
