// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/User.hpp"
#include "types/Location.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a result of an inline query that was chosen by the user and sent to their chat partner.Note: It is necessary to enable inline feedback via @BotFather in order to receive these objects in updates.
     *
     * @param result_id The unique identifier for the result that was chosen
     * @param from The user that chose the result
     * @param query The query that was used to obtain the result
     * @param location Optional. Sender location, only for bots that require user location
     * @param inline_message_id Optional. Identifier of the sent inline message. Available only if there is an inline keyboard attached to the message. Will be also received in callback queries and can be used to edit the message.
     */
    struct ChosenInlineResult : public TelegramModel {
        typedef std::shared_ptr<ChosenInlineResult> Ptr;
        typedef std::weak_ptr<ChosenInlineResult> WeakPtr;

        virtual ~ChosenInlineResult() = default;
        // The unique identifier for the result that was chosen
        std::string result_id = "";

        // The user that chose the result
        User::Ptr from = nullptr;

        // The query that was used to obtain the result
        std::string query = "";

        // Optional. Sender location, only for bots that require user location
        Location::Ptr location = nullptr;

        // Optional. Identifier of the sent inline message. Available only if there is an inline keyboard attached to the message. Will be also received in callback queries and can be used to edit the message.
        std::string inline_message_id = "";
    };
    void to_json(json& j, const ChosenInlineResult& value);
    void from_json(const json& j, ChosenInlineResult& value);
}
