// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/PhotoSize.hpp"
#include "types/MessageOrigin.hpp"
#include "types/Chat.hpp"
#include "types/LinkPreviewOptions.hpp"
#include "types/Animation.hpp"
#include "types/Audio.hpp"
#include "types/Document.hpp"
#include "types/PaidMediaInfo.hpp"
#include "types/Sticker.hpp"
#include "types/Story.hpp"
#include "types/Video.hpp"
#include "types/VideoNote.hpp"
#include "types/Voice.hpp"
#include "types/Checklist.hpp"
#include "types/Contact.hpp"
#include "types/Dice.hpp"
#include "types/Game.hpp"
#include "types/Giveaway.hpp"
#include "types/GiveawayWinners.hpp"
#include "types/Invoice.hpp"
#include "types/Location.hpp"
#include "types/Poll.hpp"
#include "types/Venue.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains information about a message that is being replied to, which may come from another chat or forum topic.
     *
     * @param origin Origin of the message replied to by the given message
     * @param chat Optional. Chat the original message belongs to. Available only if the chat is a supergroup or a channel.
     * @param message_id Optional. Unique message identifier inside the original chat. Available only if the original chat is a supergroup or a channel.
     * @param link_preview_options Optional. Options used for link preview generation for the original message, if it is a text message
     * @param animation Optional. Message is an animation, information about the animation
     * @param audio Optional. Message is an audio file, information about the file
     * @param document Optional. Message is a general file, information about the file
     * @param paid_media Optional. Message contains paid media; information about the paid media
     * @param photo Optional. Message is a photo, available sizes of the photo
     * @param sticker Optional. Message is a sticker, information about the sticker
     * @param story Optional. Message is a forwarded story
     * @param video Optional. Message is a video, information about the video
     * @param video_note Optional. Message is a video note, information about the video message
     * @param voice Optional. Message is a voice message, information about the file
     * @param has_media_spoiler Optional. True, if the message media is covered by a spoiler animation
     * @param checklist Optional. Message is a checklist
     * @param contact Optional. Message is a shared contact, information about the contact
     * @param dice Optional. Message is a dice with random value
     * @param game Optional. Message is a game, information about the game. More about games »
     * @param giveaway Optional. Message is a scheduled giveaway, information about the giveaway
     * @param giveaway_winners Optional. A giveaway with public winners was completed
     * @param invoice Optional. Message is an invoice for a payment, information about the invoice. More about payments »
     * @param location Optional. Message is a shared location, information about the location
     * @param poll Optional. Message is a native poll, information about the poll
     * @param venue Optional. Message is a venue, information about the venue
     */
    struct ExternalReplyInfo : public TelegramModel {
        typedef std::shared_ptr<ExternalReplyInfo> Ptr;
        typedef std::weak_ptr<ExternalReplyInfo> WeakPtr;

        virtual ~ExternalReplyInfo() = default;
        // Origin of the message replied to by the given message
        MessageOrigin::Ptr origin = nullptr;

        // Optional. Chat the original message belongs to. Available only if the chat is a supergroup or a channel.
        Chat::Ptr chat = nullptr;

        // Optional. Unique message identifier inside the original chat. Available only if the original chat is a supergroup or a channel.
        std::int64_t message_id = 0;

        // Optional. Options used for link preview generation for the original message, if it is a text message
        LinkPreviewOptions::Ptr link_preview_options = nullptr;

        // Optional. Message is an animation, information about the animation
        Animation::Ptr animation = nullptr;

        // Optional. Message is an audio file, information about the file
        Audio::Ptr audio = nullptr;

        // Optional. Message is a general file, information about the file
        Document::Ptr document = nullptr;

        // Optional. Message contains paid media; information about the paid media
        PaidMediaInfo::Ptr paid_media = nullptr;

        // Optional. Message is a photo, available sizes of the photo
        std::vector<PhotoSize::Ptr> photo = std::vector<PhotoSize::Ptr>();

        // Optional. Message is a sticker, information about the sticker
        Sticker::Ptr sticker = nullptr;

        // Optional. Message is a forwarded story
        Story::Ptr story = nullptr;

        // Optional. Message is a video, information about the video
        Video::Ptr video = nullptr;

        // Optional. Message is a video note, information about the video message
        VideoNote::Ptr video_note = nullptr;

        // Optional. Message is a voice message, information about the file
        Voice::Ptr voice = nullptr;

        // Optional. True, if the message media is covered by a spoiler animation
        bool has_media_spoiler = false;

        // Optional. Message is a checklist
        Checklist::Ptr checklist = nullptr;

        // Optional. Message is a shared contact, information about the contact
        Contact::Ptr contact = nullptr;

        // Optional. Message is a dice with random value
        Dice::Ptr dice = nullptr;

        // Optional. Message is a game, information about the game. More about games »
        Game::Ptr game = nullptr;

        // Optional. Message is a scheduled giveaway, information about the giveaway
        Giveaway::Ptr giveaway = nullptr;

        // Optional. A giveaway with public winners was completed
        GiveawayWinners::Ptr giveaway_winners = nullptr;

        // Optional. Message is an invoice for a payment, information about the invoice. More about payments »
        Invoice::Ptr invoice = nullptr;

        // Optional. Message is a shared location, information about the location
        Location::Ptr location = nullptr;

        // Optional. Message is a native poll, information about the poll
        Poll::Ptr poll = nullptr;

        // Optional. Message is a venue, information about the venue
        Venue::Ptr venue = nullptr;
    };
    void to_json(json& j, const ExternalReplyInfo& value);
    void from_json(const json& j, ExternalReplyInfo& value);
}
