// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a file ready to be downloaded. The file can be downloaded via the link https://api.telegram.org/file/bot<token>/<file_path>. It is guaranteed that the link will be valid for at least 1 hour. When the link expires, a new one can be requested by calling getFile.
     *  The maximum file size to download is 20 MB
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param file_size Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
     * @param file_path Optional. File path. Use https://api.telegram.org/file/bot<token>/<file_path> to get the file.
     */
    struct File : public TelegramModel {
        typedef std::shared_ptr<File> Ptr;
        typedef std::weak_ptr<File> WeakPtr;

        virtual ~File() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id;

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id;

        // Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
        int64_t file_size = 0;

        // Optional. File path. Use https://api.telegram.org/file/bot<token>/<file_path> to get the file.
        std::string file_path;
    };
    void to_json(json& j, const File& value);
    void from_json(const json& j, File& value);
}
