// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about a new forum topic created in the chat.
     *
     * @param name Name of the topic
     * @param icon_color Color of the topic icon in RGB format
     * @param icon_custom_emoji_id Optional. Unique identifier of the custom emoji shown as the topic icon
     * @param is_name_implicit Optional. True, if the name of the topic wasn't specified explicitly by its creator and likely needs to be changed by the bot
     */
    struct ForumTopicCreated : public TelegramModel {
        typedef std::shared_ptr<ForumTopicCreated> Ptr;
        typedef std::weak_ptr<ForumTopicCreated> WeakPtr;

        virtual ~ForumTopicCreated() = default;
        // Name of the topic
        std::string name = "";

        // Color of the topic icon in RGB format
        std::int64_t icon_color = 0;

        // Optional. Unique identifier of the custom emoji shown as the topic icon
        std::string icon_custom_emoji_id = "";

        // Optional. True, if the name of the topic wasn't specified explicitly by its creator and likely needs to be changed by the bot
        bool is_name_implicit = false;
    };
    void to_json(json& j, const ForumTopicCreated& value);
    void from_json(const json& j, ForumTopicCreated& value);
}
