// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/PhotoSize.hpp"
#include "types/MessageEntity.hpp"
#include "types/Animation.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a game. Use BotFather to create and edit games, their short names will act as unique identifiers.
     *
     * @param title Title of the game
     * @param description Description of the game
     * @param photo Photo that will be displayed in the game message in chats.
     * @param text Optional. Brief description of the game or high scores included in the game message. Can be automatically edited to include current high scores for the game when the bot calls setGameScore, or manually edited using editMessageText. 0-4096 characters.
     * @param text_entities Optional. Special entities that appear in text, such as usernames, URLs, bot commands, etc.
     * @param animation Optional. Animation that will be displayed in the game message in chats. Upload via BotFather
     */
    struct Game : public TelegramModel {
        typedef std::shared_ptr<Game> Ptr;
        typedef std::weak_ptr<Game> WeakPtr;

        virtual ~Game() = default;
        // Title of the game
        std::string title = "";

        // Description of the game
        std::string description = "";

        // Photo that will be displayed in the game message in chats.
        std::vector<PhotoSize::Ptr> photo = std::vector<PhotoSize::Ptr>();

        // Optional. Brief description of the game or high scores included in the game message. Can be automatically edited to include current high scores for the game when the bot calls setGameScore, or manually edited using editMessageText. 0-4096 characters.
        std::string text = "";

        // Optional. Special entities that appear in text, such as usernames, URLs, bot commands, etc.
        std::vector<MessageEntity::Ptr> text_entities = std::vector<MessageEntity::Ptr>();

        // Optional. Animation that will be displayed in the game message in chats. Upload via BotFather
        Animation::Ptr animation = nullptr;
    };
    void to_json(json& j, const Game& value);
    void from_json(const json& j, Game& value);
}
