// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/User.hpp"
#include "types/Chat.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a message about the completion of a giveaway with public winners.
     *
     * @param chat The chat that created the giveaway
     * @param giveaway_message_id Identifier of the message with the giveaway in the chat
     * @param winners_selection_date Point in time (Unix timestamp) when winners of the giveaway were selected
     * @param winner_count Total number of winners in the giveaway
     * @param winners List of up to 100 winners of the giveaway
     * @param additional_chat_count Optional. The number of other chats the user had to join in order to be eligible for the giveaway
     * @param prize_star_count Optional. The number of Telegram Stars that were split between giveaway winners; for Telegram Star giveaways only
     * @param premium_subscription_month_count Optional. The number of months the Telegram Premium subscription won from the giveaway will be active for; for Telegram Premium giveaways only
     * @param unclaimed_prize_count Optional. Number of undistributed prizes
     * @param only_new_members Optional. True, if only users who had joined the chats after the giveaway started were eligible to win
     * @param was_refunded Optional. True, if the giveaway was canceled because the payment for it was refunded
     * @param prize_description Optional. Description of additional giveaway prize
     */
    struct GiveawayWinners : public TelegramModel {
        typedef std::shared_ptr<GiveawayWinners> Ptr;
        typedef std::weak_ptr<GiveawayWinners> WeakPtr;

        virtual ~GiveawayWinners() = default;
        // The chat that created the giveaway
        Chat::Ptr chat = nullptr;

        // Identifier of the message with the giveaway in the chat
        std::int64_t giveaway_message_id = 0;

        // Point in time (Unix timestamp) when winners of the giveaway were selected
        std::int64_t winners_selection_date = 0;

        // Total number of winners in the giveaway
        std::int64_t winner_count = 0;

        // List of up to 100 winners of the giveaway
        std::vector<User::Ptr> winners = std::vector<User::Ptr>();

        // Optional. The number of other chats the user had to join in order to be eligible for the giveaway
        std::int64_t additional_chat_count = 0;

        // Optional. The number of Telegram Stars that were split between giveaway winners; for Telegram Star giveaways only
        std::int64_t prize_star_count = 0;

        // Optional. The number of months the Telegram Premium subscription won from the giveaway will be active for; for Telegram Premium giveaways only
        std::int64_t premium_subscription_month_count = 0;

        // Optional. Number of undistributed prizes
        std::int64_t unclaimed_prize_count = 0;

        // Optional. True, if only users who had joined the chats after the giveaway started were eligible to win
        bool only_new_members = false;

        // Optional. True, if the giveaway was canceled because the payment for it was refunded
        bool was_refunded = false;

        // Optional. Description of additional giveaway prize
        std::string prize_description = "";
    };
    void to_json(json& j, const GiveawayWinners& value);
    void from_json(const json& j, GiveawayWinners& value);
}
