// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Chat.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a message about a scheduled giveaway.
     *
     * @param chats The list of chats which the user must join to participate in the giveaway
     * @param winners_selection_date Point in time (Unix timestamp) when winners of the giveaway will be selected
     * @param winner_count The number of users which are supposed to be selected as winners of the giveaway
     * @param only_new_members Optional. True, if only users who join the chats after the giveaway started should be eligible to win
     * @param has_public_winners Optional. True, if the list of giveaway winners will be visible to everyone
     * @param prize_description Optional. Description of additional giveaway prize
     * @param country_codes Optional. A list of two-letter ISO 3166-1 alpha-2 country codes indicating the countries from which eligible users for the giveaway must come. If empty, then all users can participate in the giveaway. Users with a phone number that was bought on Fragment can always participate in giveaways.
     * @param prize_star_count Optional. The number of Telegram Stars to be split between giveaway winners; for Telegram Star giveaways only
     * @param premium_subscription_month_count Optional. The number of months the Telegram Premium subscription won from the giveaway will be active for; for Telegram Premium giveaways only
     */
    struct Giveaway : public TelegramModel {
        typedef std::shared_ptr<Giveaway> Ptr;
        typedef std::weak_ptr<Giveaway> WeakPtr;

        virtual ~Giveaway() = default;
        // The list of chats which the user must join to participate in the giveaway
        std::vector<Chat::Ptr> chats;

        // Point in time (Unix timestamp) when winners of the giveaway will be selected
        int64_t winners_selection_date = 0;

        // The number of users which are supposed to be selected as winners of the giveaway
        int64_t winner_count = 0;

        // Optional. True, if only users who join the chats after the giveaway started should be eligible to win
        bool only_new_members = false;

        // Optional. True, if the list of giveaway winners will be visible to everyone
        bool has_public_winners = false;

        // Optional. Description of additional giveaway prize
        std::string prize_description;

        // Optional. A list of two-letter ISO 3166-1 alpha-2 country codes indicating the countries from which eligible users for the giveaway must come. If empty, then all users can participate in the giveaway. Users with a phone number that was bought on Fragment can always participate in giveaways.
        std::vector<std::string> country_codes;

        // Optional. The number of Telegram Stars to be split between giveaway winners; for Telegram Star giveaways only
        int64_t prize_star_count = 0;

        // Optional. The number of months the Telegram Premium subscription won from the giveaway will be active for; for Telegram Premium giveaways only
        int64_t premium_subscription_month_count = 0;
    };
    void to_json(json& j, const Giveaway& value);
    void from_json(const json& j, Giveaway& value);
}
