// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/MessageEntity.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a link to a page containing an embedded video player or a video file. By default, this video file will be sent by the user with an optional caption. Alternatively, you can use input_message_content to send a message with the specified content instead of the video.
     *  If an InlineQueryResultVideo message contains an embedded video (e.g., YouTube), you must replace its content using input_message_content.
     *
     * @param type Type of the result, must be video
     * @param id Unique identifier for this result, 1-64 bytes
     * @param video_url A valid URL for the embedded video player or video file
     * @param mime_type MIME type of the content of the video URL, “text/html” or “video/mp4”
     * @param thumbnail_url URL of the thumbnail (JPEG only) for the video
     * @param title Title for the result
     * @param caption Optional. Caption of the video to be sent, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the video caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param show_caption_above_media Optional. Pass True, if the caption must be shown above the message media
     * @param video_width Optional. Video width
     * @param video_height Optional. Video height
     * @param video_duration Optional. Video duration in seconds
     * @param description Optional. Short description of the result
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the video. This field is required if InlineQueryResultVideo is used to send an HTML-page as a result (e.g., a YouTube video).
     */
    struct InlineQueryResultVideo : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultVideo> Ptr;
        typedef std::weak_ptr<InlineQueryResultVideo> WeakPtr;

        virtual ~InlineQueryResultVideo() = default;
        // Type of the result, must be video
        std::string type_;

        // Unique identifier for this result, 1-64 bytes
        std::string id;

        // A valid URL for the embedded video player or video file
        std::string video_url;

        // MIME type of the content of the video URL, “text/html” or “video/mp4”
        std::string mime_type;

        // URL of the thumbnail (JPEG only) for the video
        std::string thumbnail_url;

        // Title for the result
        std::string title;

        // Optional. Caption of the video to be sent, 0-1024 characters after entities parsing
        std::string caption;

        // Optional. Mode for parsing entities in the video caption. See formatting options for more details.
        std::string parse_mode;

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities;

        // Optional. Pass True, if the caption must be shown above the message media
        bool show_caption_above_media = false;

        // Optional. Video width
        int64_t video_width = 0;

        // Optional. Video height
        int64_t video_height = 0;

        // Optional. Video duration in seconds
        int64_t video_duration = 0;

        // Optional. Short description of the result
        std::string description;

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup;

        // Optional. Content of the message to be sent instead of the video. This field is required if InlineQueryResultVideo is used to send an HTML-page as a result (e.g., a YouTube video).
        InputMessageContent::Ptr input_message_content;
    };
    void to_json(json& j, const InlineQueryResultVideo& value);
    void from_json(const json& j, InlineQueryResultVideo& value);
}
