// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/MessageEntity.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a link to a file. By default, this file will be sent by the user with an optional caption. Alternatively, you can use input_message_content to send a message with the specified content instead of the file. Currently, only .PDF and .ZIP files can be sent using this method.
     *
     * @param type Type of the result, must be document
     * @param id Unique identifier for this result, 1-64 bytes
     * @param title Title for the result
     * @param document_url A valid URL for the file
     * @param mime_type MIME type of the content of the file, either “application/pdf” or “application/zip”
     * @param caption Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the document caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param description Optional. Short description of the result
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the file
     * @param thumbnail_url Optional. URL of the thumbnail (JPEG only) for the file
     * @param thumbnail_width Optional. Thumbnail width
     * @param thumbnail_height Optional. Thumbnail height
     */
    struct InlineQueryResultDocument : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultDocument> Ptr;
        typedef std::weak_ptr<InlineQueryResultDocument> WeakPtr;

        virtual ~InlineQueryResultDocument() = default;
        // Type of the result, must be document
        std::string type_ = "";

        // Unique identifier for this result, 1-64 bytes
        std::string id = "";

        // Title for the result
        std::string title = "";

        // A valid URL for the file
        std::string document_url = "";

        // MIME type of the content of the file, either “application/pdf” or “application/zip”
        std::string mime_type = "";

        // Optional. Caption of the document to be sent, 0-1024 characters after entities parsing
        std::string caption = "";

        // Optional. Mode for parsing entities in the document caption. See formatting options for more details.
        std::string parse_mode = "";

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities = std::vector<MessageEntity::Ptr>();

        // Optional. Short description of the result
        std::string description = "";

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;

        // Optional. Content of the message to be sent instead of the file
        InputMessageContent::Ptr input_message_content = nullptr;

        // Optional. URL of the thumbnail (JPEG only) for the file
        std::string thumbnail_url = "";

        // Optional. Thumbnail width
        std::int64_t thumbnail_width = 0;

        // Optional. Thumbnail height
        std::int64_t thumbnail_height = 0;
    };
    void to_json(json& j, const InlineQueryResultDocument& value);
    void from_json(const json& j, InlineQueryResultDocument& value);
}
