// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/MessageEntity.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a link to an MP3 audio file. By default, this audio file will be sent by the user. Alternatively, you can use input_message_content to send a message with the specified content instead of the audio.
     *
     * @param type Type of the result, must be audio
     * @param id Unique identifier for this result, 1-64 bytes
     * @param audio_url A valid URL for the audio file
     * @param title Title
     * @param caption Optional. Caption, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the audio caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param performer Optional. Performer
     * @param audio_duration Optional. Audio duration in seconds
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the audio
     */
    struct InlineQueryResultAudio : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultAudio> Ptr;
        typedef std::weak_ptr<InlineQueryResultAudio> WeakPtr;

        virtual ~InlineQueryResultAudio() = default;
        // Type of the result, must be audio
        std::string type_ = "";

        // Unique identifier for this result, 1-64 bytes
        std::string id = "";

        // A valid URL for the audio file
        std::string audio_url = "";

        // Title
        std::string title = "";

        // Optional. Caption, 0-1024 characters after entities parsing
        std::string caption = "";

        // Optional. Mode for parsing entities in the audio caption. See formatting options for more details.
        std::string parse_mode = "";

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities = std::vector<MessageEntity::Ptr>();

        // Optional. Performer
        std::string performer = "";

        // Optional. Audio duration in seconds
        std::int64_t audio_duration = 0;

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;

        // Optional. Content of the message to be sent instead of the audio
        InputMessageContent::Ptr input_message_content = nullptr;
    };
    void to_json(json& j, const InlineQueryResultAudio& value);
    void from_json(const json& j, InlineQueryResultAudio& value);
}
