// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a venue. By default, the venue will be sent by the user. Alternatively, you can use input_message_content to send a message with the specified content instead of the venue.
     *
     * @param type Type of the result, must be venue
     * @param id Unique identifier for this result, 1-64 Bytes
     * @param latitude Latitude of the venue location in degrees
     * @param longitude Longitude of the venue location in degrees
     * @param title Title of the venue
     * @param address Address of the venue
     * @param foursquare_id Optional. Foursquare identifier of the venue if known
     * @param foursquare_type Optional. Foursquare type of the venue, if known. (For example, “arts_entertainment/default”, “arts_entertainment/aquarium” or “food/icecream”.)
     * @param google_place_id Optional. Google Places identifier of the venue
     * @param google_place_type Optional. Google Places type of the venue. (See supported types.)
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the venue
     * @param thumbnail_url Optional. Url of the thumbnail for the result
     * @param thumbnail_width Optional. Thumbnail width
     * @param thumbnail_height Optional. Thumbnail height
     */
    struct InlineQueryResultVenue : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultVenue> Ptr;
        typedef std::weak_ptr<InlineQueryResultVenue> WeakPtr;

        virtual ~InlineQueryResultVenue() = default;
        // Type of the result, must be venue
        std::string type_ = "";

        // Unique identifier for this result, 1-64 Bytes
        std::string id = "";

        // Latitude of the venue location in degrees
        double latitude = 0.0;

        // Longitude of the venue location in degrees
        double longitude = 0.0;

        // Title of the venue
        std::string title = "";

        // Address of the venue
        std::string address = "";

        // Optional. Foursquare identifier of the venue if known
        std::string foursquare_id = "";

        // Optional. Foursquare type of the venue, if known. (For example, “arts_entertainment/default”, “arts_entertainment/aquarium” or “food/icecream”.)
        std::string foursquare_type = "";

        // Optional. Google Places identifier of the venue
        std::string google_place_id = "";

        // Optional. Google Places type of the venue. (See supported types.)
        std::string google_place_type = "";

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup = nullptr;

        // Optional. Content of the message to be sent instead of the venue
        InputMessageContent::Ptr input_message_content = nullptr;

        // Optional. Url of the thumbnail for the result
        std::string thumbnail_url = "";

        // Optional. Thumbnail width
        std::int64_t thumbnail_width = 0;

        // Optional. Thumbnail height
        std::int64_t thumbnail_height = 0;
    };
    void to_json(json& j, const InlineQueryResultVenue& value);
    void from_json(const json& j, InlineQueryResultVenue& value);
}
