// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineQueryResult.hpp"
#include "types/MessageEntity.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents a link to an animated GIF file stored on the Telegram servers. By default, this animated GIF file will be sent by the user with an optional caption. Alternatively, you can use input_message_content to send a message with specified content instead of the animation.
     *
     * @param type Type of the result, must be gif
     * @param id Unique identifier for this result, 1-64 bytes
     * @param gif_file_id A valid file identifier for the GIF file
     * @param title Optional. Title for the result
     * @param caption Optional. Caption of the GIF file to be sent, 0-1024 characters after entities parsing
     * @param parse_mode Optional. Mode for parsing entities in the caption. See formatting options for more details.
     * @param caption_entities Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param show_caption_above_media Optional. Pass True, if the caption must be shown above the message media
     * @param reply_markup Optional. Inline keyboard attached to the message
     * @param input_message_content Optional. Content of the message to be sent instead of the GIF animation
     */
    struct InlineQueryResultCachedGif : public InlineQueryResult {
        typedef std::shared_ptr<InlineQueryResultCachedGif> Ptr;
        typedef std::weak_ptr<InlineQueryResultCachedGif> WeakPtr;

        virtual ~InlineQueryResultCachedGif() = default;
        // Type of the result, must be gif
        std::string type_;

        // Unique identifier for this result, 1-64 bytes
        std::string id;

        // A valid file identifier for the GIF file
        std::string gif_file_id;

        // Optional. Title for the result
        std::string title;

        // Optional. Caption of the GIF file to be sent, 0-1024 characters after entities parsing
        std::string caption;

        // Optional. Mode for parsing entities in the caption. See formatting options for more details.
        std::string parse_mode;

        // Optional. List of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities;

        // Optional. Pass True, if the caption must be shown above the message media
        bool show_caption_above_media = false;

        // Optional. Inline keyboard attached to the message
        InlineKeyboardMarkup::Ptr reply_markup;

        // Optional. Content of the message to be sent instead of the GIF animation
        InputMessageContent::Ptr input_message_content;
    };
    void to_json(json& j, const InlineQueryResultCachedGif& value);
    void from_json(const json& j, InlineQueryResultCachedGif& value);
}
