// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputMessageContent.hpp"
#include "types/MessageEntity.hpp"
#include "types/LinkPreviewOptions.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents the content of a text message to be sent as the result of an inline query.
     *
     * @param message_text Text of the message to be sent, 1-4096 characters
     * @param parse_mode Optional. Mode for parsing entities in the message text. See formatting options for more details.
     * @param entities Optional. List of special entities that appear in message text, which can be specified instead of parse_mode
     * @param link_preview_options Optional. Link preview generation options for the message
     */
    struct InputTextMessageContent : public InputMessageContent {
        typedef std::shared_ptr<InputTextMessageContent> Ptr;
        typedef std::weak_ptr<InputTextMessageContent> WeakPtr;

        virtual ~InputTextMessageContent() = default;
        // Text of the message to be sent, 1-4096 characters
        std::string message_text = "";

        // Optional. Mode for parsing entities in the message text. See formatting options for more details.
        std::string parse_mode = "";

        // Optional. List of special entities that appear in message text, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> entities = std::vector<MessageEntity::Ptr>();

        // Optional. Link preview generation options for the message
        LinkPreviewOptions::Ptr link_preview_options = nullptr;
    };
    void to_json(json& j, const InputTextMessageContent& value);
    void from_json(const json& j, InputTextMessageContent& value);
}
