// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputMessageContent.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents the content of a contact message to be sent as the result of an inline query.
     *
     * @param phone_number Contact's phone number
     * @param first_name Contact's first name
     * @param last_name Optional. Contact's last name
     * @param vcard Optional. Additional data about the contact in the form of a vCard, 0-2048 bytes
     */
    struct InputContactMessageContent : public InputMessageContent {
        typedef std::shared_ptr<InputContactMessageContent> Ptr;
        typedef std::weak_ptr<InputContactMessageContent> WeakPtr;

        virtual ~InputContactMessageContent() = default;
        // Contact's phone number
        std::string phone_number;

        // Contact's first name
        std::string first_name;

        // Optional. Contact's last name
        std::string last_name;

        // Optional. Additional data about the contact in the form of a vCard, 0-2048 bytes
        std::string vcard;
    };
    void to_json(json& j, const InputContactMessageContent& value);
    void from_json(const json& j, InputContactMessageContent& value);
}
