// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    struct InputPaidMedia : public TelegramModel {
        typedef std::shared_ptr<InputPaidMedia> Ptr;
        virtual ~InputPaidMedia() = default;
    };

    void to_json(json& j, const InputPaidMedia& value);
    void from_json(const json& j, InputPaidMedia& value);
}
