// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputPaidMedia.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The paid media to send is a photo.
     *
     * @param type Type of the media, must be photo
     * @param media File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name. More information on Sending Files »
     */
    struct InputPaidMediaPhoto : public InputPaidMedia {
        typedef std::shared_ptr<InputPaidMediaPhoto> Ptr;
        typedef std::weak_ptr<InputPaidMediaPhoto> WeakPtr;

        virtual ~InputPaidMediaPhoto() = default;
        // Type of the media, must be photo
        std::string type_;

        // File to send. Pass a file_id to send a file that exists on the Telegram servers (recommended), pass an HTTP URL for Telegram to get a file from the Internet, or pass “attach://<file_attach_name>” to upload a new one using multipart/form-data under <file_attach_name> name. More information on Sending Files »
        std::string media;
    };
    void to_json(json& j, const InputPaidMediaPhoto& value);
    void from_json(const json& j, InputPaidMediaPhoto& value);
}
