// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/ReactionType.hpp"
#include "types/Chat.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a change of a reaction on a message performed by a user.
     *
     * @param chat The chat containing the message the user reacted to
     * @param message_id Unique identifier of the message inside the chat
     * @param date Date of the change in Unix time
     * @param old_reaction Previous list of reaction types that were set by the user
     * @param new_reaction New list of reaction types that have been set by the user
     * @param user Optional. The user that changed the reaction, if the user isn't anonymous
     * @param actor_chat Optional. The chat on behalf of which the reaction was changed, if the user is anonymous
     */
    struct MessageReactionUpdated : public TelegramModel {
        typedef std::shared_ptr<MessageReactionUpdated> Ptr;
        typedef std::weak_ptr<MessageReactionUpdated> WeakPtr;

        virtual ~MessageReactionUpdated() = default;
        // The chat containing the message the user reacted to
        Chat::Ptr chat = nullptr;

        // Unique identifier of the message inside the chat
        std::int64_t message_id = 0;

        // Date of the change in Unix time
        std::int64_t date = 0;

        // Previous list of reaction types that were set by the user
        std::vector<ReactionType::Ptr> old_reaction = std::vector<ReactionType::Ptr>();

        // New list of reaction types that have been set by the user
        std::vector<ReactionType::Ptr> new_reaction = std::vector<ReactionType::Ptr>();

        // Optional. The user that changed the reaction, if the user isn't anonymous
        User::Ptr user = nullptr;

        // Optional. The chat on behalf of which the reaction was changed, if the user is anonymous
        Chat::Ptr actor_chat = nullptr;
    };
    void to_json(json& j, const MessageReactionUpdated& value);
    void from_json(const json& j, MessageReactionUpdated& value);
}
