// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/OwnedGift.hpp"
#include "types/UniqueGift.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a unique gift received and owned by a user or a chat.
     *
     * @param type Type of the gift, always “unique”
     * @param gift Information about the unique gift
     * @param send_date Date the gift was sent in Unix time
     * @param owned_gift_id Optional. Unique identifier of the received gift for the bot; for gifts received on behalf of business accounts only
     * @param sender_user Optional. Sender of the gift if it is a known user
     * @param is_saved Optional. True, if the gift is displayed on the account's profile page; for gifts received on behalf of business accounts only
     * @param can_be_transferred Optional. True, if the gift can be transferred to another owner; for gifts received on behalf of business accounts only
     * @param transfer_star_count Optional. Number of Telegram Stars that must be paid to transfer the gift; omitted if the bot cannot transfer the gift
     * @param next_transfer_date Optional. Point in time (Unix timestamp) when the gift can be transferred. If it is in the past, then the gift can be transferred now
     */
    struct OwnedGiftUnique : public OwnedGift {
        typedef std::shared_ptr<OwnedGiftUnique> Ptr;
        typedef std::weak_ptr<OwnedGiftUnique> WeakPtr;

        virtual ~OwnedGiftUnique() = default;
        // Type of the gift, always “unique”
        std::string type_ = "";

        // Information about the unique gift
        UniqueGift::Ptr gift = nullptr;

        // Date the gift was sent in Unix time
        std::int64_t send_date = 0;

        // Optional. Unique identifier of the received gift for the bot; for gifts received on behalf of business accounts only
        std::string owned_gift_id = "";

        // Optional. Sender of the gift if it is a known user
        User::Ptr sender_user = nullptr;

        // Optional. True, if the gift is displayed on the account's profile page; for gifts received on behalf of business accounts only
        bool is_saved = false;

        // Optional. True, if the gift can be transferred to another owner; for gifts received on behalf of business accounts only
        bool can_be_transferred = false;

        // Optional. Number of Telegram Stars that must be paid to transfer the gift; omitted if the bot cannot transfer the gift
        std::int64_t transfer_star_count = 0;

        // Optional. Point in time (Unix timestamp) when the gift can be transferred. If it is in the past, then the gift can be transferred now
        std::int64_t next_transfer_date = 0;
    };
    void to_json(json& j, const OwnedGiftUnique& value);
    void from_json(const json& j, OwnedGiftUnique& value);
}
