// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/OwnedGift.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Contains the list of gifts received and owned by a user or a chat.
     *
     * @param total_count The total number of gifts owned by the user or the chat
     * @param gifts The list of gifts
     * @param next_offset Optional. Offset for the next request. If empty, then there are no more results
     */
    struct OwnedGifts : public TelegramModel {
        typedef std::shared_ptr<OwnedGifts> Ptr;
        typedef std::weak_ptr<OwnedGifts> WeakPtr;

        virtual ~OwnedGifts() = default;
        // The total number of gifts owned by the user or the chat
        std::int64_t total_count = 0;

        // The list of gifts
        std::vector<OwnedGift::Ptr> gifts = std::vector<OwnedGift::Ptr>();

        // Optional. Offset for the next request. If empty, then there are no more results
        std::string next_offset = "";
    };
    void to_json(json& j, const OwnedGifts& value);
    void from_json(const json& j, OwnedGifts& value);
}
