// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/PaidMedia.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The paid media isn't available before the payment.
     *
     * @param type Type of the paid media, always “preview”
     * @param width Optional. Media width as defined by the sender
     * @param height Optional. Media height as defined by the sender
     * @param duration Optional. Duration of the media in seconds as defined by the sender
     */
    struct PaidMediaPreview : public PaidMedia {
        typedef std::shared_ptr<PaidMediaPreview> Ptr;
        typedef std::weak_ptr<PaidMediaPreview> WeakPtr;

        virtual ~PaidMediaPreview() = default;
        // Type of the paid media, always “preview”
        std::string type_;

        // Optional. Media width as defined by the sender
        int64_t width = 0;

        // Optional. Media height as defined by the sender
        int64_t height = 0;

        // Optional. Duration of the media in seconds as defined by the sender
        int64_t duration = 0;
    };
    void to_json(json& j, const PaidMediaPreview& value);
    void from_json(const json& j, PaidMediaPreview& value);
}
