// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/PaidMedia.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains information about a paid media purchase.
     *
     * @param from User who purchased the media
     * @param paid_media_payload Bot-specified paid media payload
     */
    struct PaidMediaPurchased : public PaidMedia {
        typedef std::shared_ptr<PaidMediaPurchased> Ptr;
        typedef std::weak_ptr<PaidMediaPurchased> WeakPtr;

        virtual ~PaidMediaPurchased() = default;
        // User who purchased the media
        User::Ptr from = nullptr;

        // Bot-specified paid media payload
        std::string paid_media_payload = "";
    };
    void to_json(json& j, const PaidMediaPurchased& value);
    void from_json(const json& j, PaidMediaPurchased& value);
}
