// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/PassportElementError.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents an issue in one of the data fields that was provided by the user. The error is considered resolved when the field's value changes.
     *
     * @param source Error source, must be data
     * @param type The section of the user's Telegram Passport which has the error, one of “personal_details”, “passport”, “driver_license”, “identity_card”, “internal_passport”, “address”
     * @param field_name Name of the data field which has the error
     * @param data_hash Base64-encoded data hash
     * @param message Error message
     */
    struct PassportElementErrorDataField : public PassportElementError {
        typedef std::shared_ptr<PassportElementErrorDataField> Ptr;
        typedef std::weak_ptr<PassportElementErrorDataField> WeakPtr;

        virtual ~PassportElementErrorDataField() = default;
        // Error source, must be data
        std::string source = "";

        // The section of the user's Telegram Passport which has the error, one of “personal_details”, “passport”, “driver_license”, “identity_card”, “internal_passport”, “address”
        std::string type_ = "";

        // Name of the data field which has the error
        std::string field_name = "";

        // Base64-encoded data hash
        std::string data_hash = "";

        // Error message
        std::string message = "";
    };
    void to_json(json& j, const PassportElementErrorDataField& value);
    void from_json(const json& j, PassportElementErrorDataField& value);
}
