// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/PassportElementError.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents an issue in an unspecified place. The error is considered resolved when new data is added.
     *
     * @param source Error source, must be unspecified
     * @param type Type of element of the user's Telegram Passport which has the issue
     * @param element_hash Base64-encoded element hash
     * @param message Error message
     */
    struct PassportElementErrorUnspecified : public PassportElementError {
        typedef std::shared_ptr<PassportElementErrorUnspecified> Ptr;
        typedef std::weak_ptr<PassportElementErrorUnspecified> WeakPtr;

        virtual ~PassportElementErrorUnspecified() = default;
        // Error source, must be unspecified
        std::string source = "";

        // Type of element of the user's Telegram Passport which has the issue
        std::string type_ = "";

        // Base64-encoded element hash
        std::string element_hash = "";

        // Error message
        std::string message = "";
    };
    void to_json(json& j, const PassportElementErrorUnspecified& value);
    void from_json(const json& j, PassportElementErrorUnspecified& value);
}
