// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a file uploaded to Telegram Passport. Currently all Telegram Passport files are in JPEG format when decrypted and don't exceed 10MB.
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param file_size File size in bytes
     * @param file_date Unix time when the file was uploaded
     */
    struct PassportFile : public TelegramModel {
        typedef std::shared_ptr<PassportFile> Ptr;
        typedef std::weak_ptr<PassportFile> WeakPtr;

        virtual ~PassportFile() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id = "";

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id = "";

        // File size in bytes
        std::int64_t file_size = 0;

        // Unix time when the file was uploaded
        std::int64_t file_date = 0;
    };
    void to_json(json& j, const PassportFile& value);
    void from_json(const json& j, PassportFile& value);
}
