// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/PassportElementError.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Represents an issue with the selfie with a document. The error is considered resolved when the file with the selfie changes.
     *
     * @param source Error source, must be selfie
     * @param type The section of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”
     * @param file_hash Base64-encoded hash of the file with the selfie
     * @param message Error message
     */
    struct PassportElementErrorSelfie : public PassportElementError {
        typedef std::shared_ptr<PassportElementErrorSelfie> Ptr;
        typedef std::weak_ptr<PassportElementErrorSelfie> WeakPtr;

        virtual ~PassportElementErrorSelfie() = default;
        // Error source, must be selfie
        std::string source = "";

        // The section of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”
        std::string type_ = "";

        // Base64-encoded hash of the file with the selfie
        std::string file_hash = "";

        // Error message
        std::string message = "";
    };
    void to_json(json& j, const PassportElementErrorSelfie& value);
    void from_json(const json& j, PassportElementErrorSelfie& value);
}
