// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ReactionType.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The reaction is based on an emoji.
     *
     * @param type Type of the reaction, always “emoji”
     * @param emoji Reaction emoji. Currently, it can be one of "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
     */
    struct ReactionTypeEmoji : public ReactionType {
        typedef std::shared_ptr<ReactionTypeEmoji> Ptr;
        typedef std::weak_ptr<ReactionTypeEmoji> WeakPtr;

        virtual ~ReactionTypeEmoji() = default;
        // Type of the reaction, always “emoji”
        std::string type_ = "";

        // Reaction emoji. Currently, it can be one of "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""
        std::string emoji = "";
    };
    void to_json(json& j, const ReactionTypeEmoji& value);
    void from_json(const json& j, ReactionTypeEmoji& value);
}
