// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/ReactionType.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * The reaction is paid.
     *
     * @param type Type of the reaction, always “paid”
     */
    struct ReactionTypePaid : public ReactionType {
        typedef std::shared_ptr<ReactionTypePaid> Ptr;
        typedef std::weak_ptr<ReactionTypePaid> WeakPtr;

        virtual ~ReactionTypePaid() = default;
        // Type of the reaction, always “paid”
        std::string type_ = "";
    };
    void to_json(json& j, const ReactionTypePaid& value);
    void from_json(const json& j, ReactionTypePaid& value);
}
