// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object contains basic information about a refunded payment.
     *
     * @param currency Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars. Currently, always “XTR”
     * @param total_amount Total refunded price in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45, total_amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
     * @param invoice_payload Bot-specified invoice payload
     * @param telegram_payment_charge_id Telegram payment identifier
     * @param provider_payment_charge_id Optional. Provider payment identifier
     */
    struct RefundedPayment : public TelegramModel {
        typedef std::shared_ptr<RefundedPayment> Ptr;
        typedef std::weak_ptr<RefundedPayment> WeakPtr;

        virtual ~RefundedPayment() = default;
        // Three-letter ISO 4217 currency code, or “XTR” for payments in Telegram Stars. Currently, always “XTR”
        std::string currency;

        // Total refunded price in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45, total_amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
        int64_t total_amount = 0;

        // Bot-specified invoice payload
        std::string invoice_payload;

        // Telegram payment identifier
        std::string telegram_payment_charge_id;

        // Optional. Provider payment identifier
        std::string provider_payment_charge_id;
    };
    void to_json(json& j, const RefundedPayment& value);
    void from_json(const json& j, RefundedPayment& value);
}
