// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/KeyboardOption.hpp"
#include "types/KeyboardButton.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a custom keyboard with reply options (see Introduction to bots for details and examples). Not supported in channels and for messages sent on behalf of a Telegram Business account.
     *
     * @param keyboard Array of button rows, each represented by an Array of KeyboardButton objects
     * @param is_persistent Optional. Requests clients to always show the keyboard when the regular keyboard is hidden. Defaults to false, in which case the custom keyboard can be hidden and opened with a keyboard icon.
     * @param resize_keyboard Optional. Requests clients to resize the keyboard vertically for optimal fit (e.g., make the keyboard smaller if there are just two rows of buttons). Defaults to false, in which case the custom keyboard is always of the same height as the app's standard keyboard.
     * @param one_time_keyboard Optional. Requests clients to hide the keyboard as soon as it's been used. The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat - the user can press a special button in the input field to see the custom keyboard again. Defaults to false.
     * @param input_field_placeholder Optional. The placeholder to be shown in the input field when the keyboard is active; 1-64 characters
     * @param selective Optional. Use this parameter if you want to show the keyboard to specific users only. Targets: 1) users that are @mentioned in the text of the Message object; 2) if the bot's message is a reply to a message in the same chat and forum topic, sender of the original message.Example: A user requests to change the bot's language, bot replies to the request with a keyboard to select the new language. Other users in the group don't see the keyboard.
     */
    struct ReplyKeyboardMarkup : public KeyboardOption {
        typedef std::shared_ptr<ReplyKeyboardMarkup> Ptr;
        typedef std::weak_ptr<ReplyKeyboardMarkup> WeakPtr;

        virtual ~ReplyKeyboardMarkup() = default;
        // Array of button rows, each represented by an Array of KeyboardButton objects
        std::vector<std::vector<KeyboardButton::Ptr>> keyboard = std::vector<std::vector<KeyboardButton::Ptr>>();

        // Optional. Requests clients to always show the keyboard when the regular keyboard is hidden. Defaults to false, in which case the custom keyboard can be hidden and opened with a keyboard icon.
        bool is_persistent = false;

        // Optional. Requests clients to resize the keyboard vertically for optimal fit (e.g., make the keyboard smaller if there are just two rows of buttons). Defaults to false, in which case the custom keyboard is always of the same height as the app's standard keyboard.
        bool resize_keyboard = false;

        // Optional. Requests clients to hide the keyboard as soon as it's been used. The keyboard will still be available, but clients will automatically display the usual letter-keyboard in the chat - the user can press a special button in the input field to see the custom keyboard again. Defaults to false.
        bool one_time_keyboard = false;

        // Optional. The placeholder to be shown in the input field when the keyboard is active; 1-64 characters
        std::string input_field_placeholder = "";

        // Optional. Use this parameter if you want to show the keyboard to specific users only. Targets: 1) users that are @mentioned in the text of the Message object; 2) if the bot's message is a reply to a message in the same chat and forum topic, sender of the original message.Example: A user requests to change the bot's language, bot replies to the request with a keyboard to select the new language. Other users in the group don't see the keyboard.
        bool selective = false;
    };
    void to_json(json& j, const ReplyKeyboardMarkup& value);
    void from_json(const json& j, ReplyKeyboardMarkup& value);
}
