// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/StoryAreaType.hpp"
#include "types/ReactionType.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a story area pointing to a suggested reaction. Currently, a story can have up to 5 suggested reaction areas.
     *
     * @param type Type of the area, always “suggested_reaction”
     * @param reaction_type Type of the reaction
     * @param is_dark Optional. Pass True if the reaction area has a dark background
     * @param is_flipped Optional. Pass True if reaction area corner is flipped
     */
    struct StoryAreaTypeSuggestedReaction : public StoryAreaType {
        typedef std::shared_ptr<StoryAreaTypeSuggestedReaction> Ptr;
        typedef std::weak_ptr<StoryAreaTypeSuggestedReaction> WeakPtr;

        virtual ~StoryAreaTypeSuggestedReaction() = default;
        // Type of the area, always “suggested_reaction”
        std::string type_ = "";

        // Type of the reaction
        ReactionType::Ptr reaction_type = nullptr;

        // Optional. Pass True if the reaction area has a dark background
        bool is_dark = false;

        // Optional. Pass True if reaction area corner is flipped
        bool is_flipped = false;
    };
    void to_json(json& j, const StoryAreaTypeSuggestedReaction& value);
    void from_json(const json& j, StoryAreaTypeSuggestedReaction& value);
}
