// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/SuggestedPostPrice.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Contains information about a suggested post.
     *
     * @param state State of the suggested post. Currently, it can be one of “pending”, “approved”, “declined”.
     * @param price Optional. Proposed price of the post. If the field is omitted, then the post is unpaid.
     * @param send_date Optional. Proposed send date of the post. If the field is omitted, then the post can be published at any time within 30 days at the sole discretion of the user or administrator who approves it.
     */
    struct SuggestedPostInfo : public TelegramModel {
        typedef std::shared_ptr<SuggestedPostInfo> Ptr;
        typedef std::weak_ptr<SuggestedPostInfo> WeakPtr;

        virtual ~SuggestedPostInfo() = default;
        // State of the suggested post. Currently, it can be one of “pending”, “approved”, “declined”.
        std::string state = "";

        // Optional. Proposed price of the post. If the field is omitted, then the post is unpaid.
        SuggestedPostPrice::Ptr price = nullptr;

        // Optional. Proposed send date of the post. If the field is omitted, then the post can be published at any time within 30 days at the sole discretion of the user or administrator who approves it.
        std::int64_t send_date = 0;
    };
    void to_json(json& j, const SuggestedPostInfo& value);
    void from_json(const json& j, SuggestedPostInfo& value);
}
