// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Message.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a service message about the rejection of a suggested post.
     *
     * @param suggested_post_message Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
     * @param comment Optional. Comment with which the post was declined
     */
    struct SuggestedPostDeclined : public TelegramModel {
        typedef std::shared_ptr<SuggestedPostDeclined> Ptr;
        typedef std::weak_ptr<SuggestedPostDeclined> WeakPtr;

        virtual ~SuggestedPostDeclined() = default;
        // Optional. Message containing the suggested post. Note that the Message object in this field will not contain the reply_to_message field even if it itself is a reply.
        Message::Ptr suggested_post_message = nullptr;

        // Optional. Comment with which the post was declined
        std::string comment = "";
    };
    void to_json(json& j, const SuggestedPostDeclined& value);
    void from_json(const json& j, SuggestedPostDeclined& value);
}
