// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TransactionPartner.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes the affiliate program that issued the affiliate commission received via this transaction.
     *
     * @param type Type of the transaction partner, always “affiliate_program”
     * @param commission_per_mille The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the affiliate program sponsor from referred users
     * @param sponsor_user Optional. Information about the bot that sponsored the affiliate program
     */
    struct TransactionPartnerAffiliateProgram : public TransactionPartner {
        typedef std::shared_ptr<TransactionPartnerAffiliateProgram> Ptr;
        typedef std::weak_ptr<TransactionPartnerAffiliateProgram> WeakPtr;

        virtual ~TransactionPartnerAffiliateProgram() = default;
        // Type of the transaction partner, always “affiliate_program”
        std::string type_;

        // The number of Telegram Stars received by the bot for each 1000 Telegram Stars received by the affiliate program sponsor from referred users
        int64_t commission_per_mille = 0;

        // Optional. Information about the bot that sponsored the affiliate program
        User::Ptr sponsor_user;
    };
    void to_json(json& j, const TransactionPartnerAffiliateProgram& value);
    void from_json(const json& j, TransactionPartnerAffiliateProgram& value);
}
