// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TransactionPartner.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Describes a transaction with payment for paid broadcasting.
     *
     * @param type Type of the transaction partner, always “telegram_api”
     * @param request_count The number of successful requests that exceeded regular limits and were therefore billed
     */
    struct TransactionPartnerTelegramApi : public TransactionPartner {
        typedef std::shared_ptr<TransactionPartnerTelegramApi> Ptr;
        typedef std::weak_ptr<TransactionPartnerTelegramApi> WeakPtr;

        virtual ~TransactionPartnerTelegramApi() = default;
        // Type of the transaction partner, always “telegram_api”
        std::string type_ = "";

        // The number of successful requests that exceeded regular limits and were therefore billed
        std::int64_t request_count = 0;
    };
    void to_json(json& j, const TransactionPartnerTelegramApi& value);
    void from_json(const json& j, TransactionPartnerTelegramApi& value);
}
