// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/UniqueGiftModel.hpp"
#include "types/UniqueGiftSymbol.hpp"
#include "types/UniqueGiftBackdrop.hpp"
#include "types/UniqueGiftColors.hpp"
#include "types/Chat.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object describes a unique gift that was upgraded from a regular gift.
     *
     * @param gift_id Identifier of the regular gift from which the gift was upgraded
     * @param base_name Human-readable name of the regular gift from which this unique gift was upgraded
     * @param name Unique name of the gift. This name can be used in https://t.me/nft/... links and story areas
     * @param number Unique number of the upgraded gift among gifts upgraded from the same regular gift
     * @param model Model of the gift
     * @param symbol Symbol of the gift
     * @param backdrop Backdrop of the gift
     * @param is_premium Optional. True, if the original regular gift was exclusively purchaseable by Telegram Premium subscribers
     * @param is_burned Optional. True, if the gift was used to craft another gift and isn't available anymore
     * @param is_from_blockchain Optional. True, if the gift is assigned from the TON blockchain and can't be resold or transferred in Telegram
     * @param colors Optional. The color scheme that can be used by the gift's owner for the chat's name, replies to messages and link previews; for business account gifts and gifts that are currently on sale only
     * @param publisher_chat Optional. Information about the chat that published the gift
     */
    struct UniqueGift : public TelegramModel {
        typedef std::shared_ptr<UniqueGift> Ptr;
        typedef std::weak_ptr<UniqueGift> WeakPtr;

        virtual ~UniqueGift() = default;
        // Identifier of the regular gift from which the gift was upgraded
        std::string gift_id;

        // Human-readable name of the regular gift from which this unique gift was upgraded
        std::string base_name;

        // Unique name of the gift. This name can be used in https://t.me/nft/... links and story areas
        std::string name;

        // Unique number of the upgraded gift among gifts upgraded from the same regular gift
        int64_t number = 0;

        // Model of the gift
        UniqueGiftModel::Ptr model;

        // Symbol of the gift
        UniqueGiftSymbol::Ptr symbol;

        // Backdrop of the gift
        UniqueGiftBackdrop::Ptr backdrop;

        // Optional. True, if the original regular gift was exclusively purchaseable by Telegram Premium subscribers
        bool is_premium = false;

        // Optional. True, if the gift was used to craft another gift and isn't available anymore
        bool is_burned = false;

        // Optional. True, if the gift is assigned from the TON blockchain and can't be resold or transferred in Telegram
        bool is_from_blockchain = false;

        // Optional. The color scheme that can be used by the gift's owner for the chat's name, replies to messages and link previews; for business account gifts and gifts that are currently on sale only
        UniqueGiftColors::Ptr colors;

        // Optional. Information about the chat that published the gift
        Chat::Ptr publisher_chat;
    };
    void to_json(json& j, const UniqueGift& value);
    void from_json(const json& j, UniqueGift& value);
}
