// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Sticker.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object describes the model of a unique gift.
     *
     * @param name Name of the model
     * @param sticker The sticker that represents the unique gift
     * @param rarity_per_mille The number of unique gifts that receive this model for every 1000 gift upgrades. Always 0 for crafted gifts.
     * @param rarity Optional. Rarity of the model if it is a crafted model. Currently, can be “uncommon”, “rare”, “epic”, or “legendary”.
     */
    struct UniqueGiftModel : public TelegramModel {
        typedef std::shared_ptr<UniqueGiftModel> Ptr;
        typedef std::weak_ptr<UniqueGiftModel> WeakPtr;

        virtual ~UniqueGiftModel() = default;
        // Name of the model
        std::string name = "";

        // The sticker that represents the unique gift
        Sticker::Ptr sticker = nullptr;

        // The number of unique gifts that receive this model for every 1000 gift upgrades. Always 0 for crafted gifts.
        std::int64_t rarity_per_mille = 0;

        // Optional. Rarity of the model if it is a crafted model. Currently, can be “uncommon”, “rare”, “epic”, or “legendary”.
        std::string rarity = "";
    };
    void to_json(json& j, const UniqueGiftModel& value);
    void from_json(const json& j, UniqueGiftModel& value);
}
