// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Message.hpp"
#include "types/BusinessConnection.hpp"
#include "types/BusinessMessagesDeleted.hpp"
#include "types/MessageReactionUpdated.hpp"
#include "types/MessageReactionCountUpdated.hpp"
#include "types/InlineQuery.hpp"
#include "types/ChosenInlineResult.hpp"
#include "types/CallbackQuery.hpp"
#include "types/ShippingQuery.hpp"
#include "types/PreCheckoutQuery.hpp"
#include "types/PaidMediaPurchased.hpp"
#include "types/Poll.hpp"
#include "types/PollAnswer.hpp"
#include "types/ChatMemberUpdated.hpp"
#include "types/ChatJoinRequest.hpp"
#include "types/ChatBoostUpdated.hpp"
#include "types/ChatBoostRemoved.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents an incoming update.At most one of the optional parameters can be present in any given update.
     *
     * @param update_id The update's unique identifier. Update identifiers start from a certain positive number and increase sequentially. This identifier becomes especially handy if you're using webhooks, since it allows you to ignore repeated updates or to restore the correct update sequence, should they get out of order. If there are no new updates for at least a week, then identifier of the next update will be chosen randomly instead of sequentially.
     * @param message Optional. New incoming message of any kind - text, photo, sticker, etc.
     * @param edited_message Optional. New version of a message that is known to the bot and was edited. This update may at times be triggered by changes to message fields that are either unavailable or not actively used by your bot.
     * @param channel_post Optional. New incoming channel post of any kind - text, photo, sticker, etc.
     * @param edited_channel_post Optional. New version of a channel post that is known to the bot and was edited. This update may at times be triggered by changes to message fields that are either unavailable or not actively used by your bot.
     * @param business_connection Optional. The bot was connected to or disconnected from a business account, or a user edited an existing connection with the bot
     * @param business_message Optional. New message from a connected business account
     * @param edited_business_message Optional. New version of a message from a connected business account
     * @param deleted_business_messages Optional. Messages were deleted from a connected business account
     * @param message_reaction Optional. A reaction to a message was changed by a user. The bot must be an administrator in the chat and must explicitly specify "message_reaction" in the list of allowed_updates to receive these updates. The update isn't received for reactions set by bots.
     * @param message_reaction_count Optional. Reactions to a message with anonymous reactions were changed. The bot must be an administrator in the chat and must explicitly specify "message_reaction_count" in the list of allowed_updates to receive these updates. The updates are grouped and can be sent with delay up to a few minutes.
     * @param inline_query Optional. New incoming inline query
     * @param chosen_inline_result Optional. The result of an inline query that was chosen by a user and sent to their chat partner. Please see our documentation on the feedback collecting for details on how to enable these updates for your bot.
     * @param callback_query Optional. New incoming callback query
     * @param shipping_query Optional. New incoming shipping query. Only for invoices with flexible price
     * @param pre_checkout_query Optional. New incoming pre-checkout query. Contains full information about checkout
     * @param purchased_paid_media Optional. A user purchased paid media with a non-empty payload sent by the bot in a non-channel chat
     * @param poll Optional. New poll state. Bots receive only updates about manually stopped polls and polls, which are sent by the bot
     * @param poll_answer Optional. A user changed their answer in a non-anonymous poll. Bots receive new votes only in polls that were sent by the bot itself.
     * @param my_chat_member Optional. The bot's chat member status was updated in a chat. For private chats, this update is received only when the bot is blocked or unblocked by the user.
     * @param chat_member Optional. A chat member's status was updated in a chat. The bot must be an administrator in the chat and must explicitly specify "chat_member" in the list of allowed_updates to receive these updates.
     * @param chat_join_request Optional. A request to join the chat has been sent. The bot must have the can_invite_users administrator right in the chat to receive these updates.
     * @param chat_boost Optional. A chat boost was added or changed. The bot must be an administrator in the chat to receive these updates.
     * @param removed_chat_boost Optional. A boost was removed from a chat. The bot must be an administrator in the chat to receive these updates.
     */
    struct Update : public TelegramModel {
        typedef std::shared_ptr<Update> Ptr;
        typedef std::weak_ptr<Update> WeakPtr;

        virtual ~Update() = default;
        // The update's unique identifier. Update identifiers start from a certain positive number and increase sequentially. This identifier becomes especially handy if you're using webhooks, since it allows you to ignore repeated updates or to restore the correct update sequence, should they get out of order. If there are no new updates for at least a week, then identifier of the next update will be chosen randomly instead of sequentially.
        std::int64_t update_id = 0;

        // Optional. New incoming message of any kind - text, photo, sticker, etc.
        Message::Ptr message = nullptr;

        // Optional. New version of a message that is known to the bot and was edited. This update may at times be triggered by changes to message fields that are either unavailable or not actively used by your bot.
        Message::Ptr edited_message = nullptr;

        // Optional. New incoming channel post of any kind - text, photo, sticker, etc.
        Message::Ptr channel_post = nullptr;

        // Optional. New version of a channel post that is known to the bot and was edited. This update may at times be triggered by changes to message fields that are either unavailable or not actively used by your bot.
        Message::Ptr edited_channel_post = nullptr;

        // Optional. The bot was connected to or disconnected from a business account, or a user edited an existing connection with the bot
        BusinessConnection::Ptr business_connection = nullptr;

        // Optional. New message from a connected business account
        Message::Ptr business_message = nullptr;

        // Optional. New version of a message from a connected business account
        Message::Ptr edited_business_message = nullptr;

        // Optional. Messages were deleted from a connected business account
        BusinessMessagesDeleted::Ptr deleted_business_messages = nullptr;

        // Optional. A reaction to a message was changed by a user. The bot must be an administrator in the chat and must explicitly specify "message_reaction" in the list of allowed_updates to receive these updates. The update isn't received for reactions set by bots.
        MessageReactionUpdated::Ptr message_reaction = nullptr;

        // Optional. Reactions to a message with anonymous reactions were changed. The bot must be an administrator in the chat and must explicitly specify "message_reaction_count" in the list of allowed_updates to receive these updates. The updates are grouped and can be sent with delay up to a few minutes.
        MessageReactionCountUpdated::Ptr message_reaction_count = nullptr;

        // Optional. New incoming inline query
        InlineQuery::Ptr inline_query = nullptr;

        // Optional. The result of an inline query that was chosen by a user and sent to their chat partner. Please see our documentation on the feedback collecting for details on how to enable these updates for your bot.
        ChosenInlineResult::Ptr chosen_inline_result = nullptr;

        // Optional. New incoming callback query
        CallbackQuery::Ptr callback_query = nullptr;

        // Optional. New incoming shipping query. Only for invoices with flexible price
        ShippingQuery::Ptr shipping_query = nullptr;

        // Optional. New incoming pre-checkout query. Contains full information about checkout
        PreCheckoutQuery::Ptr pre_checkout_query = nullptr;

        // Optional. A user purchased paid media with a non-empty payload sent by the bot in a non-channel chat
        PaidMediaPurchased::Ptr purchased_paid_media = nullptr;

        // Optional. New poll state. Bots receive only updates about manually stopped polls and polls, which are sent by the bot
        Poll::Ptr poll = nullptr;

        // Optional. A user changed their answer in a non-anonymous poll. Bots receive new votes only in polls that were sent by the bot itself.
        PollAnswer::Ptr poll_answer = nullptr;

        // Optional. The bot's chat member status was updated in a chat. For private chats, this update is received only when the bot is blocked or unblocked by the user.
        ChatMemberUpdated::Ptr my_chat_member = nullptr;

        // Optional. A chat member's status was updated in a chat. The bot must be an administrator in the chat and must explicitly specify "chat_member" in the list of allowed_updates to receive these updates.
        ChatMemberUpdated::Ptr chat_member = nullptr;

        // Optional. A request to join the chat has been sent. The bot must have the can_invite_users administrator right in the chat to receive these updates.
        ChatJoinRequest::Ptr chat_join_request = nullptr;

        // Optional. A chat boost was added or changed. The bot must be an administrator in the chat to receive these updates.
        ChatBoostUpdated::Ptr chat_boost = nullptr;

        // Optional. A boost was removed from a chat. The bot must be an administrator in the chat to receive these updates.
        ChatBoostRemoved::Ptr removed_chat_boost = nullptr;
    };
    void to_json(json& j, const Update& value);
    void from_json(const json& j, Update& value);
}
