// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a Telegram user or bot.
     *
     * @param id Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
     * @param is_bot True, if this user is a bot
     * @param first_name User's or bot's first name
     * @param last_name Optional. User's or bot's last name
     * @param username Optional. User's or bot's username
     * @param language_code Optional. IETF language tag of the user's language
     * @param is_premium Optional. True, if this user is a Telegram Premium user
     * @param added_to_attachment_menu Optional. True, if this user added the bot to the attachment menu
     * @param can_join_groups Optional. True, if the bot can be invited to groups. Returned only in getMe.
     * @param can_read_all_group_messages Optional. True, if privacy mode is disabled for the bot. Returned only in getMe.
     * @param supports_inline_queries Optional. True, if the bot supports inline queries. Returned only in getMe.
     * @param can_connect_to_business Optional. True, if the bot can be connected to a Telegram Business account to receive its messages. Returned only in getMe.
     * @param has_main_web_app Optional. True, if the bot has a main Web App. Returned only in getMe.
     * @param has_topics_enabled Optional. True, if the bot has forum topic mode enabled in private chats. Returned only in getMe.
     * @param allows_users_to_create_topics Optional. True, if the bot allows users to create and delete topics in private chats. Returned only in getMe.
     */
    struct User : public TelegramModel {
        typedef std::shared_ptr<User> Ptr;
        typedef std::weak_ptr<User> WeakPtr;

        virtual ~User() = default;
        // Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.
        std::int64_t id = 0;

        // True, if this user is a bot
        bool is_bot = false;

        // User's or bot's first name
        std::string first_name = "";

        // Optional. User's or bot's last name
        std::string last_name = "";

        // Optional. User's or bot's username
        std::string username = "";

        // Optional. IETF language tag of the user's language
        std::string language_code = "";

        // Optional. True, if this user is a Telegram Premium user
        bool is_premium = false;

        // Optional. True, if this user added the bot to the attachment menu
        bool added_to_attachment_menu = false;

        // Optional. True, if the bot can be invited to groups. Returned only in getMe.
        bool can_join_groups = false;

        // Optional. True, if privacy mode is disabled for the bot. Returned only in getMe.
        bool can_read_all_group_messages = false;

        // Optional. True, if the bot supports inline queries. Returned only in getMe.
        bool supports_inline_queries = false;

        // Optional. True, if the bot can be connected to a Telegram Business account to receive its messages. Returned only in getMe.
        bool can_connect_to_business = false;

        // Optional. True, if the bot has a main Web App. Returned only in getMe.
        bool has_main_web_app = false;

        // Optional. True, if the bot has forum topic mode enabled in private chats. Returned only in getMe.
        bool has_topics_enabled = false;

        // Optional. True, if the bot allows users to create and delete topics in private chats. Returned only in getMe.
        bool allows_users_to_create_topics = false;
    };
    void to_json(json& j, const User& value);
    void from_json(const json& j, User& value);
}
