// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/Audio.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents the audios displayed on a user's profile.
     *
     * @param total_count Total number of profile audios for the target user
     * @param audios Requested profile audios
     */
    struct UserProfileAudios : public TelegramModel {
        typedef std::shared_ptr<UserProfileAudios> Ptr;
        typedef std::weak_ptr<UserProfileAudios> WeakPtr;

        virtual ~UserProfileAudios() = default;
        // Total number of profile audios for the target user
        std::int64_t total_count = 0;

        // Requested profile audios
        std::vector<Audio::Ptr> audios = std::vector<Audio::Ptr>();
    };
    void to_json(json& j, const UserProfileAudios& value);
    void from_json(const json& j, UserProfileAudios& value);
}
