// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/PhotoSize.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represent a user's profile pictures.
     *
     * @param total_count Total number of profile pictures the target user has
     * @param photos Requested profile pictures (in up to 4 sizes each)
     */
    struct UserProfilePhotos : public TelegramModel {
        typedef std::shared_ptr<UserProfilePhotos> Ptr;
        typedef std::weak_ptr<UserProfilePhotos> WeakPtr;

        virtual ~UserProfilePhotos() = default;
        // Total number of profile pictures the target user has
        std::int64_t total_count = 0;

        // Requested profile pictures (in up to 4 sizes each)
        std::vector<std::vector<PhotoSize::Ptr>> photos = std::vector<std::vector<PhotoSize::Ptr>>();
    };
    void to_json(json& j, const UserProfilePhotos& value);
    void from_json(const json& j, UserProfilePhotos& value);
}
