// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/ChatBoost.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a list of boosts added to a chat by a user.
     *
     * @param boosts The list of boosts added to the chat by the user
     */
    struct UserChatBoosts : public TelegramModel {
        typedef std::shared_ptr<UserChatBoosts> Ptr;
        typedef std::weak_ptr<UserChatBoosts> WeakPtr;

        virtual ~UserChatBoosts() = default;
        // The list of boosts added to the chat by the user
        std::vector<ChatBoost::Ptr> boosts;
    };
    void to_json(json& j, const UserChatBoosts& value);
    void from_json(const json& j, UserChatBoosts& value);
}
