// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a video file of a specific quality.
     *
     * @param file_id Identifier for this file, which can be used to download or reuse the file
     * @param file_unique_id Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
     * @param width Video width
     * @param height Video height
     * @param codec Codec that was used to encode the video, for example, “h264”, “h265”, or “av01”
     * @param file_size Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
     */
    struct VideoQuality : public TelegramModel {
        typedef std::shared_ptr<VideoQuality> Ptr;
        typedef std::weak_ptr<VideoQuality> WeakPtr;

        virtual ~VideoQuality() = default;
        // Identifier for this file, which can be used to download or reuse the file
        std::string file_id = "";

        // Unique identifier for this file, which is supposed to be the same over time and for different bots. Can't be used to download or reuse the file.
        std::string file_unique_id = "";

        // Video width
        std::int64_t width = 0;

        // Video height
        std::int64_t height = 0;

        // Codec that was used to encode the video, for example, “h264”, “h265”, or “av01”
        std::string codec = "";

        // Optional. File size in bytes. It can be bigger than 2^31 and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this value.
        std::int64_t file_size = 0;
    };
    void to_json(json& j, const VideoQuality& value);
    void from_json(const json& j, VideoQuality& value);
}
