// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"
#include "types/User.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about new members invited to a video chat.
     *
     * @param users New members that were invited to the video chat
     */
    struct VideoChatParticipantsInvited : public TelegramModel {
        typedef std::shared_ptr<VideoChatParticipantsInvited> Ptr;
        typedef std::weak_ptr<VideoChatParticipantsInvited> WeakPtr;

        virtual ~VideoChatParticipantsInvited() = default;
        // New members that were invited to the video chat
        std::vector<User::Ptr> users = std::vector<User::Ptr>();
    };
    void to_json(json& j, const VideoChatParticipantsInvited& value);
    void from_json(const json& j, VideoChatParticipantsInvited& value);
}
