// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/TelegramModel.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * This object represents a service message about a user allowing a bot to write messages after adding it to the attachment menu, launching a Web App from a link, or accepting an explicit request from a Web App sent by the method requestWriteAccess.
     *
     * @param from_request Optional. True, if the access was granted after the user accepted an explicit request from a Web App sent by the method requestWriteAccess
     * @param web_app_name Optional. Name of the Web App, if the access was granted when the Web App was launched from a link
     * @param from_attachment_menu Optional. True, if the access was granted when the bot was added to the attachment or side menu
     */
    struct WriteAccessAllowed : public TelegramModel {
        typedef std::shared_ptr<WriteAccessAllowed> Ptr;
        typedef std::weak_ptr<WriteAccessAllowed> WeakPtr;

        virtual ~WriteAccessAllowed() = default;
        // Optional. True, if the access was granted after the user accepted an explicit request from a Web App sent by the method requestWriteAccess
        bool from_request = false;

        // Optional. Name of the Web App, if the access was granted when the Web App was launched from a link
        std::string web_app_name;

        // Optional. True, if the access was granted when the bot was added to the attachment or side menu
        bool from_attachment_menu = false;
    };
    void to_json(json& j, const WriteAccessAllowed& value);
    void from_json(const json& j, WriteAccessAllowed& value);
}
