// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BackgroundTypeFill.hpp"
#include "types/BackgroundFill.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BackgroundTypeFill& value) {
        j = json{};
        j["type"] = value.type_;
        j["fill"] = value.fill;
        j["dark_theme_dimming"] = value.dark_theme_dimming;
    }

    void from_json(const json& j, BackgroundTypeFill& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("fill")) {
            j.at("fill").get_to(value.fill);
        }
        if (j.contains("dark_theme_dimming")) {
            j.at("dark_theme_dimming").get_to(value.dark_theme_dimming);
        }
    }
}
