// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BackgroundFillFreeformGradient.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BackgroundFillFreeformGradient& value) {
        j = json{};
        j["type"] = value.type_;
        j["colors"] = value.colors;
    }

    void from_json(const json& j, BackgroundFillFreeformGradient& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("colors")) {
            j.at("colors").get_to(value.colors);
        }
    }
}
