// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BackgroundTypeWallpaper.hpp"
#include "types/Document.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BackgroundTypeWallpaper& value) {
        j = json{};
        j["type"] = value.type_;
        j["document"] = value.document;
        j["dark_theme_dimming"] = value.dark_theme_dimming;
    if (value.is_blurred) { 
                    j["is_blurred"] = value.is_blurred; 
            }
    if (value.is_moving) { 
                    j["is_moving"] = value.is_moving; 
            }
    }

    void from_json(const json& j, BackgroundTypeWallpaper& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("document")) {
            j.at("document").get_to(value.document);
        }
        if (j.contains("dark_theme_dimming")) {
            j.at("dark_theme_dimming").get_to(value.dark_theme_dimming);
        }
        if (j.contains("is_blurred")) {
            j.at("is_blurred").get_to(value.is_blurred);
        }
        if (j.contains("is_moving")) {
            j.at("is_moving").get_to(value.is_moving);
        }
    }
}
