// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BackgroundTypeChatTheme.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BackgroundTypeChatTheme& value) {
        j = json{};
        j["type"] = value.type_;
        j["theme_name"] = value.theme_name;
    }

    void from_json(const json& j, BackgroundTypeChatTheme& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("theme_name")) {
            j.at("theme_name").get_to(value.theme_name);
        }
    }
}
