// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Birthdate.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Birthdate& value) {
        j = json{};
        j["day"] = value.day;
        j["month"] = value.month;
    if (value.year != 0) { 
                    j["year"] = value.year; 
            }
    }

    void from_json(const json& j, Birthdate& value) {
        if (j.contains("day")) {
            j.at("day").get_to(value.day);
        }
        if (j.contains("month")) {
            j.at("month").get_to(value.month);
        }
        if (j.contains("year")) {
            j.at("year").get_to(value.year);
        }
    }
}
