// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BotCommandScopeDefault.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BotCommandScopeDefault& value) {
        j = json{};
        j["type"] = value.type_;
    }

    void from_json(const json& j, BotCommandScopeDefault& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
    }
}
