// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BotDescription.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BotDescription& value) {
        j = json{};
        j["description"] = value.description;
    }

    void from_json(const json& j, BotDescription& value) {
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
    }
}
