// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BusinessIntro.hpp"
#include "types/Sticker.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BusinessIntro& value) {
        j = json{};
    if (!value.title.empty()) { 
                    j["title"] = value.title; 
            }
    if (!value.message.empty()) { 
                    j["message"] = value.message; 
            }
    if (value.sticker) { 
                    j["sticker"] = value.sticker; 
            }
    }

    void from_json(const json& j, BusinessIntro& value) {
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("message")) {
            j.at("message").get_to(value.message);
        }
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
    }
}
