// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/BusinessBotRights.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const BusinessBotRights& value) {
        j = json{};
    if (value.can_reply) { 
                    j["can_reply"] = value.can_reply; 
            }
    if (value.can_read_messages) { 
                    j["can_read_messages"] = value.can_read_messages; 
            }
    if (value.can_delete_sent_messages) { 
                    j["can_delete_sent_messages"] = value.can_delete_sent_messages; 
            }
    if (value.can_delete_all_messages) { 
                    j["can_delete_all_messages"] = value.can_delete_all_messages; 
            }
    if (value.can_edit_name) { 
                    j["can_edit_name"] = value.can_edit_name; 
            }
    if (value.can_edit_bio) { 
                    j["can_edit_bio"] = value.can_edit_bio; 
            }
    if (value.can_edit_profile_photo) { 
                    j["can_edit_profile_photo"] = value.can_edit_profile_photo; 
            }
    if (value.can_edit_username) { 
                    j["can_edit_username"] = value.can_edit_username; 
            }
    if (value.can_change_gift_settings) { 
                    j["can_change_gift_settings"] = value.can_change_gift_settings; 
            }
    if (value.can_view_gifts_and_stars) { 
                    j["can_view_gifts_and_stars"] = value.can_view_gifts_and_stars; 
            }
    if (value.can_convert_gifts_to_stars) { 
                    j["can_convert_gifts_to_stars"] = value.can_convert_gifts_to_stars; 
            }
    if (value.can_transfer_and_upgrade_gifts) { 
                    j["can_transfer_and_upgrade_gifts"] = value.can_transfer_and_upgrade_gifts; 
            }
    if (value.can_transfer_stars) { 
                    j["can_transfer_stars"] = value.can_transfer_stars; 
            }
    if (value.can_manage_stories) { 
                    j["can_manage_stories"] = value.can_manage_stories; 
            }
    }

    void from_json(const json& j, BusinessBotRights& value) {
        if (j.contains("can_reply")) {
            j.at("can_reply").get_to(value.can_reply);
        }
        if (j.contains("can_read_messages")) {
            j.at("can_read_messages").get_to(value.can_read_messages);
        }
        if (j.contains("can_delete_sent_messages")) {
            j.at("can_delete_sent_messages").get_to(value.can_delete_sent_messages);
        }
        if (j.contains("can_delete_all_messages")) {
            j.at("can_delete_all_messages").get_to(value.can_delete_all_messages);
        }
        if (j.contains("can_edit_name")) {
            j.at("can_edit_name").get_to(value.can_edit_name);
        }
        if (j.contains("can_edit_bio")) {
            j.at("can_edit_bio").get_to(value.can_edit_bio);
        }
        if (j.contains("can_edit_profile_photo")) {
            j.at("can_edit_profile_photo").get_to(value.can_edit_profile_photo);
        }
        if (j.contains("can_edit_username")) {
            j.at("can_edit_username").get_to(value.can_edit_username);
        }
        if (j.contains("can_change_gift_settings")) {
            j.at("can_change_gift_settings").get_to(value.can_change_gift_settings);
        }
        if (j.contains("can_view_gifts_and_stars")) {
            j.at("can_view_gifts_and_stars").get_to(value.can_view_gifts_and_stars);
        }
        if (j.contains("can_convert_gifts_to_stars")) {
            j.at("can_convert_gifts_to_stars").get_to(value.can_convert_gifts_to_stars);
        }
        if (j.contains("can_transfer_and_upgrade_gifts")) {
            j.at("can_transfer_and_upgrade_gifts").get_to(value.can_transfer_and_upgrade_gifts);
        }
        if (j.contains("can_transfer_stars")) {
            j.at("can_transfer_stars").get_to(value.can_transfer_stars);
        }
        if (j.contains("can_manage_stories")) {
            j.at("can_manage_stories").get_to(value.can_manage_stories);
        }
    }
}
