// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChatBoostSourceGiftCode.hpp"
#include "types/User.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChatBoostSourceGiftCode& value) {
        j = json{};
        j["source"] = value.source;
        j["user"] = value.user;
    }

    void from_json(const json& j, ChatBoostSourceGiftCode& value) {
        if (j.contains("source")) {
            j.at("source").get_to(value.source);
        }
        if (j.contains("user")) {
            j.at("user").get_to(value.user);
        }
    }
}
