// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChecklistTask.hpp"
#include "types/User.hpp"
#include "types/Chat.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChecklistTask& value) {
        j = json{};
        j["id"] = value.id;
        j["text"] = value.text;
    if (!value.text_entities.empty()) { 
                    j["text_entities"] = value.text_entities; 
            }
    if (value.completed_by_user) { 
                    j["completed_by_user"] = value.completed_by_user; 
            }
    if (value.completed_by_chat) { 
                    j["completed_by_chat"] = value.completed_by_chat; 
            }
    if (value.completion_date != 0) { 
                    j["completion_date"] = value.completion_date; 
            }
    }

    void from_json(const json& j, ChecklistTask& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("text_entities")) {
            j.at("text_entities").get_to(value.text_entities);
        }
        if (j.contains("completed_by_user")) {
            j.at("completed_by_user").get_to(value.completed_by_user);
        }
        if (j.contains("completed_by_chat")) {
            j.at("completed_by_chat").get_to(value.completed_by_chat);
        }
        if (j.contains("completion_date")) {
            j.at("completion_date").get_to(value.completion_date);
        }
    }
}
