// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ChecklistTasksDone.hpp"
#include "types/Message.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ChecklistTasksDone& value) {
        j = json{};
    if (value.checklist_message) { 
                    j["checklist_message"] = value.checklist_message; 
            }
    if (!value.marked_as_done_task_ids.empty()) { 
                    j["marked_as_done_task_ids"] = value.marked_as_done_task_ids; 
            }
    if (!value.marked_as_not_done_task_ids.empty()) { 
                    j["marked_as_not_done_task_ids"] = value.marked_as_not_done_task_ids; 
            }
    }

    void from_json(const json& j, ChecklistTasksDone& value) {
        if (j.contains("checklist_message")) {
            j.at("checklist_message").get_to(value.checklist_message);
        }
        if (j.contains("marked_as_done_task_ids")) {
            j.at("marked_as_done_task_ids").get_to(value.marked_as_done_task_ids);
        }
        if (j.contains("marked_as_not_done_task_ids")) {
            j.at("marked_as_not_done_task_ids").get_to(value.marked_as_not_done_task_ids);
        }
    }
}
