// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/DirectMessagePriceChanged.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const DirectMessagePriceChanged& value) {
        j = json{};
        j["are_direct_messages_enabled"] = value.are_direct_messages_enabled;
    if (value.direct_message_star_count != 0) { 
                    j["direct_message_star_count"] = value.direct_message_star_count; 
            }
    }

    void from_json(const json& j, DirectMessagePriceChanged& value) {
        if (j.contains("are_direct_messages_enabled")) {
            j.at("are_direct_messages_enabled").get_to(value.are_direct_messages_enabled);
        }
        if (j.contains("direct_message_star_count")) {
            j.at("direct_message_star_count").get_to(value.direct_message_star_count);
        }
    }
}
