// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/GiveawayCompleted.hpp"
#include "types/Message.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const GiveawayCompleted& value) {
        j = json{};
        j["winner_count"] = value.winner_count;
    if (value.unclaimed_prize_count != 0) { 
                    j["unclaimed_prize_count"] = value.unclaimed_prize_count; 
            }
    if (value.giveaway_message) { 
                    j["giveaway_message"] = value.giveaway_message; 
            }
    if (value.is_star_giveaway) { 
                    j["is_star_giveaway"] = value.is_star_giveaway; 
            }
    }

    void from_json(const json& j, GiveawayCompleted& value) {
        if (j.contains("winner_count")) {
            j.at("winner_count").get_to(value.winner_count);
        }
        if (j.contains("unclaimed_prize_count")) {
            j.at("unclaimed_prize_count").get_to(value.unclaimed_prize_count);
        }
        if (j.contains("giveaway_message")) {
            j.at("giveaway_message").get_to(value.giveaway_message);
        }
        if (j.contains("is_star_giveaway")) {
            j.at("is_star_giveaway").get_to(value.is_star_giveaway);
        }
    }
}
