// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultAudio.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include "types/InputMessageContent.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InlineQueryResultAudio& value) {
        j = json{};
        j["type"] = value.type_;
        j["id"] = value.id;
        j["audio_url"] = value.audio_url;
        j["title"] = value.title;
    if (!value.caption.empty()) { 
                    j["caption"] = value.caption; 
            }
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.caption_entities.empty()) { 
                    j["caption_entities"] = value.caption_entities; 
            }
    if (!value.performer.empty()) { 
                    j["performer"] = value.performer; 
            }
    if (value.audio_duration != 0) { 
                    j["audio_duration"] = value.audio_duration; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    if (value.input_message_content) { 
                    j["input_message_content"] = value.input_message_content; 
            }
    }

    void from_json(const json& j, InlineQueryResultAudio& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("audio_url")) {
            j.at("audio_url").get_to(value.audio_url);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("caption")) {
            j.at("caption").get_to(value.caption);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("caption_entities")) {
            j.at("caption_entities").get_to(value.caption_entities);
        }
        if (j.contains("performer")) {
            j.at("performer").get_to(value.performer);
        }
        if (j.contains("audio_duration")) {
            j.at("audio_duration").get_to(value.audio_duration);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
    }
}
