// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InlineQueryResultArticle.hpp"
#include "types/InputMessageContent.hpp"
#include "types/InlineKeyboardMarkup.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InlineQueryResultArticle& value) {
        j = json{};
        j["type"] = value.type_;
        j["id"] = value.id;
        j["title"] = value.title;
        j["input_message_content"] = value.input_message_content;
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    if (!value.url.empty()) { 
                    j["url"] = value.url; 
            }
    if (!value.description.empty()) { 
                    j["description"] = value.description; 
            }
    if (!value.thumbnail_url.empty()) { 
                    j["thumbnail_url"] = value.thumbnail_url; 
            }
    if (value.thumbnail_width != 0) { 
                    j["thumbnail_width"] = value.thumbnail_width; 
            }
    if (value.thumbnail_height != 0) { 
                    j["thumbnail_height"] = value.thumbnail_height; 
            }
    }

    void from_json(const json& j, InlineQueryResultArticle& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("input_message_content")) {
            j.at("input_message_content").get_to(value.input_message_content);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
        if (j.contains("url")) {
            j.at("url").get_to(value.url);
        }
        if (j.contains("description")) {
            j.at("description").get_to(value.description);
        }
        if (j.contains("thumbnail_url")) {
            j.at("thumbnail_url").get_to(value.thumbnail_url);
        }
        if (j.contains("thumbnail_width")) {
            j.at("thumbnail_width").get_to(value.thumbnail_width);
        }
        if (j.contains("thumbnail_height")) {
            j.at("thumbnail_height").get_to(value.thumbnail_height);
        }
    }
}
