// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputChecklist.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputChecklist& value) {
        j = json{};
        j["title"] = value.title;
        j["tasks"] = value.tasks;
    if (!value.parse_mode.empty()) { 
                    j["parse_mode"] = value.parse_mode; 
            }
    if (!value.title_entities.empty()) { 
                    j["title_entities"] = value.title_entities; 
            }
    if (value.others_can_add_tasks) { 
                    j["others_can_add_tasks"] = value.others_can_add_tasks; 
            }
    if (value.others_can_mark_tasks_as_done) { 
                    j["others_can_mark_tasks_as_done"] = value.others_can_mark_tasks_as_done; 
            }
    }

    void from_json(const json& j, InputChecklist& value) {
        if (j.contains("title")) {
            j.at("title").get_to(value.title);
        }
        if (j.contains("tasks")) {
            j.at("tasks").get_to(value.tasks);
        }
        if (j.contains("parse_mode")) {
            j.at("parse_mode").get_to(value.parse_mode);
        }
        if (j.contains("title_entities")) {
            j.at("title_entities").get_to(value.title_entities);
        }
        if (j.contains("others_can_add_tasks")) {
            j.at("others_can_add_tasks").get_to(value.others_can_add_tasks);
        }
        if (j.contains("others_can_mark_tasks_as_done")) {
            j.at("others_can_mark_tasks_as_done").get_to(value.others_can_mark_tasks_as_done);
        }
    }
}
