// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputFile.hpp"
#include "tools/FileTools.hpp"
#include <filesystem>

namespace TgBot {
    InputFile::Ptr InputFile::fromFile(const std::string& filePath, const std::string& mimeType) {
        auto result(std::make_shared<InputFile>());
        result->data = FileTools::read(filePath);
        result->mimeType = mimeType;
        result->fileName = std::filesystem::path(filePath).filename().string();
        return result;
    }
}
