// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/InputPaidMediaPhoto.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const InputPaidMediaPhoto& value) {
        j = json{};
        j["type"] = value.type_;
        j["media"] = value.media;
    }

    void from_json(const json& j, InputPaidMediaPhoto& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("media")) {
            j.at("media").get_to(value.media);
        }
    }
}
