// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/LocationAddress.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const LocationAddress& value) {
        j = json{};
        j["country_code"] = value.country_code;
    if (!value.state.empty()) { 
                    j["state"] = value.state; 
            }
    if (!value.city.empty()) { 
                    j["city"] = value.city; 
            }
    if (!value.street.empty()) { 
                    j["street"] = value.street; 
            }
    }

    void from_json(const json& j, LocationAddress& value) {
        if (j.contains("country_code")) {
            j.at("country_code").get_to(value.country_code);
        }
        if (j.contains("state")) {
            j.at("state").get_to(value.state);
        }
        if (j.contains("city")) {
            j.at("city").get_to(value.city);
        }
        if (j.contains("street")) {
            j.at("street").get_to(value.street);
        }
    }
}
