// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MessageOrigin.hpp"

namespace TgBot {
    void to_json(json& j, const MessageOrigin& value) { }
    void from_json(const json& j, MessageOrigin& value) { }
}
