// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/MessageOriginHiddenUser.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const MessageOriginHiddenUser& value) {
        j = json{};
        j["type"] = value.type_;
        j["date"] = value.date;
        j["sender_user_name"] = value.sender_user_name;
    }

    void from_json(const json& j, MessageOriginHiddenUser& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("date")) {
            j.at("date").get_to(value.date);
        }
        if (j.contains("sender_user_name")) {
            j.at("sender_user_name").get_to(value.sender_user_name);
        }
    }
}
