// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/OrderInfo.hpp"
#include "types/ShippingAddress.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const OrderInfo& value) {
        j = json{};
    if (!value.name.empty()) { 
                    j["name"] = value.name; 
            }
    if (!value.phone_number.empty()) { 
                    j["phone_number"] = value.phone_number; 
            }
    if (!value.email.empty()) { 
                    j["email"] = value.email; 
            }
    if (value.shipping_address) { 
                    j["shipping_address"] = value.shipping_address; 
            }
    }

    void from_json(const json& j, OrderInfo& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("phone_number")) {
            j.at("phone_number").get_to(value.phone_number);
        }
        if (j.contains("email")) {
            j.at("email").get_to(value.email);
        }
        if (j.contains("shipping_address")) {
            j.at("shipping_address").get_to(value.shipping_address);
        }
    }
}
