// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PaidMediaPreview.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PaidMediaPreview& value) {
        j = json{};
        j["type"] = value.type_;
    if (value.width != 0) { 
                    j["width"] = value.width; 
            }
    if (value.height != 0) { 
                    j["height"] = value.height; 
            }
    if (value.duration != 0) { 
                    j["duration"] = value.duration; 
            }
    }

    void from_json(const json& j, PaidMediaPreview& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("width")) {
            j.at("width").get_to(value.width);
        }
        if (j.contains("height")) {
            j.at("height").get_to(value.height);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
    }
}
