// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/PassportFile.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const PassportFile& value) {
        j = json{};
        j["file_id"] = value.file_id;
        j["file_unique_id"] = value.file_unique_id;
        j["file_size"] = value.file_size;
        j["file_date"] = value.file_date;
    }

    void from_json(const json& j, PassportFile& value) {
        if (j.contains("file_id")) {
            j.at("file_id").get_to(value.file_id);
        }
        if (j.contains("file_unique_id")) {
            j.at("file_unique_id").get_to(value.file_unique_id);
        }
        if (j.contains("file_size")) {
            j.at("file_size").get_to(value.file_size);
        }
        if (j.contains("file_date")) {
            j.at("file_date").get_to(value.file_date);
        }
    }
}
