// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ReactionCount.hpp"
#include "types/ReactionType.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ReactionCount& value) {
        j = json{};
        j["type"] = value.type_;
        j["total_count"] = value.total_count;
    }

    void from_json(const json& j, ReactionCount& value) {
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("total_count")) {
            j.at("total_count").get_to(value.total_count);
        }
    }
}
