// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/SharedUser.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const SharedUser& value) {
        j = json{};
        j["user_id"] = value.user_id;
    if (!value.first_name.empty()) { 
                    j["first_name"] = value.first_name; 
            }
    if (!value.last_name.empty()) { 
                    j["last_name"] = value.last_name; 
            }
    if (!value.username.empty()) { 
                    j["username"] = value.username; 
            }
    if (!value.photo.empty()) { 
                    j["photo"] = value.photo; 
            }
    }

    void from_json(const json& j, SharedUser& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
        if (j.contains("username")) {
            j.at("username").get_to(value.username);
        }
        if (j.contains("photo")) {
            j.at("photo").get_to(value.photo);
        }
    }
}
