// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/ShippingQuery.hpp"
#include "types/User.hpp"
#include "types/ShippingAddress.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const ShippingQuery& value) {
        j = json{};
        j["id"] = value.id;
        j["from"] = value.from;
        j["invoice_payload"] = value.invoice_payload;
        j["shipping_address"] = value.shipping_address;
    }

    void from_json(const json& j, ShippingQuery& value) {
        if (j.contains("id")) {
            j.at("id").get_to(value.id);
        }
        if (j.contains("from")) {
            j.at("from").get_to(value.from);
        }
        if (j.contains("invoice_payload")) {
            j.at("invoice_payload").get_to(value.invoice_payload);
        }
        if (j.contains("shipping_address")) {
            j.at("shipping_address").get_to(value.shipping_address);
        }
    }
}
