// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/SuggestedPostPaid.hpp"
#include "types/Message.hpp"
#include "types/StarAmount.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const SuggestedPostPaid& value) {
        j = json{};
        j["currency"] = value.currency;
    if (value.suggested_post_message) { 
                    j["suggested_post_message"] = value.suggested_post_message; 
            }
    if (value.amount != 0) { 
                    j["amount"] = value.amount; 
            }
    if (value.star_amount) { 
                    j["star_amount"] = value.star_amount; 
            }
    }

    void from_json(const json& j, SuggestedPostPaid& value) {
        if (j.contains("currency")) {
            j.at("currency").get_to(value.currency);
        }
        if (j.contains("suggested_post_message")) {
            j.at("suggested_post_message").get_to(value.suggested_post_message);
        }
        if (j.contains("amount")) {
            j.at("amount").get_to(value.amount);
        }
        if (j.contains("star_amount")) {
            j.at("star_amount").get_to(value.star_amount);
        }
    }
}
