// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/SuggestedPostPrice.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const SuggestedPostPrice& value) {
        j = json{};
        j["currency"] = value.currency;
        j["amount"] = value.amount;
    }

    void from_json(const json& j, SuggestedPostPrice& value) {
        if (j.contains("currency")) {
            j.at("currency").get_to(value.currency);
        }
        if (j.contains("amount")) {
            j.at("amount").get_to(value.amount);
        }
    }
}
