// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/TransactionPartner.hpp"

namespace TgBot {
    void to_json(json& j, const TransactionPartner& value) { }
    void from_json(const json& j, TransactionPartner& value) { }
}
