// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/UsersShared.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const UsersShared& value) {
        j = json{};
        j["request_id"] = value.request_id;
        j["users"] = value.users;
    }

    void from_json(const json& j, UsersShared& value) {
        if (j.contains("request_id")) {
            j.at("request_id").get_to(value.request_id);
        }
        if (j.contains("users")) {
            j.at("users").get_to(value.users);
        }
    }
}
