// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/VideoChatScheduled.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const VideoChatScheduled& value) {
        j = json{};
        j["start_date"] = value.start_date;
    }

    void from_json(const json& j, VideoChatScheduled& value) {
        if (j.contains("start_date")) {
            j.at("start_date").get_to(value.start_date);
        }
    }
}
