// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "types/Voice.hpp"
#include <nlohmann/json.hpp>

namespace TgBot {
    void to_json(json& j, const Voice& value) {
        j = json{};
        j["file_id"] = value.file_id;
        j["file_unique_id"] = value.file_unique_id;
        j["duration"] = value.duration;
    if (!value.mime_type.empty()) { 
                    j["mime_type"] = value.mime_type; 
            }
    if (value.file_size != 0) { 
                    j["file_size"] = value.file_size; 
            }
    }

    void from_json(const json& j, Voice& value) {
        if (j.contains("file_id")) {
            j.at("file_id").get_to(value.file_id);
        }
        if (j.contains("file_unique_id")) {
            j.at("file_unique_id").get_to(value.file_unique_id);
        }
        if (j.contains("duration")) {
            j.at("duration").get_to(value.duration);
        }
        if (j.contains("mime_type")) {
            j.at("mime_type").get_to(value.mime_type);
        }
        if (j.contains("file_size")) {
            j.at("file_size").get_to(value.file_size);
        }
    }
}
