// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InputSticker.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to add a new sticker to a set created by the bot. Emoji sticker sets can have up to 200 stickers. Other sticker sets can have up to 120 stickers. Returns True on success.
     *
     * @param user_id User identifier of sticker set owner
     * @param name Sticker set name
     * @param sticker A JSON-serialized object with information about the added sticker. If exactly the same sticker had already been added to the set, then the set isn't changed.
     */
    struct AddStickerToSetRequest {
        typedef std::shared_ptr<AddStickerToSetRequest> Ptr;
        // User identifier of sticker set owner
        int64_t user_id = 0;

        // Sticker set name
        std::string name;

        // A JSON-serialized object with information about the added sticker. If exactly the same sticker had already been added to the set, then the set isn't changed.
        InputSticker::Ptr sticker;
    };
    void to_json(json& j, const AddStickerToSetRequest& value);
    void from_json(const json& j, AddStickerToSetRequest& value);
}
