// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Returns the bot's Telegram Star transactions in chronological order. On success, returns a StarTransactions object.
     *
     * @param offset Number of transactions to skip in the response
     * @param limit The maximum number of transactions to be retrieved. Values between 1-100 are accepted. Defaults to 100.
     */
    struct GetStarTransactionsRequest {
        typedef std::shared_ptr<GetStarTransactionsRequest> Ptr;
        // Number of transactions to skip in the response
        int64_t offset = 0;

        // The maximum number of transactions to be retrieved. Values between 1-100 are accepted. Defaults to 100.
        int64_t limit = 0;
    };
    void to_json(json& j, const GetStarTransactionsRequest& value);
    void from_json(const json& j, GetStarTransactionsRequest& value);
}
