// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Marks incoming message as read on behalf of a business account. Requires the can_read_messages business bot right. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection on behalf of which to read the message
     * @param chat_id Unique identifier of the chat in which the message was received. The chat must have been active in the last 24 hours.
     * @param message_id Unique identifier of the message to mark as read
     */
    struct ReadBusinessMessageRequest {
        typedef std::shared_ptr<ReadBusinessMessageRequest> Ptr;
        // Unique identifier of the business connection on behalf of which to read the message
        std::string business_connection_id;

        // Unique identifier of the chat in which the message was received. The chat must have been active in the last 24 hours.
        int64_t chat_id = 0;

        // Unique identifier of the message to mark as read
        int64_t message_id = 0;
    };
    void to_json(json& j, const ReadBusinessMessageRequest& value);
    void from_json(const json& j, ReadBusinessMessageRequest& value);
}
