// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Reposts a story on behalf of a business account from another business account. Both business accounts must be managed by the same bot, and the story on the source account must have been posted (or reposted) by the bot. Requires the can_manage_stories business bot right for both business accounts. Returns Story on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param from_chat_id Unique identifier of the chat which posted the story that should be reposted
     * @param from_story_id Unique identifier of the story that should be reposted
     * @param active_period Period after which the story is moved to the archive, in seconds; must be one of 6 * 3600, 12 * 3600, 86400, or 2 * 86400
     * @param post_to_chat_page Pass True to keep the story accessible after it expires
     * @param protect_content Pass True if the content of the story must be protected from forwarding and screenshotting
     */
    struct RepostStoryRequest {
        typedef std::shared_ptr<RepostStoryRequest> Ptr;
        // Unique identifier of the business connection
        std::string business_connection_id;

        // Unique identifier of the chat which posted the story that should be reposted
        int64_t from_chat_id = 0;

        // Unique identifier of the story that should be reposted
        int64_t from_story_id = 0;

        // Period after which the story is moved to the archive, in seconds; must be one of 6 * 3600, 12 * 3600, 86400, or 2 * 86400
        int64_t active_period = 0;

        // Pass True to keep the story accessible after it expires
        bool post_to_chat_page = false;

        // Pass True if the content of the story must be protected from forwarding and screenshotting
        bool protect_content = false;
    };
    void to_json(json& j, const RepostStoryRequest& value);
    void from_json(const json& j, RepostStoryRequest& value);
}
