// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/MessageEntity.hpp"
#include "types/SuggestedPostParameters.hpp"
#include "types/ReplyParameters.hpp"
#include "types/KeyboardOption.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to send audio files, if you want Telegram clients to display the file as a playable voice message. For this to work, your audio must be in an .OGG file encoded with OPUS, or in .MP3 format, or in .M4A format (other formats may be sent as Audio or Document). On success, the sent Message is returned. Bots can currently send voice messages of up to 50 MB in size, this limit may be changed in the future.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param voice Audio file to send. Pass a file_id as String to send a file that exists on the Telegram servers (recommended), pass an HTTP URL as a String for Telegram to get a file from the Internet, or upload a new one using multipart/form-data. More information on Sending Files »
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param message_thread_id Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
     * @param direct_messages_topic_id Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
     * @param caption Voice message caption, 0-1024 characters after entities parsing
     * @param parse_mode Mode for parsing entities in the voice message caption. See formatting options for more details.
     * @param caption_entities A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
     * @param duration Duration of the voice message in seconds
     * @param disable_notification Sends the message silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the sent message from forwarding and saving
     * @param allow_paid_broadcast Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
     * @param message_effect_id Unique identifier of the message effect to be added to the message; for private chats only
     * @param suggested_post_parameters A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
     * @param reply_parameters Description of the message to reply to
     * @param reply_markup Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
     */
    struct SendVoiceRequest {
        typedef std::shared_ptr<SendVoiceRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // Audio file to send. Pass a file_id as String to send a file that exists on the Telegram servers (recommended), pass an HTTP URL as a String for Telegram to get a file from the Internet, or upload a new one using multipart/form-data. More information on Sending Files »
        std::string voice;

        // Unique identifier of the business connection on behalf of which the message will be sent
        std::string business_connection_id;

        // Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
        int64_t message_thread_id = 0;

        // Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
        int64_t direct_messages_topic_id = 0;

        // Voice message caption, 0-1024 characters after entities parsing
        std::string caption;

        // Mode for parsing entities in the voice message caption. See formatting options for more details.
        std::string parse_mode;

        // A JSON-serialized list of special entities that appear in the caption, which can be specified instead of parse_mode
        std::vector<MessageEntity::Ptr> caption_entities;

        // Duration of the voice message in seconds
        int64_t duration = 0;

        // Sends the message silently. Users will receive a notification with no sound.
        bool disable_notification = false;

        // Protects the contents of the sent message from forwarding and saving
        bool protect_content = false;

        // Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
        bool allow_paid_broadcast = false;

        // Unique identifier of the message effect to be added to the message; for private chats only
        std::string message_effect_id;

        // A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
        SuggestedPostParameters::Ptr suggested_post_parameters;

        // Description of the message to reply to
        ReplyParameters::Ptr reply_parameters;

        // Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
        KeyboardOption::Ptr reply_markup;
    };
    void to_json(json& j, const SendVoiceRequest& value);
    void from_json(const json& j, SendVoiceRequest& value);
}
