// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/SuggestedPostParameters.hpp"
#include "types/ReplyParameters.hpp"
#include "types/KeyboardOption.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to send phone contacts. On success, the sent Message is returned.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param phone_number Contact's phone number
     * @param first_name Contact's first name
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message will be sent
     * @param message_thread_id Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
     * @param direct_messages_topic_id Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
     * @param last_name Contact's last name
     * @param vcard Additional data about the contact in the form of a vCard, 0-2048 bytes
     * @param disable_notification Sends the message silently. Users will receive a notification with no sound.
     * @param protect_content Protects the contents of the sent message from forwarding and saving
     * @param allow_paid_broadcast Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
     * @param message_effect_id Unique identifier of the message effect to be added to the message; for private chats only
     * @param suggested_post_parameters A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
     * @param reply_parameters Description of the message to reply to
     * @param reply_markup Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
     */
    struct SendContactRequest {
        typedef std::shared_ptr<SendContactRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // Contact's phone number
        std::string phone_number;

        // Contact's first name
        std::string first_name;

        // Unique identifier of the business connection on behalf of which the message will be sent
        std::string business_connection_id;

        // Unique identifier for the target message thread (topic) of a forum; for forum supergroups and private chats of bots with forum topic mode enabled only
        int64_t message_thread_id = 0;

        // Identifier of the direct messages topic to which the message will be sent; required if the message is sent to a direct messages chat
        int64_t direct_messages_topic_id = 0;

        // Contact's last name
        std::string last_name;

        // Additional data about the contact in the form of a vCard, 0-2048 bytes
        std::string vcard;

        // Sends the message silently. Users will receive a notification with no sound.
        bool disable_notification = false;

        // Protects the contents of the sent message from forwarding and saving
        bool protect_content = false;

        // Pass True to allow up to 1000 messages per second, ignoring broadcasting limits for a fee of 0.1 Telegram Stars per message. The relevant Stars will be withdrawn from the bot's balance
        bool allow_paid_broadcast = false;

        // Unique identifier of the message effect to be added to the message; for private chats only
        std::string message_effect_id;

        // A JSON-serialized object containing the parameters of the suggested post to send; for direct messages chats only. If the message is sent as a reply to another suggested post, then that suggested post is automatically declined.
        SuggestedPostParameters::Ptr suggested_post_parameters;

        // Description of the message to reply to
        ReplyParameters::Ptr reply_parameters;

        // Additional interface options. A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove a reply keyboard or to force a reply from the user
        KeyboardOption::Ptr reply_markup;
    };
    void to_json(json& j, const SendContactRequest& value);
    void from_json(const json& j, SendContactRequest& value);
}
