// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Changes the first and last name of a managed business account. Requires the can_change_name business bot right. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param first_name The new value of the first name for the business account; 1-64 characters
     * @param last_name The new value of the last name for the business account; 0-64 characters
     */
    struct SetBusinessAccountNameRequest {
        typedef std::shared_ptr<SetBusinessAccountNameRequest> Ptr;
        // Unique identifier of the business connection
        std::string business_connection_id;

        // The new value of the first name for the business account; 1-64 characters
        std::string first_name;

        // The new value of the last name for the business account; 0-64 characters
        std::string last_name;
    };
    void to_json(json& j, const SetBusinessAccountNameRequest& value);
    void from_json(const json& j, SetBusinessAccountNameRequest& value);
}
