// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/AcceptedGiftTypes.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Changes the privacy settings pertaining to incoming gifts in a managed business account. Requires the can_change_gift_settings business bot right. Returns True on success.
     *
     * @param business_connection_id Unique identifier of the business connection
     * @param show_gift_button Pass True, if a button for sending a gift to the user or by the business account must always be shown in the input field
     * @param accepted_gift_types Types of gifts accepted by the business account
     */
    struct SetBusinessAccountGiftSettingsRequest {
        typedef std::shared_ptr<SetBusinessAccountGiftSettingsRequest> Ptr;
        // Unique identifier of the business connection
        std::string business_connection_id;

        // Pass True, if a button for sending a gift to the user or by the business account must always be shown in the input field
        bool show_gift_button = false;

        // Types of gifts accepted by the business account
        AcceptedGiftTypes::Ptr accepted_gift_types;
    };
    void to_json(json& j, const SetBusinessAccountGiftSettingsRequest& value);
    void from_json(const json& j, SetBusinessAccountGiftSettingsRequest& value);
}
