// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to set a custom title for an administrator in a supergroup promoted by the bot. Returns True on success.
     *
     * @param chat_id Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
     * @param user_id Unique identifier of the target user
     * @param custom_title New custom title for the administrator; 0-16 characters, emoji are not allowed
     */
    struct SetChatAdministratorCustomTitleRequest {
        typedef std::shared_ptr<SetChatAdministratorCustomTitleRequest> Ptr;
        // Unique identifier for the target chat or username of the target supergroup (in the format @supergroupusername)
        int64_t chat_id = 0;

        // Unique identifier of the target user
        int64_t user_id = 0;

        // New custom title for the administrator; 0-16 characters, emoji are not allowed
        std::string custom_title;
    };
    void to_json(json& j, const SetChatAdministratorCustomTitleRequest& value);
    void from_json(const json& j, SetChatAdministratorCustomTitleRequest& value);
}
