// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <nlohmann/json.hpp>
#include "types/InlineKeyboardMarkup.hpp"

namespace TgBot {

    using json = nlohmann::json;

    /**
     * Use this method to stop a poll which was sent by the bot. On success, the stopped Poll is returned.
     *
     * @param chat_id Unique identifier for the target chat or username of the target channel (in the format @channelusername)
     * @param message_id Identifier of the original message with the poll
     * @param business_connection_id Unique identifier of the business connection on behalf of which the message to be edited was sent
     * @param reply_markup A JSON-serialized object for a new message inline keyboard.
     */
    struct StopPollRequest {
        typedef std::shared_ptr<StopPollRequest> Ptr;
        // Unique identifier for the target chat or username of the target channel (in the format @channelusername)
        int64_t chat_id = 0;

        // Identifier of the original message with the poll
        int64_t message_id = 0;

        // Unique identifier of the business connection on behalf of which the message to be edited was sent
        std::string business_connection_id;

        // A JSON-serialized object for a new message inline keyboard.
        InlineKeyboardMarkup::Ptr reply_markup;
    };
    void to_json(json& j, const StopPollRequest& value);
    void from_json(const json& j, StopPollRequest& value);
}
