// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "net/TgLongPoll.hpp"
#include "Bot.hpp"
#include "EventHandler.hpp"
#include "requests/GetUpdatesRequest.hpp"
#include <cstdint>
#include <memory>
#include <vector>
#include <utility>
#include <coro/sync_wait.hpp>

namespace TgBot {
    TgLongPoll::TgLongPoll(const Api* api, const EventHandler* eventHandler, std::int32_t limit, std::int32_t timeout, std::shared_ptr<std::vector<std::string>> allowUpdates)
        : api_(api), eventHandler_(eventHandler), limit_(limit), timeout_(timeout)
        , allowUpdates_(std::move(allowUpdates)) {
    }

    TgLongPoll::TgLongPoll(const Bot& bot, std::int32_t limit, std::int32_t timeout, const std::shared_ptr<std::vector<std::string>>& allowUpdates)
        : TgLongPoll(&bot.getApi(), &bot.getEventHandler(), limit, timeout, allowUpdates) {
    }

    void TgLongPoll::start() {
        coro::sync_wait(startAsync());
    }

    coro::task<void> TgLongPoll::startAsync() {
        // handle updates
        for (Update::Ptr& item : updates_) {
            if (item->update_id >= lastUpdateId_) {
                lastUpdateId_ = item->update_id + 1;
            }
            co_await eventHandler_->handleUpdate(item);
        }

        // confirm handled updates by fetching new ones
        GetUpdatesRequest request;
        request.offset = lastUpdateId_;
        request.limit = limit_;
        request.timeout = timeout_;
        if (allowUpdates_)
            request.allowed_updates = *allowUpdates_;
        
        auto response = co_await api_->getUpdates(request);
        if (response.result) {
            updates_ = response.result.value();
        }
    }
}
