// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include "types/Message.hpp"
#include "types/InlineQuery.hpp"
#include "types/ChosenInlineResult.hpp"
#include "types/CallbackQuery.hpp"
#include "types/ShippingQuery.hpp"
#include "types/PreCheckoutQuery.hpp"
#include "types/Poll.hpp"
#include "types/PollAnswer.hpp"
#include "types/ChatMemberUpdated.hpp"
#include "types/ChatJoinRequest.hpp"
#include "types/SuccessfulPayment.hpp"
#include <functional>
#include <initializer_list>
#include <string>
#include <unordered_map>
#include <vector>
#include <coro/task.hpp>

namespace TgBot {

    class EventHandler;

    /**
     * @brief This class holds all event listeners.
     *
     * @ingroup general
     */
    class EventBroadcaster {

    friend class EventHandler;

    public:
        typedef std::function<coro::task<void> (const Message::Ptr)> MessageListener;
        typedef std::function<coro::task<void> (const InlineQuery::Ptr)> InlineQueryListener;
        typedef std::function<coro::task<void> (const ChosenInlineResult::Ptr)> ChosenInlineResultListener;
        typedef std::function<coro::task<void> (const CallbackQuery::Ptr)> CallbackQueryListener;
        typedef std::function<coro::task<void> (const ShippingQuery::Ptr)> ShippingQueryListener;
        typedef std::function<coro::task<void> (const PreCheckoutQuery::Ptr)> PreCheckoutQueryListener;
        typedef std::function<coro::task<void> (const Poll::Ptr)> PollListener;
        typedef std::function<coro::task<void> (const PollAnswer::Ptr)> PollAnswerListener;
        typedef std::function<coro::task<void> (const ChatMemberUpdated::Ptr)> ChatMemberUpdatedListener;
        typedef std::function<coro::task<void> (const ChatJoinRequest::Ptr)> ChatJoinRequestListener;
        typedef std::function<coro::task<void> (const Message::Ptr, const SuccessfulPayment::Ptr)> SuccessfulPaymentListener;

        /**
         * @brief Registers listener which receives new incoming message of any kind - text, photo, sticker, etc.
         * @param listener Listener.
         */
        void onAnyMessage(const MessageListener& listener);

        /**
         * @brief Registers listener which receives all messages with commands (messages with leading '/' char).
         * @param commandName Command name which listener can handle.
         * @param listener Listener. Pass nullptr to remove listener of command
         */
        void onCommand(const std::string& commandName, const MessageListener& listener);

        /**
        * @brief Registers listener which receives all messages with commands (messages with leading '/' char).
        * @param commandsList Commands names which listener can handle.
        * @param listener Listener. Pass nullptr to remove listener of commands
        */
        void onCommand(const std::initializer_list<std::string>& commandsList, const MessageListener& listener);

        /**
         * @brief Registers listener which receives all messages with commands (messages with leading '/' char) which haven't been handled by other listeners.
         * @param listener Listener.
         */
        void onUnknownCommand(const MessageListener& listener);

        /**
         * @brief Registers listener which receives all messages without commands (messages with no leading '/' char)
         * @param listener Listener.
         */
        void onNonCommandMessage(const MessageListener& listener);

        /**
         * @brief Registers listener which receives new versions of a message that is known to the bot and was edited
         * @param listener Listener.
         */
        void onEditedMessage(const MessageListener& listener);

        /**
         * @brief Registers listener which receives new incoming inline queries
         * @param listener Listener.
         */
        void onInlineQuery(const InlineQueryListener& listener);

        /**
         * @brief Registers listener which receives the results of an inline query that was chosen by a user and sent to their chat partner.
         * Please see https://core.telegram.org/bots/inline#collecting-feedback for details on how to enable these updates for your bot.
         * 
         * @param listener Listener.
         */
        void onChosenInlineResult(const ChosenInlineResultListener& listener);

        /**
         * @brief Registers listener which receives new incoming callback queries
         * @param listener Listener.
         */
        void onCallbackQuery(const CallbackQueryListener& listener);

        /**
         * @brief Registers listener which receives new incoming shipping queries.
         * Only for invoices with flexible price
         * 
         * @param listener Listener.
         */
        void onShippingQuery(const ShippingQueryListener& listener);

        /**
         * @brief Registers listener which receives new incoming pre-checkout queries.
         * Contains full information about checkout
         * 
         * @param listener Listener.
         */
        void onPreCheckoutQuery(const PreCheckoutQueryListener& listener);

        /**
         * @brief Registers listener which receives new poll states.
         * Bots receive only updates about stopped polls and polls, which are sent by the bot
         * 
         * @param listener Listener.
         */
        void onPoll(const PollListener& listener);

        /**
         * @brief Registers listener which receives an answer if a user changed their answer in a non-anonymous poll.
         * Bots receive new votes only in polls that were sent by the bot itself.
         * 
         * @param listener Listener.
         */
        void onPollAnswer(const PollAnswerListener& listener);

        /**
         * @brief Registers listener which receives the bot's chat member status if it was updated in a chat.
         * For private chats, this update is received only when the bot is blocked or unblocked by the user.
         * 
         * @param listener Listener.
         */
        void onMyChatMember(const ChatMemberUpdatedListener& listener);

        /**
         * @brief Registers listener which receives a status if a chat member's status was updated in a chat.
         * The bot must be an administrator in the chat and must explicitly specify “chat_member” in the list of allowedUpdates to receive these updates.
         * 
         * @param listener Listener.
         */
        void onChatMember(const ChatMemberUpdatedListener& listener);

        /**
         * @brief Registers listener which receives requests to join the chat.
         * The bot must have the canInviteUsers administrator right in the chat to receive these updates.
         * 
         * @param listener Listener.
         */
        void onChatJoinRequest(const ChatJoinRequestListener& listener);

        /**
        * @brief Registers listener which receives information about successful payments.
        * This listener is triggered when a successful payment is received by the bot.
        * 
        * @param listener Listener.
        */
        void onSuccessfulPayment(const SuccessfulPaymentListener& listener);

    private:
        template<typename ListenerType, typename ObjectType>
        coro::task<void> broadcast(const std::vector<ListenerType>& listeners, const ObjectType object) const {
            if (!object)
                co_return;

            for (const ListenerType& item : listeners) {
                co_await item(object);
            }
        }

        coro::task<void> broadcastAnyMessage(const Message::Ptr& message) const;
        coro::task<bool> broadcastCommand(const std::string& command, const Message::Ptr& message) const;
        coro::task<void> broadcastUnknownCommand(const Message::Ptr& message) const;
        coro::task<void> broadcastNonCommandMessage(const Message::Ptr& message) const;
        coro::task<void> broadcastEditedMessage(const Message::Ptr& message) const;
        coro::task<void> broadcastInlineQuery(const InlineQuery::Ptr& query) const;
        coro::task<void> broadcastChosenInlineResult(const ChosenInlineResult::Ptr& result) const;
        coro::task<void> broadcastCallbackQuery(const CallbackQuery::Ptr& result) const;
        coro::task<void> broadcastShippingQuery(const ShippingQuery::Ptr& result) const;
        coro::task<void> broadcastPreCheckoutQuery(const PreCheckoutQuery::Ptr& result) const;
        coro::task<void> broadcastPoll(const Poll::Ptr& result) const;
        coro::task<void> broadcastPollAnswer(const PollAnswer::Ptr& result) const;
        coro::task<void> broadcastMyChatMember(const ChatMemberUpdated::Ptr& result) const;
        coro::task<void> broadcastChatMember(const ChatMemberUpdated::Ptr& result) const;
        coro::task<void> broadcastChatJoinRequest(const ChatJoinRequest::Ptr& result) const;
        coro::task<void> broadcastSuccessfulPayment(const Message::Ptr& message) const;

        std::vector<MessageListener> onAnyMessageListeners_;
        std::unordered_map<std::string, MessageListener> onCommandListeners_;
        std::vector<MessageListener> onUnknownCommandListeners_;
        std::vector<MessageListener> onNonCommandMessageListeners_;
        std::vector<MessageListener> onEditedMessageListeners_;
        std::vector<InlineQueryListener> onInlineQueryListeners_;
        std::vector<ChosenInlineResultListener> onChosenInlineResultListeners_;
        std::vector<CallbackQueryListener> onCallbackQueryListeners_;
        std::vector<ShippingQueryListener> onShippingQueryListeners_;
        std::vector<PreCheckoutQueryListener> onPreCheckoutQueryListeners_;
        std::vector<PollListener> onPollListeners_;
        std::vector<PollAnswerListener> onPollAnswerListeners_;
        std::vector<ChatMemberUpdatedListener> onMyChatMemberListeners_;
        std::vector<ChatMemberUpdatedListener> onChatMemberListeners_;
        std::vector<ChatJoinRequestListener> onChatJoinRequestListeners_;
        std::vector<SuccessfulPaymentListener> onSuccessfulPaymentListeners_;
    };
}
