// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#pragma once
#include "Api.hpp"
#include <coro/task.hpp>
#include <string>

namespace TgBot {

    class WebhookService {
    private:
        Api& client_;
        std::string url_;
        std::string secret_token_;

    public:
        explicit WebhookService(Api& client, const std::string& url, const std::string& secret_token = "");
        
        void start();

        [[nodiscard]]
        coro::task<void> startAsync();
        
        [[nodiscard]]
        bool validate(const std::string& header_secret_token) const;
        
        static Update::Ptr parse(const std::string& json);

    };
}
