// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/AnswerShippingQueryRequest.hpp"

namespace TgBot {
    void to_json(json& j, const AnswerShippingQueryRequest& value) {
        j = json{};
        j["shipping_query_id"] = value.shipping_query_id;
        j["ok"] = value.ok;
    if (!value.shipping_options.empty()) { 
                    j["shipping_options"] = value.shipping_options; 
            }
    if (!value.error_message.empty()) { 
                    j["error_message"] = value.error_message; 
            }
    }

    void from_json(const json& j, AnswerShippingQueryRequest& value) {
        if (j.contains("shipping_query_id")) {
            j.at("shipping_query_id").get_to(value.shipping_query_id);
        }
        if (j.contains("ok")) {
            j.at("ok").get_to(value.ok);
        }
        if (j.contains("shipping_options")) {
            j.at("shipping_options").get_to(value.shipping_options);
        }
        if (j.contains("error_message")) {
            j.at("error_message").get_to(value.error_message);
        }
    }
}
