// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/AnswerCallbackQueryRequest.hpp"

namespace TgBot {
    void to_json(json& j, const AnswerCallbackQueryRequest& value) {
        j = json{};
        j["callback_query_id"] = value.callback_query_id;
    if (!value.text.empty()) { 
                    j["text"] = value.text; 
            }
    if (value.show_alert) { 
                    j["show_alert"] = value.show_alert; 
            }
    if (!value.url.empty()) { 
                    j["url"] = value.url; 
            }
    if (value.cache_time != 0) { 
                    j["cache_time"] = value.cache_time; 
            }
    }

    void from_json(const json& j, AnswerCallbackQueryRequest& value) {
        if (j.contains("callback_query_id")) {
            j.at("callback_query_id").get_to(value.callback_query_id);
        }
        if (j.contains("text")) {
            j.at("text").get_to(value.text);
        }
        if (j.contains("show_alert")) {
            j.at("show_alert").get_to(value.show_alert);
        }
        if (j.contains("url")) {
            j.at("url").get_to(value.url);
        }
        if (j.contains("cache_time")) {
            j.at("cache_time").get_to(value.cache_time);
        }
    }
}
