// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/CreateChatSubscriptionInviteLinkRequest.hpp"

namespace TgBot {
    void to_json(json& j, const CreateChatSubscriptionInviteLinkRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["subscription_period"] = value.subscription_period;
        j["subscription_price"] = value.subscription_price;
    if (!value.name.empty()) { 
                    j["name"] = value.name; 
            }
    }

    void from_json(const json& j, CreateChatSubscriptionInviteLinkRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("subscription_period")) {
            j.at("subscription_period").get_to(value.subscription_period);
        }
        if (j.contains("subscription_price")) {
            j.at("subscription_price").get_to(value.subscription_price);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
    }
}
