// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/CreateForumTopicRequest.hpp"

namespace TgBot {
    void to_json(json& j, const CreateForumTopicRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["name"] = value.name;
    if (value.icon_color != 0) { 
                    j["icon_color"] = value.icon_color; 
            }
    if (!value.icon_custom_emoji_id.empty()) { 
                    j["icon_custom_emoji_id"] = value.icon_custom_emoji_id; 
            }
    }

    void from_json(const json& j, CreateForumTopicRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("icon_color")) {
            j.at("icon_color").get_to(value.icon_color);
        }
        if (j.contains("icon_custom_emoji_id")) {
            j.at("icon_custom_emoji_id").get_to(value.icon_custom_emoji_id);
        }
    }
}
