// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/DeleteMessagesRequest.hpp"

namespace TgBot {
    void to_json(json& j, const DeleteMessagesRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["message_ids"] = value.message_ids;
    }

    void from_json(const json& j, DeleteMessagesRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("message_ids")) {
            j.at("message_ids").get_to(value.message_ids);
        }
    }
}
