// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/DeleteStickerFromSetRequest.hpp"

namespace TgBot {
    void to_json(json& j, const DeleteStickerFromSetRequest& value) {
        j = json{};
        j["sticker"] = value.sticker;
    }

    void from_json(const json& j, DeleteStickerFromSetRequest& value) {
        if (j.contains("sticker")) {
            j.at("sticker").get_to(value.sticker);
        }
    }
}
