// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/EditUserStarSubscriptionRequest.hpp"

namespace TgBot {
    void to_json(json& j, const EditUserStarSubscriptionRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
        j["telegram_payment_charge_id"] = value.telegram_payment_charge_id;
        j["is_canceled"] = value.is_canceled;
    }

    void from_json(const json& j, EditUserStarSubscriptionRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("telegram_payment_charge_id")) {
            j.at("telegram_payment_charge_id").get_to(value.telegram_payment_charge_id);
        }
        if (j.contains("is_canceled")) {
            j.at("is_canceled").get_to(value.is_canceled);
        }
    }
}
