// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetMyDefaultAdministratorRightsRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetMyDefaultAdministratorRightsRequest& value) {
        j = json{};
    if (value.for_channels) { 
                    j["for_channels"] = value.for_channels; 
            }
    }

    void from_json(const json& j, GetMyDefaultAdministratorRightsRequest& value) {
        if (j.contains("for_channels")) {
            j.at("for_channels").get_to(value.for_channels);
        }
    }
}
