// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/GetUserProfilePhotosRequest.hpp"

namespace TgBot {
    void to_json(json& j, const GetUserProfilePhotosRequest& value) {
        j = json{};
        j["user_id"] = value.user_id;
    if (value.offset != 0) { 
                    j["offset"] = value.offset; 
            }
    if (value.limit != 0) { 
                    j["limit"] = value.limit; 
            }
    }

    void from_json(const json& j, GetUserProfilePhotosRequest& value) {
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("offset")) {
            j.at("offset").get_to(value.offset);
        }
        if (j.contains("limit")) {
            j.at("limit").get_to(value.limit);
        }
    }
}
