// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SendPollRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SendPollRequest& value) {
        j = json{};
        j["chat_id"] = value.chat_id;
        j["question"] = value.question;
        j["options"] = value.options;
    if (!value.business_connection_id.empty()) { 
                    j["business_connection_id"] = value.business_connection_id; 
            }
    if (value.message_thread_id != 0) { 
                    j["message_thread_id"] = value.message_thread_id; 
            }
    if (!value.question_parse_mode.empty()) { 
                    j["question_parse_mode"] = value.question_parse_mode; 
            }
    if (!value.question_entities.empty()) { 
                    j["question_entities"] = value.question_entities; 
            }
    if (value.is_anonymous) { 
                    j["is_anonymous"] = value.is_anonymous; 
            }
    if (!value.type_.empty()) { 
                    j["type"] = value.type_; 
            }
    if (value.allows_multiple_answers) { 
                    j["allows_multiple_answers"] = value.allows_multiple_answers; 
            }
    if (value.correct_option_id != 0) { 
                    j["correct_option_id"] = value.correct_option_id; 
            }
    if (!value.explanation.empty()) { 
                    j["explanation"] = value.explanation; 
            }
    if (!value.explanation_parse_mode.empty()) { 
                    j["explanation_parse_mode"] = value.explanation_parse_mode; 
            }
    if (!value.explanation_entities.empty()) { 
                    j["explanation_entities"] = value.explanation_entities; 
            }
    if (value.open_period != 0) { 
                    j["open_period"] = value.open_period; 
            }
    if (value.close_date != 0) { 
                    j["close_date"] = value.close_date; 
            }
    if (value.is_closed) { 
                    j["is_closed"] = value.is_closed; 
            }
    if (value.disable_notification) { 
                    j["disable_notification"] = value.disable_notification; 
            }
    if (value.protect_content) { 
                    j["protect_content"] = value.protect_content; 
            }
    if (value.allow_paid_broadcast) { 
                    j["allow_paid_broadcast"] = value.allow_paid_broadcast; 
            }
    if (!value.message_effect_id.empty()) { 
                    j["message_effect_id"] = value.message_effect_id; 
            }
    if (value.reply_parameters) { 
                    j["reply_parameters"] = value.reply_parameters; 
            }
    if (value.reply_markup) { 
                    j["reply_markup"] = value.reply_markup; 
            }
    }

    void from_json(const json& j, SendPollRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("question")) {
            j.at("question").get_to(value.question);
        }
        if (j.contains("options")) {
            j.at("options").get_to(value.options);
        }
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("message_thread_id")) {
            j.at("message_thread_id").get_to(value.message_thread_id);
        }
        if (j.contains("question_parse_mode")) {
            j.at("question_parse_mode").get_to(value.question_parse_mode);
        }
        if (j.contains("question_entities")) {
            j.at("question_entities").get_to(value.question_entities);
        }
        if (j.contains("is_anonymous")) {
            j.at("is_anonymous").get_to(value.is_anonymous);
        }
        if (j.contains("type")) {
            j.at("type").get_to(value.type_);
        }
        if (j.contains("allows_multiple_answers")) {
            j.at("allows_multiple_answers").get_to(value.allows_multiple_answers);
        }
        if (j.contains("correct_option_id")) {
            j.at("correct_option_id").get_to(value.correct_option_id);
        }
        if (j.contains("explanation")) {
            j.at("explanation").get_to(value.explanation);
        }
        if (j.contains("explanation_parse_mode")) {
            j.at("explanation_parse_mode").get_to(value.explanation_parse_mode);
        }
        if (j.contains("explanation_entities")) {
            j.at("explanation_entities").get_to(value.explanation_entities);
        }
        if (j.contains("open_period")) {
            j.at("open_period").get_to(value.open_period);
        }
        if (j.contains("close_date")) {
            j.at("close_date").get_to(value.close_date);
        }
        if (j.contains("is_closed")) {
            j.at("is_closed").get_to(value.is_closed);
        }
        if (j.contains("disable_notification")) {
            j.at("disable_notification").get_to(value.disable_notification);
        }
        if (j.contains("protect_content")) {
            j.at("protect_content").get_to(value.protect_content);
        }
        if (j.contains("allow_paid_broadcast")) {
            j.at("allow_paid_broadcast").get_to(value.allow_paid_broadcast);
        }
        if (j.contains("message_effect_id")) {
            j.at("message_effect_id").get_to(value.message_effect_id);
        }
        if (j.contains("reply_parameters")) {
            j.at("reply_parameters").get_to(value.reply_parameters);
        }
        if (j.contains("reply_markup")) {
            j.at("reply_markup").get_to(value.reply_markup);
        }
    }
}
