// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetBusinessAccountNameRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetBusinessAccountNameRequest& value) {
        j = json{};
        j["business_connection_id"] = value.business_connection_id;
        j["first_name"] = value.first_name;
    if (!value.last_name.empty()) { 
                    j["last_name"] = value.last_name; 
            }
    }

    void from_json(const json& j, SetBusinessAccountNameRequest& value) {
        if (j.contains("business_connection_id")) {
            j.at("business_connection_id").get_to(value.business_connection_id);
        }
        if (j.contains("first_name")) {
            j.at("first_name").get_to(value.first_name);
        }
        if (j.contains("last_name")) {
            j.at("last_name").get_to(value.last_name);
        }
    }
}
