// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetChatMenuButtonRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetChatMenuButtonRequest& value) {
        j = json{};
    if (value.chat_id != 0) { 
                    j["chat_id"] = value.chat_id; 
            }
    if (value.menu_button) { 
                    j["menu_button"] = value.menu_button; 
            }
    }

    void from_json(const json& j, SetChatMenuButtonRequest& value) {
        if (j.contains("chat_id")) {
            j.at("chat_id").get_to(value.chat_id);
        }
        if (j.contains("menu_button")) {
            j.at("menu_button").get_to(value.menu_button);
        }
    }
}
