// Auto-generated Telegram Bot API models for C++
// Generated by telegram-api-generator. Do not edit manually.

#include "requests/SetStickerSetThumbnailRequest.hpp"

namespace TgBot {
    void to_json(json& j, const SetStickerSetThumbnailRequest& value) {
        j = json{};
        j["name"] = value.name;
        j["user_id"] = value.user_id;
        j["format"] = value.format;
    if (!value.thumbnail.empty()) { 
                        j["thumbnail"] = value.thumbnail; 
                }
    }

    void from_json(const json& j, SetStickerSetThumbnailRequest& value) {
        if (j.contains("name")) {
            j.at("name").get_to(value.name);
        }
        if (j.contains("user_id")) {
            j.at("user_id").get_to(value.user_id);
        }
        if (j.contains("format")) {
            j.at("format").get_to(value.format);
        }
        if (j.contains("thumbnail")) {
            j.at("thumbnail").get_to(value.thumbnail);
        }
    }
}
